//! # `canvas::cursor` — pdfcer's own crosshair, because the platform's is invisible
//!
//!
//! > *"The crosshairs when over the canvas are white making it hard to see
//! > them."*
//!
//! Design and rationale: `docs/modules/pdfcer-gui/canvas/cursor.md`.

use std::sync::{Arc, Mutex, OnceLock};

use egui::CustomCursorImage;

/// The crosshair's logical size, in egui points, before UI scale.
const LOGICAL_SIZE_PTS: f32 = 32.0;

/// The largest bitmap `winit::window::CustomCursor` will accept, per its own
/// `MAX_CURSOR_SIZE`. Named rather than inlined because exceeding it is not a
/// panic — it is a silent fall back to the platform crosshair, i.e. to the
/// defect this module exists to fix — so the clamp has to be deliberate.
const MAX_CURSOR_PX: u32 = 2048;

/// Arm length from the centre, in points: where the drawn part of each arm
/// ends.
const ARM_PTS: f32 = 12.0;

/// Gap radius, in points: nothing is drawn within this of the centre.
const GAP_PTS: f32 = 3.0;

/// The generated bitmaps, keyed by their pixel size.
static CACHE: OnceLock<Mutex<Vec<(u32, CustomCursorImage)>>> = OnceLock::new();

/// The crosshair cursor bitmap for this scale factor.
#[must_use]
pub fn crosshair(pixels_per_point: f32) -> CustomCursorImage {
    let scale = if pixels_per_point.is_finite() && pixels_per_point > 0.0 {
        pixels_per_point
    } else {
        1.0
    };
    #[allow(
        clippy::cast_possible_truncation,
        clippy::cast_sign_loss,
        reason = "the value is clamped into 1..=MAX_CURSOR_PX on the line below, so neither can occur" // ui-text-exempt: lint justification, never displayed
    )]
    let size = ((LOGICAL_SIZE_PTS * scale).round() as u32).clamp(1, MAX_CURSOR_PX);

    let cache = CACHE.get_or_init(|| Mutex::new(Vec::new()));
    // `unwrap_or_else(PoisonError::into_inner)` rather than `unwrap`: a panic
    // while this lock was held would otherwise cost the operator their cursor
    // for the rest of the session, and the worst a possibly-stale cache can do
    // is hand back a correct bitmap that was generated by the thread that
    // panicked.
    let mut cache = cache
        .lock()
        .unwrap_or_else(std::sync::PoisonError::into_inner);
    if let Some((_, image)) = cache.iter().find(|(key, _)| *key == size) {
        return image.clone();
    }
    let image = render(size, scale);
    cache.push((size, image.clone()));
    image
}

/// **How far the I-beam is turned from upright**, in whole degrees, folded into
/// `0..180` and quantised.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub struct Tilt(u16);

impl Tilt {
    /// The default: an upright beam, for text that runs along the page.
    pub const UPRIGHT: Self = Self(0);

    /// The quantisation step, in degrees. See the type's docs.
    const STEP: u16 = 5;

    /// The tilt nearest `degrees`, folded and quantised.
    #[must_use]
    pub fn nearest(degrees: f32) -> Self {
        if !degrees.is_finite() {
            return Self::UPRIGHT;
        }
        let folded = degrees.rem_euclid(180.0);
        #[allow(
            clippy::cast_possible_truncation,
            clippy::cast_sign_loss,
            reason = "folded is in 0..180 and the quotient is in 0..36" // ui-text-exempt: lint justification, never displayed
        )]
        let steps = (folded / f32::from(Self::STEP)).round() as u16;
        // 180° rounds up to step 36, which is 0° again — the fold, applied once
        // more after rounding rather than trusted to have survived it.
        Self((steps * Self::STEP) % 180)
    }

    /// The angle in degrees.
    #[must_use]
    pub const fn degrees(self) -> u16 {
        self.0
    }

    /// Whether this is the ordinary upright beam.
    #[must_use]
    pub const fn is_upright(self) -> bool {
        self.0 == 0
    }
}

/// The two-tone I-beam at `tilt`, cached per `(pixel size, tilt)` exactly as
/// [`crosshair`] is cached per pixel size.
#[must_use]
pub fn ibeam(pixels_per_point: f32, tilt: Tilt) -> CustomCursorImage {
    let scale = if pixels_per_point.is_finite() && pixels_per_point > 0.0 {
        pixels_per_point
    } else {
        1.0
    };
    #[allow(
        clippy::cast_possible_truncation,
        clippy::cast_sign_loss,
        reason = "clamped into 1..=MAX_CURSOR_PX on the same line" // ui-text-exempt: lint justification, never displayed
    )]
    let size = ((LOGICAL_SIZE_PTS * scale).round() as u32).clamp(1, MAX_CURSOR_PX);

    let cache = IBEAM_CACHE.get_or_init(|| Mutex::new(Vec::new()));
    let mut cache = cache
        .lock()
        .unwrap_or_else(std::sync::PoisonError::into_inner);
    if let Some((_, _, img)) = cache
        .iter()
        .find(|(key, angle, _)| *key == size && *angle == tilt)
    {
        return img.clone();
    }
    let img = render_ibeam(size, scale, tilt);
    cache.push((size, tilt, img.clone()));
    img
}

/// Cache for [`ibeam`], separate from the crosshair's.
static IBEAM_CACHE: OnceLock<Mutex<Vec<(u32, Tilt, CustomCursorImage)>>> = OnceLock::new();

/// Draw the I-beam: a dark bar with serifs, haloed in light, turned by `tilt`.
fn render_ibeam(size: u32, scale: f32, tilt: Tilt) -> CustomCursorImage {
    let mut rgba = vec![0u8; (size as usize) * (size as usize) * 4];
    let px = |pts: f32| (pts * scale).round().max(1.0) as i32;
    #[allow(
        clippy::cast_possible_wrap,
        reason = "size is clamped to MAX_CURSOR_PX, far inside i32" // ui-text-exempt: lint justification, never displayed
    )]
    let n = size as i32;
    let centre = n / 2;
    let half_height = px(IBEAM_HEIGHT_PTS / 2.0).min(centre);
    let serif = px(IBEAM_SERIF_PTS).min(centre - 1).max(1);
    // Same asymmetry the crosshair uses and for the same reason: the dark core
    // stays a hairline so the operator can see exactly which glyph boundary the
    // caret will land on, and the light halo takes the extra pixels because its
    // whole job is to be seen against whatever is underneath.
    let core = px(IBEAM_CORE_PTS).max(1);
    let halo = core + 2;

    let radians = f32::from(tilt.degrees()).to_radians();
    let (sin, cos) = radians.sin_cos();

    let mut put = |x: i32, y: i32, white: bool| {
        if x < 0 || y < 0 || x >= n || y >= n {
            return;
        }
        let at = ((y * n + x) as usize) * 4;
        let value = if white { 0xFF } else { 0x00 };
        rgba[at] = value;
        rgba[at + 1] = value;
        rgba[at + 2] = value;
        rgba[at + 3] = 0xFF;
    };
    // How wide a pixel is, measured across the beam's own axes.
    //
    // **Without it a tilted hairline comes out dotted.** The core is one device
    // pixel wide at ordinary scales (deliberately — see below), so a bare test
    // of `|across| <= 0` selects at most one pixel per scanline; where the beam
    // is not axis-aligned, consecutive scanlines can then step two columns
    // apart and the line breaks into dashes.
    //
    // The value is derived rather than fudged, and the derivation is what
    // stops it being too generous. Walking one step along the beam's dominant
    // axis changes `across` by `max(|cos|, |sin|)`, so a tolerance of **half
    // that** guarantees at least one pixel per scanline and nothing more:
    //
    // | tilt | `max(\|cos\|,\|sin\|)` | spread | a one-pixel core comes out as |
    // |---|---|---|---|
    // | 0° / 90° | 1.0 | 0.5 | one pixel — exactly the columns the upright version drew |
    // | 45° | 0.707 | 0.354 | one pixel per anti-diagonal: a clean 1-px staircase |
    //
    let spread = 0.5 * cos.abs().max(sin.abs());
    let mut bar = |width: i32, white: bool| {
        let half = (width / 2) as f32;
        // Where the serif slab begins, as a distance from the centre: the
        // outermost `width` rows at each end, which is what the upright version
        // drew by counting `dy in 0..width` inwards from the tip.
        let serif_from = f32::from(i16::try_from((half_height - width + 1).max(0)).unwrap_or(0));
        for y in 0..n {
            for x in 0..n {
                // Into the beam's own upright frame. Offsets are whole pixels
                // from the hotspot, exactly as the upright version indexed
                // them, so the glyph stays centred on the hotspot at every
                // angle rather than drifting half a pixel.
                let dx = (x - centre) as f32;
                let dy = (y - centre) as f32;
                let across = dx.mul_add(cos, dy * sin);
                let along = dx.mul_add(-sin, dy * cos);
                let within_length = along.abs() <= half_height as f32 + spread;
                let in_bar = across.abs() <= half + spread && within_length;
                let in_serif = across.abs() <= serif as f32 + spread
                    && within_length
                    && along.abs() >= serif_from - spread;
                if in_bar || in_serif {
                    put(x, y, white);
                }
            }
        }
    };
    bar(halo, true);
    bar(core, false);

    CustomCursorImage {
        rgba: Arc::from(rgba),
        #[allow(
            clippy::cast_possible_truncation,
            reason = "size is clamped to MAX_CURSOR_PX = 2048, inside u16" // ui-text-exempt: lint justification, never displayed
        )]
        size: [size as u16, size as u16],
        #[allow(
            clippy::cast_possible_truncation,
            reason = "centre is half of a value clamped to 2048" // ui-text-exempt: lint justification, never displayed
        )]
        hotspot: [centre as u16, centre as u16],
    }
}

/// Total height of the I-beam, in logical points.
const IBEAM_HEIGHT_PTS: f32 = 15.0;
/// How far each serif reaches from the centre line.
const IBEAM_SERIF_PTS: f32 = 3.0;
/// Width of the dark core bar.
const IBEAM_CORE_PTS: f32 = 1.0;

/// Draw the glyph into a fresh buffer.
fn render(size: u32, scale: f32) -> CustomCursorImage {
    // Straight (non-premultiplied) RGBA, four bytes per pixel, fully
    // transparent everywhere the glyph is not. `CustomCursorImage` documents
    // the encoding and `winit::window::CustomCursor::from_rgba` requires it.
    //
    // NOT A THEME COLOUR: black and white, deliberately and permanently — see
    // the module header. These contrast with the operator's DOCUMENT, which is
    // content pdfcer does not control and no palette can be right about.
    let mut rgba = vec![0_u8; (size as usize) * (size as usize) * 4];

    // The centre is the hotspot, and it must be a whole pixel: a hotspot half a
    // pixel away from the crossing point puts every click one pixel from where
    // the operator aimed, which is invisible until somebody dimensions with it.
    let centre = (size / 2) as i32;

    let px = |points: f32| -> i32 { (points * scale).round().max(1.0) as i32 };

    // The core stays a HAIRLINE and the halo grows. That asymmetry is the
    // design, not an oversight in the scaling.
    //
    // A crosshair is an aiming device: its value is that the operator can see
    // exactly which pixel they are about to pick, and every extra pixel of core
    // takes that away. So the core is one device pixel at ordinary scales and
    // reaches three only past 200 %, where one device pixel has become too fine
    // to see at all. Both are ODD widths, which is required rather than
    // preferred — an even-width line has no centre pixel, so the hotspot would
    // sit half a pixel off the line it is meant to be the centre of.
    //
    // The halo has the opposite job: it exists to be seen against whatever is
    // underneath, so it takes the pixels the core does not.
    let core_half = i32::from(scale >= 2.0);
    let halo_half = core_half + (scale * 0.75).round().max(1.0) as i32;
    let gap = px(GAP_PTS);
    let arm = px(ARM_PTS).min(centre);

    let mut put = |x: i32, y: i32, white: bool| {
        if x < 0 || y < 0 || x >= size as i32 || y >= size as i32 {
            return;
        }
        let at = ((y as usize) * (size as usize) + (x as usize)) * 4;
        let value = if white { 0xFF } else { 0x00 };
        rgba[at] = value;
        rgba[at + 1] = value;
        rgba[at + 2] = value;
        rgba[at + 3] = 0xFF;
    };

    // Each of the four arms, twice: the halo runs one pixel further at both
    // ends than the core so the core's tip is capped rather than left bare.
    for (white, half, from, to) in [
        (true, halo_half, gap - px(1.0), arm + px(1.0)),
        (false, core_half, gap, arm),
    ] {
        for along in from.max(0)..=to {
            for across in -half..=half {
                // Horizontal arms, left and right.
                put(centre - along, centre + across, white);
                put(centre + along, centre + across, white);
                // Vertical arms, up and down.
                put(centre + across, centre - along, white);
                put(centre + across, centre + along, white);
            }
        }
    }

    CustomCursorImage {
        rgba: Arc::from(rgba),
        #[allow(
            clippy::cast_possible_truncation,
            reason = "size is clamped to MAX_CURSOR_PX = 2048, which fits u16" // ui-text-exempt: lint justification, never displayed
        )]
        size: [size as u16, size as u16],
        #[allow(
            clippy::cast_possible_truncation,
            reason = "centre is size/2 and size fits u16" // ui-text-exempt: lint justification, never displayed
        )]
        hotspot: [centre as u16, centre as u16],
    }
}

/// Whether the crosshair was wanted on the last frame that asked.
///
/// `u32`: `0` means "not wanted", anything else is the pixel size that was
/// applied. Only [`apply`] touches it.
static LAST_APPLIED: std::sync::atomic::AtomicU32 = std::sync::atomic::AtomicU32::new(0);

/// Ask for the crosshair, or don't, and **trace the transition**.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Shape {
    /// The picking crosshair, for an armed tool.
    Crosshair,
    /// The text I-beam, for selecting or editing text on the page, **turned to
    /// match the text under the pointer**.
    ///
    /// The angle rides on the variant rather than beside it because a shape and
    /// its orientation are one answer to one question: [`apply`] keys its cache
    /// and its change detection on the whole `Shape`, and a tilt stored
    /// separately would let the two disagree — the classic form of which is a
    /// cursor that turns once and then never again. See [`Tilt`].
    Ibeam(Tilt),
}

impl Shape {
    /// The `egui` icon this replaces, so one call site can decide.
    #[must_use]
    pub const fn of(icon: egui::CursorIcon) -> Option<Self> {
        match icon {
            egui::CursorIcon::Crosshair => Some(Self::Crosshair),
            // Upright, always: this function knows only which *stock* icon the
            // frame asked for, and nothing about what is under the pointer. The
            // tilt is applied afterwards by the one caller that has the page's
            // text — `canvas::interact` — because turning the beam requires an
            // extraction and a pure icon mapping must not reach for one.
            egui::CursorIcon::Text => Some(Self::Ibeam(Tilt::UPRIGHT)),
            _ => None,
        }
    }

    /// The trace word, so a reader can tell the two apart.
    const fn label(self) -> &'static str {
        match self {
            // ui-text-exempt: diagnostic trace values, never displayed
            Self::Crosshair => "crosshair",
            Self::Ibeam(_) => "ibeam",
        }
    }

    /// How far this shape is turned from upright, in degrees.
    ///
    /// Zero for the crosshair, which is rotationally symmetric to within its
    /// own arms and would say nothing by turning.
    const fn degrees(self) -> u16 {
        match self {
            Self::Crosshair => 0,
            Self::Ibeam(tilt) => tilt.degrees(),
        }
    }
}

/// The bitmap for a shape at this scale, cached per `(shape, size)`.
#[must_use]
pub fn image(shape: Shape, pixels_per_point: f32) -> CustomCursorImage {
    match shape {
        Shape::Crosshair => crosshair(pixels_per_point),
        Shape::Ibeam(tilt) => ibeam(pixels_per_point, tilt),
    }
}

pub fn apply(ctx: &egui::Context, wanted: Option<Shape>) {
    use std::sync::atomic::Ordering;

    let size = if let Some(shape) = wanted {
        let image = image(shape, ctx.pixels_per_point());
        let size = u32::from(image.size[0]);
        ctx.set_cursor_image(Some(image));
        // The shape AND its angle ride in the low bits beside the size, so a
        // change of either at one scale is still a change. Without the shape
        // bit, switching from crosshair to I-beam at the same scale would trace
        // nothing; without the angle, an I-beam turning from upright to 90°
        // would trace nothing — and the angle is the half a screenshot cannot
        // check, because Windows composites the pointer separately and
        // `ui-verify`'s window capture contains no cursor at any price.
        //
        // `+ 1` on the shape bit rather than a bare boolean, so the whole
        // packed value stays non-zero for any real cursor: zero is reserved for
        // "none wanted", and an upright crosshair at a zero-width scale must
        // not collide with it.
        (size * 512 + u32::from(shape.degrees()) * 2) + u32::from(matches!(shape, Shape::Ibeam(_)))
    } else {
        // Deliberately does NOT clear: `crate::app::frame` has already done it
        // for this frame, before anything drew. Clearing again here would be a
        // second owner of the same state, and the frame-level one is the only
        // one that covers a frame this function never reaches.
        0
    };

    if LAST_APPLIED.swap(size, Ordering::Relaxed) != size {
        crate::diag::trace(move || match wanted {
            // ui-text-exempt: diagnostic trace, never displayed in the UI
            None => "cursor-custom off".to_owned(),
            Some(shape) => format!(
                // ui-text-exempt: diagnostic trace, never displayed in the UI
                "cursor-custom on shape={} deg={} px={}",
                shape.label(),
                shape.degrees(),
                size / 512
            ),
        });
    }
}

#[cfg(test)]
mod tests {

    /// The I-beam has a DARK core, which is the whole of the operator's
    /// report.
    #[test]
    fn the_ibeam_core_is_dark_and_its_halo_is_light() {
        let img = ibeam(1.0, Tilt::UPRIGHT);
        let n = usize::from(img.size[0]);
        let at = |x: usize, y: usize| {
            let i = (y * n + x) * 4;
            (img.rgba[i], img.rgba[i + 3])
        };
        let c = n / 2;
        assert_eq!(at(c, c), (0x00, 0xFF), "the core must be opaque black");
        // One pixel out along the bar's width is halo — the core is a
        // HAIRLINE by design, exactly as the crosshair's is, so the operator
        // can see which glyph boundary the caret will land on.
        assert_eq!(
            at(c + 1, c),
            (0xFF, 0xFF),
            "the halo must be opaque white so the core is legible on dark ink too"
        );
        assert_eq!(
            at(c + 2, c).1,
            0x00,
            "and the glyph must end there rather than smearing"
        );
    }

    /// The glyph is taller than it is wide, which is what makes it an I-beam.
    #[test]
    fn the_ibeam_is_a_bar_and_not_a_blob() {
        let img = ibeam(1.0, Tilt::UPRIGHT);
        let n = usize::from(img.size[0]);
        let opaque = |x: usize, y: usize| img.rgba[(y * n + x) * 4 + 3] == 0xFF;
        let c = n / 2;
        let tall = (0..n).filter(|&y| opaque(c, y)).count();
        let wide = (0..n).filter(|&x| opaque(x, c)).count();
        assert!(
            tall > wide * 2,
            "an I-beam is a vertical bar: {tall} tall against {wide} wide"
        );
    }

    /// The two shapes map from the two `egui` icons and nothing else does.
    #[test]
    fn only_the_two_cursors_drawn_over_paper_are_replaced() {
        assert_eq!(
            Shape::of(egui::CursorIcon::Crosshair),
            Some(Shape::Crosshair)
        );
        assert_eq!(
            Shape::of(egui::CursorIcon::Text),
            Some(Shape::Ibeam(Tilt::UPRIGHT)),
            "the stock icon maps to an UPRIGHT beam; the tilt is applied later, \
             by the caller that knows what the pointer is over"
        );
        for stock in [
            egui::CursorIcon::Default,
            egui::CursorIcon::PointingHand,
            egui::CursorIcon::ResizeVertical,
            egui::CursorIcon::Grab,
        ] {
            assert_eq!(Shape::of(stock), None, "{stock:?} is chrome, not paper");
        }
    }
    use super::*;

    /// The four values `CustomCursorImage` promises about itself.
    #[test]
    fn the_bitmap_matches_the_size_it_declares() {
        for ppp in [1.0_f32, 1.25, 1.5, 2.0, 3.0] {
            let image = crosshair(ppp);
            let (w, h) = (usize::from(image.size[0]), usize::from(image.size[1]));
            assert_eq!(
                image.rgba.len(),
                w * h * 4,
                "the buffer must be exactly w * h * 4 at {ppp}"
            );
            assert!(w > 0 && h > 0, "a zero-sized cursor at {ppp}");
            assert!(
                u32::from(image.size[0]) <= MAX_CURSOR_PX,
                "winit rejects anything over {MAX_CURSOR_PX} and falls back to the platform \
                 cursor, which is the defect"
            );
        }
    }

    /// The hotspot is the crossing point, and it is not painted.
    #[test]
    fn the_hotspot_is_the_centre_and_the_centre_is_clear() {
        let image = crosshair(1.0);
        let size = usize::from(image.size[0]);
        let (hx, hy) = (usize::from(image.hotspot[0]), usize::from(image.hotspot[1]));
        assert_eq!(hx, size / 2, "the hotspot must be the centre column");
        assert_eq!(hy, size / 2, "the hotspot must be the centre row");

        let alpha_at = |x: usize, y: usize| image.rgba[(y * size + x) * 4 + 3];
        assert_eq!(
            alpha_at(hx, hy),
            0,
            "the pixel under the hotspot must be clear — a crosshair that paints its own \
             target hides the line the operator is aiming at"
        );
    }

    /// Both tones are present, and the dark one is surrounded by the light.
    #[test]
    fn an_arm_is_a_dark_core_inside_a_light_halo() {
        let image = crosshair(1.0);
        let size = usize::from(image.size[0]);
        let centre = size / 2;
        let sample = |x: usize, y: usize| {
            let at = (y * size + x) * 4;
            (image.rgba[at], image.rgba[at + 3])
        };

        // Along the upward arm, a few pixels clear of the gap.
        let y = centre - 8;
        assert_eq!(
            sample(centre, y),
            (0x00, 0xFF),
            "the core of an arm must be opaque black"
        );
        assert_eq!(
            sample(centre - 1, y),
            (0xFF, 0xFF),
            "the pixel beside the core must be opaque white — without the halo the cursor is \
             invisible on a dark page, which is the operator's report"
        );
        assert_eq!(
            sample(centre + 1, y),
            (0xFF, 0xFF),
            "…and on the other side too"
        );
    }

    /// Repeated calls at one scale return the SAME allocation.
    #[test]
    fn the_same_scale_returns_the_same_allocation() {
        let a = crosshair(1.0);
        let b = crosshair(1.0);
        assert!(
            Arc::ptr_eq(&a.rgba, &b.rgba),
            "two calls at one scale must share the cached buffer, or egui-winit re-uploads the \
             cursor to the OS on every frame"
        );
        let c = crosshair(2.0);
        assert!(
            !Arc::ptr_eq(&a.rgba, &c.rgba),
            "a different scale is a different bitmap"
        );
    }

    /// The quantiser folds, rounds and refuses nonsense.
    #[test]
    fn the_tilt_quantises_and_folds() {
        for (given, expect) in [
            (0.0_f32, 0),
            (2.0, 0),
            (3.0, 5),
            (89.0, 90),
            (90.0, 90),
            (92.4, 90),
            // A half turn is the same glyph, so it folds to upright.
            (180.0, 0),
            (185.0, 5),
            // Negative, which is what an `atan2` in a Y-down space gives for
            // text running UP the page — the operator's own case.
            (-90.0, 90),
            (-5.0, 175),
            (f32::NAN, 0),
            (f32::INFINITY, 0),
        ] {
            assert_eq!(
                Tilt::nearest(given).degrees(),
                expect,
                "Tilt::nearest({given}) should be {expect}°"
            );
            assert!(
                Tilt::nearest(given).degrees() < 180,
                "every tilt must fold into 0..180"
            );
        }
    }

    /// **A 90° I-beam is a HORIZONTAL bar**, which is the whole of what the
    /// operator asked for.
    #[test]
    fn a_quarter_turned_ibeam_is_a_horizontal_bar() {
        let img = ibeam(1.0, Tilt::nearest(90.0));
        let n = usize::from(img.size[0]);
        let opaque = |x: usize, y: usize| img.rgba[(y * n + x) * 4 + 3] == 0xFF;
        let c = n / 2;
        let tall = (0..n).filter(|&y| opaque(c, y)).count();
        let wide = (0..n).filter(|&x| opaque(x, c)).count();
        assert!(
            wide > tall * 2,
            "a 90° I-beam should lie on its side: {tall} tall against {wide} wide"
        );
    }

    /// **And it keeps its dark core**, at every angle.
    #[test]
    fn the_core_stays_dark_at_every_angle() {
        for degrees in [0.0_f32, 30.0, 90.0, 135.0] {
            let img = ibeam(1.0, Tilt::nearest(degrees));
            let n = usize::from(img.size[0]);
            let c = n / 2;
            let i = (c * n + c) * 4;
            assert_eq!(
                (img.rgba[i], img.rgba[i + 3]),
                (0x00, 0xFF),
                "the core must be opaque black at {degrees}°"
            );
        }
    }

    /// **The cache tells two angles apart.**
    #[test]
    fn the_ibeam_cache_is_keyed_by_angle_as_well_as_size() {
        let upright = ibeam(1.0, Tilt::UPRIGHT);
        let again = ibeam(1.0, Tilt::UPRIGHT);
        assert!(
            Arc::ptr_eq(&upright.rgba, &again.rgba),
            "one angle at one scale must share its cached buffer"
        );
        let turned = ibeam(1.0, Tilt::nearest(90.0));
        assert!(
            !Arc::ptr_eq(&upright.rgba, &turned.rgba),
            "a different angle must be a different bitmap, or the cursor turns once and never again"
        );
        assert_ne!(
            &*upright.rgba, &*turned.rgba,
            "and the pixels must actually differ, not merely the allocation"
        );
    }

    /// A turned I-beam is still a valid cursor bitmap.
    #[test]
    fn a_turned_bitmap_still_matches_the_size_it_declares() {
        for degrees in [0.0_f32, 45.0, 90.0, 175.0] {
            for ppp in [1.0_f32, 2.0] {
                let image = ibeam(ppp, Tilt::nearest(degrees));
                let (w, h) = (usize::from(image.size[0]), usize::from(image.size[1]));
                assert_eq!(
                    image.rgba.len(),
                    w * h * 4,
                    "the buffer must be exactly w * h * 4 at {degrees}° and {ppp}x"
                );
            }
        }
    }

    /// A nonsense scale lands on the clamp rather than on an allocation.
    #[test]
    fn a_nonsense_scale_is_clamped_rather_than_allocated() {
        for ppp in [0.0_f32, -3.0, f32::NAN, f32::INFINITY, 1.0e9] {
            let image = crosshair(ppp);
            assert!(
                u32::from(image.size[0]) <= MAX_CURSOR_PX && image.size[0] > 0,
                "a scale of {ppp} produced a {}px cursor",
                image.size[0]
            );
        }
    }
}

#[cfg(test)]
mod preview {
    use super::Tilt;

    /// Dump the raw bitmap so a human can look at it. `--ignored`.
    #[test]
    #[ignore]
    fn dump() {
        for ppp in [1.0_f32, 2.0] {
            let image = super::crosshair(ppp);
            // temp-path-exempt: an `#[ignore]`d developer dump. A stable name
            // is the point -- a human runs this deliberately and then opens
            // the file it printed; a pid in the name would mean hunting.
            let name = std::env::temp_dir().join(format!("crosshair-{}.rgba", image.size[0]));
            std::fs::write(&name, &*image.rgba).expect("write");
            println!("{} {}x{}", name.display(), image.size[0], image.size[1]);
        }
    }

    /// **Print the I-beam as ASCII at several angles**, so a human can check
    /// the shape with their eyes. `--ignored`.
    #[test]
    #[ignore]
    fn ibeam_ascii() {
        for degrees in [0.0_f32, 30.0, 45.0, 90.0, 135.0] {
            let img = super::ibeam(1.0, Tilt::nearest(degrees));
            let n = usize::from(img.size[0]);
            println!(
                "\n--- {degrees}° ({}°) ---",
                Tilt::nearest(degrees).degrees()
            );
            for y in 0..n {
                let row: String = (0..n)
                    .map(|x| {
                        let i = (y * n + x) * 4;
                        match (img.rgba[i + 3], img.rgba[i]) {
                            (0, _) => ' ',
                            (_, 0) => '#',
                            _ => '.',
                        }
                    })
                    .collect();
                println!("{row}");
            }
        }
    }
}
