//! `a_comment_can_be_read_on_the_page_in_read_mode` — **the operator's report
//! of 2026-09-05, turned into a gate.**
//!
//! ⬜ **NOT RUN. Written 2026-09-05 and never driven.** The operator was at his
//! keyboard for the whole session and this harness takes the foreground of the
//! entire desktop, so no window was launched. Nothing below has been observed
//! working. ★ And a layout-and-clipping change like this one has **exactly one
//! oracle — a rendered screenshot — and none was taken.** The unit tests behind
//! it are green and that is a different claim.
//!
//! # The report
//!
//! > *"check how the review functions work. unless something has changed I
//! > could add a yellow sticky note but even in read mode I don't think I could
//! > figure out how to read it. the review features should look and act the
//! > same as they do in Acrobat Reader."*
//!
//! He was right, and the measurement was worse than the report: the only route
//! to a note's `/Contents` in the whole shell was the Comments panel, whose
//! command is `markup.comments` on the **Markup** tab, and Read mode is shown
//! `["file", "view"]`. So in Read mode there was **no route at all** — a mode
//! named Read that could not read the comments.
//!
//! # ★★★ Why this cannot be a unit test, in the specific
//!
//! The pop-up is an `egui::Area` at `Order::Middle`, positioned from a page
//! rectangle through this frame's `PageMapping` and constrained to the canvas
//! viewport. **Every one of those four things is invisible to a unit test**,
//! and the failure they produce is not a wrong value — it is a window that
//! laid out perfectly and is off the edge of the canvas, or behind the docked
//! panels, or under the page it belongs to.
//!
//! `REVIEW_TRIAGE.md` T4 records three panels shipping **unreachable in real
//! builds with every gate green**, because every driven assertion about them
//! proved *layout* rather than *visibility*. This check uses
//! `crate::diag::ui_rect_visible`'s own contract to avoid repeating that: that
//! function **publishes nothing at all** unless the rectangle is visible enough
//! inside the clip it was given, so the mere presence of `notepopup.window` in
//! the trace is a visibility claim rather than a layout one.
//!
//! # The fixture is PINNED, and `--pdf` is ignored
//!
//! `fixtures/comment-note.pdf`, regenerated by
//! `python tools/gen-comment-note-fixture.py`. Two checks in this suite already
//! pin their own fixture for this reason and say so when a `--pdf` was supplied
//! and thrown away, *"because a sweep that silently ignored a flag is
//! indistinguishable from one that honoured it."*
//!
//! ★★★ **The pinning is not convenience, it is the difference between this
//! check being able to fail and not.** `RESUME.md`'s falsification discipline
//! names the trap: *"a fixture note with empty `/Contents` makes 'the pop-up
//! shows the words' pass on a build that shows nothing."* An arbitrary CAD
//! sheet has no comments at all, on which this check would SKIP forever and
//! report nothing while looking healthy. The fixture carries:
//!
//! | | |
//! |---|---|
//! | a note with real `/Contents`, `/T` and `/M` | so "it shows the words" has something to show |
//! | that note authored **`/Open true`** | so "the file's state is honoured" has a positive case |
//! | a **second note authored `/Open false`**, also with words | so a build that opens *every* pop-up fails. ★ Without this the check is vacuous in the other direction, which is the shape `RESUME.md` calls out: *"an absence check is vacuous if the run already stands where the defect lands"* |
//! | a `/Popup` with **its own `/Rect`, away from the note** | so a build that always draws "beside the note" is distinguishable from one that honours the file |
//! | a **reply** (`/IRT`, a different author) | so the thread is exercised |
//!
//! The fixture's own properties are asserted by
//! `pdfcer_gui::canvas::notepopup::model::tests::the_fixture_carries_a_real_thread_with_words_an_author_and_a_date`,
//! which runs on every `cargo test`. A fixture regenerated wrong goes red there
//! long before a sweep would notice anything here.
//!
//! # What it does
//!
//! `PDFCER_DIAG_INVOKE=mode.read` at launch, and **nothing else** — no panel,
//! no tool. That is the whole point: the surface under test must be reachable
//! with the Read ribbon, which is `file` and `view` alone.
//!
//! | Phase | Does | Expected |
//! |---|---|---|
//! | A | launch in Read mode on the pinned fixture | `note-popup … open=1 from_file=1`, and `notepopup.window` **published**, i.e. visible inside the canvas |
//! | B | read the census | exactly **one** pop-up open — the file authored one open and one closed |
//! | C | click the **closed** note at `0,110,310` | `note-popup-toggle`, then `open=2` |
//! | D | click it again | `open=1` — a click toggles, which is the class convention and the gesture an operator who opened one by accident tries |
//!
//! # ★★ Phase A is the whole report and phase B is what makes it mean anything
//!
//! `open=1` alone would pass on a build that opens every pop-up it finds.
//! `from_file=1` is the field that says the pop-up is open **because the
//! document said so** rather than because anything was clicked — and it is the
//! only oracle for that available from outside the process, because a pop-up
//! opened by `/Open` and one opened by a click are pixel-identical.
//!
//! # ⬜ What this check does NOT assert, named rather than implied
//!
//! **That the application actually entered Read mode.** `PDFCER_DIAG_INVOKE`
//! *asks* for `mode.read`, and nothing here confirms it arrived. If a future
//! change made that command silently fail, the pop-up would open for a reason
//! this check is not testing and the operator's actual complaint would go
//! unmeasured with a green result.
//!
//! It is left out deliberately rather than forgotten: the mode's own trace
//! vocabulary is a concurrent track's to settle this week, and pinning a field
//! name that is about to move would be a check that goes red for a reason that
//! is not a defect. **The day the mode publishes a stable line, add the
//! assertion here** — it is one `trace.last(...)` and it closes the last hole
//! in this check.
//!
//! It also does not assert what the pop-up **says**. `note-popup` carries
//! counts, not text; the words, the byline and the date are unit-tested
//! against the same fixture in
//! `pdfcer_gui::canvas::notepopup::model::tests`, and a driven assertion about
//! them would need a screenshot and an OCR pass. Named so nobody reads a green
//! result here as *"the operator can read the note"* — it says *"a window
//! opened, visibly, where and when it should."*

use crate::checks::driving::{SHELL_DIAG_ENV, declared, declared_names, list};
use crate::checks::text_selection::aim;
use crate::checks::{Check, CheckContext};
use crate::coords::{DocPoint, PageGeometry};
use crate::error::{Error, Result};
use crate::input::Driver;
use crate::launch::{LaunchSpec, Session};
use crate::report::CheckReport;

/// Read mode, and nothing else. See the module header.
const INVOKE: &str = "mode.read";
/// The per-frame line the pop-up surface writes when it has anything to say.
const CENSUS: &str = "note-popup";
/// The line `canvas::clicking` writes when a click toggles a pop-up.
const TOGGLE: &str = "note-popup-toggle";
/// The region an open pop-up publishes — **only when it is visible**. See the
/// module header on why that distinction is the whole check.
const POPUP_REGION: &str = "notepopup.window";
/// The page's own region, so a failure can say whether a sheet was drawn.
const PAGE_REGION: &str = "page";
/// The fixture, pinned. `--pdf` is ignored and the report says so.
const FIXTURE: &str = "fixtures/comment-note.pdf";
/// The **closed** note's centre, in PDF user space. Its `/Rect` is
/// `[100 300 120 320]`; see the generator's docstring.
const CLOSED_NOTE: (f64, f64) = (110.0, 310.0);

/// The repository's own copy of the fixture, located from **this crate**
/// rather than from the working directory or from `--source-root`.
///
/// `tools/ui-verify/` → up two → the workspace root. The same resolution
/// `crate::checks::ocr::default_fixture` uses, and for the reason recorded
/// there at length: `--source-root` defaults to `crates`, so a fixture
/// resolved through it lands at `crates/fixtures/…` and the check SKIPs; and a
/// bare relative path depends on where the harness was invoked from, which on
/// one occasion had a planted build overwrite the repository's real fixture.
fn fixture() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join(FIXTURE)
}

/// See the module documentation.
pub struct ACommentCanBeReadOnThePageInReadMode;

impl Check for ACommentCanBeReadOnThePageInReadMode {
    fn name(&self) -> &'static str {
        "a_comment_can_be_read_on_the_page_in_read_mode"
    }

    fn defect(&self) -> &'static str {
        "a sticky note can be placed and never read: nothing on the canvas shows an annotation's \
         /Contents, and the only surface that does is a panel on a tab Read mode is not shown — \
         so pdfcer's reading mode cannot read the comments, which is the posture of a PDF reader \
         exactly backwards"
    }

    fn run(&self, ctx: &CheckContext) -> CheckReport {
        let mut report = CheckReport::new(self.name(), self.defect());
        match drive(ctx, &mut report) {
            Ok(Some(failure)) => report.fail(failure),
            Ok(None) => report.pass(),
            Err(why) => report.from_error(&why),
        }
    }
}

/// Run the sequence. `Err` is SKIP, `Ok(Some(_))` is FAIL, `Ok(None)` is a pass.
#[allow(clippy::too_many_lines)]
fn drive(ctx: &CheckContext, report: &mut CheckReport) -> Result<Option<String>> {
    if !ctx.allow_input {
        return Err(Error::new(
            "input is disabled (--no-input). This check clicks a note on the page twice. \
             Reported as SKIPPED rather than passed: a check that did not run has learned \
             nothing.",
        ));
    }
    let exe = ctx.resolve_exe().ok_or_else(|| {
        Error::new(format!(
            "no binary to drive. Pass --exe, or build the profile's default at {}.",
            ctx.profile.default_exe
        ))
    })?;

    // ★ The fixture is pinned and any `--pdf` is discarded — and SAID so,
    // because a sweep that silently ignored a flag is indistinguishable from
    // one that honoured it.
    let pdf = fixture();
    if !pdf.exists() {
        return Err(Error::new(format!(
            "{FIXTURE} was not found at {}. Regenerate it with \
             `python tools/gen-comment-note-fixture.py`.",
            pdf.display()
        )));
    }
    if let Some(supplied) = &ctx.pdf
        && supplied != &pdf
    {
        report.note(format!(
            "--pdf {} was IGNORED. This check pins {FIXTURE}, because a document with no \
             comments cannot exercise it and would SKIP for ever while looking healthy.",
            supplied.display()
        ));
    }

    // The fixture is US Letter and its annotation rectangles are absolute, so
    // the geometry is read from the file rather than taken from `--page-size`:
    // a size supplied for a different document would aim these clicks at
    // nothing.
    let page: PageGeometry = crate::fixture::page_geometry(&pdf).ok_or_else(|| {
        Error::new(format!(
            "could not read a page size from {}. The fixture may be corrupt; regenerate it.",
            pdf.display()
        ))
    })?;
    let ui_rect = ctx
        .profile
        .vocab
        .ui_rect_event
        .ok_or_else(|| Error::new("the profile declares no ui-rect trace event."))?;

    let mut spec = LaunchSpec::new(&exe, ctx.out("comment-popup.trace.txt"));
    spec.pdf = Some(pdf.clone());
    spec.env.push((
        ctx.profile.diag_env.0.to_owned(),
        ctx.profile.diag_env.1.to_owned(),
    ));
    spec.env
        .push((SHELL_DIAG_ENV.0.to_owned(), SHELL_DIAG_ENV.1.to_owned()));
    spec.env
        .push(("PDFCER_DIAG_INVOKE".to_owned(), INVOKE.to_owned()));
    spec.allow_stale = ctx.allow_stale;
    spec.source_root = ctx.source_root.clone();

    let session = Session::launch(&spec, ctx.profile.trace_prefix)?;
    report.artifact(session.trace_path().to_path_buf());
    report.note(format!(
        "launched {} as pid {} on {} with PDFCER_DIAG_INVOKE={INVOKE}",
        exe.display(),
        session.pid(),
        pdf.display()
    ));
    session.settle(40);
    let driver = Driver::new(session.window());

    // --- A: the document opened, and the pop-up its file asked for is OPEN ---
    let trace = session.trace()?;
    if declared(&trace, ui_rect, PAGE_REGION).is_none() {
        return Err(Error::new(format!(
            "the application declared no `{PAGE_REGION}` region, so no sheet is on screen and \
             there is nothing to click. Regions beginning `page`: {}.",
            list(&declared_names(&trace, ui_rect, "page"))
        )));
    }

    let Some(first) = trace.last(CENSUS) else {
        return Ok(Some(format!(
            "no `{CENSUS}` line after opening a document carrying three comments, one of them \
             authored `/Open true`. The canvas surfaced nothing at all about the notes on the \
             page — which is the operator's report of 2026-09-05 verbatim: a sticky note can be \
             placed and not read. Trace: {}.",
            session.trace_path().display()
        )));
    };
    report.note(format!("on load: {}", first.raw));

    // ★ Through `TraceLine::get_usize` rather than a hand-rolled split: the
    // parser already handles quoting and the `Some(3)` wrapper, and a second
    // field reader in this file would be a second thing to keep in step with
    // the trace vocabulary.
    let raw = first.raw.clone();
    let Some(open_now) = first.get_usize("open") else {
        return Err(Error::new(format!(
            "the `{CENSUS}` line carries no `open=` field, so this check cannot tell an open \
             pop-up from a closed one. The trace vocabulary changed; fix the check. Line: \
             {raw}"
        )));
    };
    let Some(from_file) = first.get_usize("from_file") else {
        return Err(Error::new(format!(
            "the `{CENSUS}` line carries no `from_file=` field. That field is the ONLY oracle \
             for whether a pop-up is open because the document said `/Open true` rather than \
             because something was clicked, and without it phase A proves nothing. Line: \
             {raw}"
        )));
    };

    if open_now == 0 {
        return Ok(Some(format!(
            "the fixture's note is authored `/Open true` (§12.5.6.4 Table 172, and its `/Popup` \
             repeats it per Table 183) and NO pop-up opened: `{raw}`. The open state is in the \
             file and pdfcer defaulted it instead of reading it — so a document another product \
             authored with its notes open arrives here silently shut."
        )));
    }
    if from_file == 0 {
        return Ok(Some(format!(
            "a pop-up is open but `from_file=0`, so it is open because something was clicked \
             rather than because the file said so. Nothing has been clicked yet. `{raw}`"
        )));
    }
    // ★★★ The negative half, and it is what stops this check passing on a
    // build that simply opens everything. The fixture carries TWO notes with
    // words: one `/Open true` and one `/Open false`.
    if open_now != 1 {
        return Ok(Some(format!(
            "{open_now} pop-ups are open on load and the fixture authored exactly ONE `/Open \
             true` (the other note is `/Open false` and also carries words). A build that opens \
             every pop-up it finds covers the drawing with windows the operator did not ask \
             for. `{raw}`"
        )));
    }

    // …and it is VISIBLE, not merely laid out. `ui_rect_visible` publishes
    // nothing unless the rectangle is visible enough inside the canvas clip it
    // was handed, so the region's presence is the assertion. See the module
    // header, and `REVIEW_TRIAGE.md` T4.
    if declared(&trace, ui_rect, POPUP_REGION).is_none() {
        return Ok(Some(format!(
            "a pop-up is open by the census (`{raw}`) and `{POPUP_REGION}` was never \
             published, so the window laid out somewhere the operator cannot see it — off the \
             canvas edge, behind the docked panels, or clipped away. This is the failure three \
             panels in this project shipped with every gate green. Regions beginning \
             `notepopup`: {}.",
            list(&declared_names(&trace, ui_rect, "notepopup"))
        )));
    }

    // --- C: a click on the CLOSED note opens it ------------------------------
    let at = aim(
        ctx,
        &session,
        page,
        DocPoint::new(0, CLOSED_NOTE.0, CLOSED_NOTE.1),
    )?;
    driver.click_at(at)?;
    session.settle(30);

    let trace = session.trace()?;
    if trace.events(TOGGLE).count() == 0 {
        return Ok(Some(format!(
            "a click at the closed note's own rectangle ({:?} in PDF user space) produced no \
             `{TOGGLE}` line, so the canvas did not recognise a click on a comment. In Read \
             mode this is the ONLY route to a note's words — the Comments panel lives on the \
             Markup tab, which Read is not shown — so the operator has no way to read it. \
             Trace: {}.",
            CLOSED_NOTE,
            session.trace_path().display()
        )));
    }
    let after = trace
        .last(CENSUS)
        .map(|l| l.raw.clone())
        .unwrap_or_default();
    let opened = trace
        .last(CENSUS)
        .and_then(|l| l.get_usize("open"))
        .unwrap_or(0);
    if opened != 2 {
        return Ok(Some(format!(
            "after clicking the closed note, {opened} pop-ups are open and 2 were expected — the \
             one the file authored open, plus the one just clicked. `{after}`"
        )));
    }
    report.note(format!("after the first click: {after}"));

    // --- D: clicking it again CLOSES it --------------------------------------
    //
    // The class convention, and the gesture an operator who opened one by
    // accident tries first. A build that only ever opened would leave every
    // note the reviewer glanced at covering the drawing.
    driver.click_at(at)?;
    session.settle(30);
    let trace = session.trace()?;
    let after = trace
        .last(CENSUS)
        .map(|l| l.raw.clone())
        .unwrap_or_default();
    let closed_again = trace
        .last(CENSUS)
        .and_then(|l| l.get_usize("open"))
        .unwrap_or(0);
    if closed_again != 1 {
        return Ok(Some(format!(
            "clicking the note a second time left {closed_again} pop-ups open and 1 was expected \
             — a click toggles. A window that cannot be dismissed by the gesture that opened it \
             is one an operator has to hunt for a close button to be rid of. `{after}`"
        )));
    }
    report.note(format!("after the second click: {after}"));

    Ok(None)
}
