//! **The three checks about a recognition run while it is still running** —
//! progress, Stop, and Cancel.
//!
//! Design and rationale: `docs/modules/ui-verify/checks/ocr_progress.md`.

use std::path::PathBuf;

use crate::checks::driving::{self, SHELL_DIAG_ENV};
use crate::checks::ocr::{click_command, click_region, click_tab};
use crate::checks::{Check, CheckContext};
use crate::error::{Error, Result};
use crate::input::Driver;
use crate::launch::{LaunchSpec, Session};
use crate::report::CheckReport;
use crate::trace::Trace;

/// The mode the command is driven in. See `checks::ocr`'s [`READ`] for the
/// argument — OCR must be reachable in Read, and once was not.
///
/// [`READ`]: crate::checks::ocr
const READ: &str = "read";

/// The tab the command lives on.
const TAB: &str = "file";

/// The command's id, which is also its declared region's suffix.
const COMMAND: &str = "file.ocr";

/// The multi-page fixture, relative to the workspace root.
///
/// Generated by `crates/pdfcer-gui-base/src/ocr/fixture.rs`:
/// `cargo test -p pdfcer-gui --lib write_synthetic_image_only_multipage -- --ignored`
const FIXTURE: &str = "fixtures/synthetic-image-only-8pages.pdf";

/// How many pages [`FIXTURE`] has.
const FIXTURE_PAGES: usize = 8;

/// Environment override naming a real scanned document to drive instead.
const SCAN_ENV: &str = "PDFCER_VERIFY_SCAN";

/// `ocr-progress attempted=… of=… words=… chars=…` — the live tally's content.
const PROGRESS_EVENT: &str = "ocr-progress";

/// `ocr-recognised pages=… skipped=… recognised=… dpi=…`
const RECOGNISED_EVENT: &str = "ocr-recognised";

/// `ocr-refused reason=…`
const REFUSED_EVENT: &str = "ocr-refused";

/// `ocr-cancelled attempted=…` — the operator threw the run away.
const CANCELLED_EVENT: &str = "ocr-cancelled";

/// `ocr-applied written=… skipped=… words=…` — the dialog raised the edit.
const APPLIED_EVENT: &str = "ocr-applied";

/// `ocr-layer page=… n=… …` — `vector_edit`'s record that the session took it.
const EDIT_EVENT: &str = "ocr-layer";

/// The progress region, so the check can assert the operator can SEE it.
const PROGRESS_REGION: &str = "ocr-progress";

/// The control that finishes the page in hand and keeps everything.
const STOP_REGION: &str = "ocr-stop";

/// The control that abandons the run.
const CANCEL_REGION: &str = "ocr-cancel";

/// How long a whole eight-page run may take, in settle frames.
const RUN_FRAMES: u32 = 1_600;

/// How long to wait for the FIRST progress line before giving up.
const FIRST_PAGE_FRAMES: u32 = 480;

/// The polling granularity. Eight frames is 200 ms.
const SLICE: u32 = 8;

/// The workspace root, from this crate's manifest directory.
fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
}

/// The document to drive: `PDFCER_VERIFY_SCAN` if it names a real file, else the
/// committed multi-page fixture.
fn document() -> (PathBuf, bool) {
    if let Some(from_env) = std::env::var_os(SCAN_ENV) {
        let path = PathBuf::from(from_env);
        if path.is_file() {
            return (path, true);
        }
    }
    (workspace_root().join(FIXTURE), false)
}

/// Poll the trace until `pred` holds, or `budget` frames are spent.
fn wait_until(
    session: &Session,
    budget: u32,
    mut pred: impl FnMut(&Trace) -> bool,
) -> Result<bool> {
    let mut spent = 0;
    loop {
        if pred(&session.trace()?) {
            return Ok(true);
        }
        if spent >= budget {
            return Ok(false);
        }
        session.settle(SLICE);
        spent += SLICE;
    }
}

/// Every `attempted=` value the trace has reported, in order.
fn attempts(trace: &Trace) -> Vec<usize> {
    trace
        .events(PROGRESS_EVENT)
        .filter_map(|l| l.get_usize("attempted"))
        .collect()
}

/// The run's shared preamble: launch, reach `file.ocr` in Read, press
/// Recognise.
fn start_a_run(
    ctx: &CheckContext,
    report: &mut CheckReport,
    trace_name: &str,
) -> Result<(Session, Driver, bool)> {
    let exe = ctx.resolve_exe().ok_or_else(|| {
        Error::new(format!(
            "no binary to drive. Pass --exe, or build the profile's default at {}.",
            ctx.profile.default_exe
        ))
    })?;
    if !ctx.allow_input {
        return Err(Error::new(
            "input is disabled (--no-input). This check clicks a ribbon control and dialog \
             buttons. Reported as SKIPPED rather than passed: a check that did not run has \
             learned nothing.",
        ));
    }
    let ui_rect = ctx.profile.vocab.ui_rect_event.ok_or_else(|| {
        Error::new(format!(
            "the `{}` profile declares no ui-rect trace event, so the application cannot state \
             where its controls are and this check has nothing to aim at.",
            ctx.profile.name
        ))
    })?;

    let (doc, real) = document();
    if !doc.is_file() {
        return Err(Error::new(format!(
            "the multi-page image-only fixture is not at {}. Generate it:\n  cargo test -p \
             pdfcer-gui --lib write_synthetic_image_only_multipage -- --ignored\nOr set \
             {SCAN_ENV} to a scanned, text-free, multi-page PDF.",
            doc.display()
        )));
    }
    report.note(format!(
        "driving {} — {}",
        doc.display(),
        if real {
            "REAL SCANNED MATERIAL, named by $PDFCER_VERIFY_SCAN. Recognition quality is \
             exercised here, not only the plumbing"
        } else {
            "the committed synthetic fixture. ★ It is a RENDERED page, not a scan: no scanner \
             noise, no skew, no JPEG ringing. This establishes the plumbing of a multi-page run \
             and establishes NOTHING about recognition quality. Set $PDFCER_VERIFY_SCAN to a \
             real scan to exercise that"
        }
    ));

    let mut spec = LaunchSpec::new(&exe, ctx.out(trace_name));
    spec.pdf = Some(doc);
    spec.env.push((
        ctx.profile.diag_env.0.to_owned(),
        ctx.profile.diag_env.1.to_owned(),
    ));
    spec.env
        .push((SHELL_DIAG_ENV.0.to_owned(), SHELL_DIAG_ENV.1.to_owned()));
    spec.allow_stale = ctx.allow_stale;
    spec.source_root = ctx.source_root.clone();

    let session = Session::launch(&spec, ctx.profile.trace_prefix)?;
    report.note(format!(
        "launched {} as pid {}",
        exe.display(),
        session.pid()
    ));
    report.artifact(session.trace_path().to_path_buf());
    session.settle(40);
    // **MAXIMIZE, and this line is a repair.**
    //
    // Found on 2026-09-01 by writing `checks::ocr_progress` and watching it
    // SKIP for a reason that turned out to apply to THIS check too: at the
    // window's default width the `file` tab's **Recognise group collapses**,
    // and a collapsed group declares `ribbon.group.file.recognise.collapsed`
    // instead of `ribbon.item.file.ocr`. The harness then reports *"the
    // application declared no `ribbon.item.file.ocr` region"* — which reads as
    // the command having been removed, and is in fact the ribbon doing exactly
    // what a ribbon is for.
    //
    // This check had therefore been reporting **SKIP** rather than PASS, and
    // a SKIP is not a failure, so nothing was red and nothing prompted a look.
    // `Session::maximize`'s own doc comment describes this precise symptom —
    // *"would have been handed ten controls ending at `file.print`, and would
    // have reported a shipped feature as missing"* — so the lesson was already
    // written down and this call site simply never got it.
    //
    // Opt-in per check by design, because a maximised window is a different
    // layout and several checks measure the layout. Nothing here does: this
    // check's subject is a command, a dialog and a file on disk.
    session.maximize();
    session.settle(12);

    if !session.trace()?.started(ctx.profile.vocab.start_event) {
        return Err(Error::new(format!(
            "the trace has no `{}` line, so the diagnostic switch did not reach the process and \
             this check has no oracle. Captured stderr is at {}.",
            ctx.profile.vocab.start_event,
            session.trace_path().display()
        )));
    }
    let driver = Driver::new(session.window());

    driving::click_mode_segment(&session, &driver, ui_rect, READ)?;
    click_tab(&session, &driver, ui_rect, TAB)?;
    click_command(&session, &driver, ui_rect, COMMAND)?;
    session.settle(16);

    let trace = session.trace()?;
    if driving::declared(&trace, ui_rect, "ocr-dialog").is_none() {
        return Err(Error::new(format!(
            "`{COMMAND}` opened no dialog, so there is no run to observe. That is \
             `checks::ocr`'s subject and it reports it as a FAILURE; here it is a SKIP, because \
             a check about a run in progress that never got a run has measured nothing. Trace: \
             {}.",
            session.trace_path().display()
        )));
    }
    let pages = trace
        .last("ocr-scope")
        .and_then(|l| l.get_usize("pages"))
        .unwrap_or(0);
    if pages < 2 {
        return Err(Error::new(format!(
            "the dialog resolved a scope of {pages} page(s). These checks are about a run with \
             a MIDDLE; a one-page run is started and then over, and Stop, Cancel and an \
             advancing tally are all unobservable across it. Either the fixture is not the \
             multi-page one or the default scope is no longer All pages."
        )));
    }
    report.note(format!("the dialog resolved a scope of {pages} page(s)"));
    if !real && pages != FIXTURE_PAGES {
        return Err(Error::new(format!(
            "the committed fixture resolved {pages} pages and it is built with \
             {FIXTURE_PAGES}. The file on disk is not the one the generator produces — \
             regenerate it, or a denominator these checks quote is a lie."
        )));
    }

    if driving::declared(&trace, ui_rect, "ocr-run").is_none() {
        return Err(Error::new(format!(
            "the dialog drew no `ocr-run` control, so it is refusing rather than offering to \
             recognise. The overwhelmingly likely cause is that the `models/ocrs` folder is not \
             beside {} — these checks need a PACKAGED build, or the weights copied next to the \
             executable.",
            exe.display()
        )));
    }
    click_region(&session, &driver, ui_rect, "ocr-run")?;
    Ok((session, driver, real))
}

/// A refusal, if the trace carries one. Every check treats it the same way:
/// a named refusal after a drawn Run button is a FAILURE, not a skip.
fn refusal(session: &Session) -> Result<Option<String>> {
    Ok(session.trace()?.last(REFUSED_EVENT).map(|l| l.raw.clone()))
}

// ---------------------------------------------------------------------------
// 1 — the tally advances
// ---------------------------------------------------------------------------

/// **The operator can watch the run move.**
pub struct OcrSaysHowFarItHasGot;

impl Check for OcrSaysHowFarItHasGot {
    fn name(&self) -> &'static str {
        "ocr_says_how_far_it_has_got_while_it_runs"
    }

    fn defect(&self) -> &'static str {
        "A multi-page recognition gives the operator no sign it is progressing — no tally, or a \
         tally that is drawn once and then never redrawn, which is pixel-identical to the \
         frozen application the feature exists to rule out"
    }

    fn run(&self, ctx: &CheckContext) -> CheckReport {
        let mut report = CheckReport::new(self.name(), self.defect());
        match drive_progress(ctx, &mut report) {
            Ok(Some(failure)) => report.fail(failure),
            Ok(None) => report.pass(),
            Err(why) => report.from_error(&why),
        }
    }
}

#[allow(clippy::too_many_lines)]
fn drive_progress(ctx: &CheckContext, report: &mut CheckReport) -> Result<Option<String>> {
    let ui_rect = ctx
        .profile
        .vocab
        .ui_rect_event
        .ok_or_else(|| Error::new("no ui-rect event in this profile"))?;
    let (session, _driver, real) = start_a_run(ctx, report, "ocr-progress.trace.txt")?;

    // Wait for the first page to finish. Until one has, the label is
    // deliberately not drawn: `Page 0 of 8 — 0 words` beside a spinner says
    // less than the spinner alone while looking like a stall.
    let saw_first = wait_until(&session, FIRST_PAGE_FRAMES, |t| {
        !attempts(t).is_empty() || t.last(REFUSED_EVENT).is_some()
    })?;
    if let Some(why) = refusal(&session)? {
        return Ok(Some(format!(
            "RECOGNITION REFUSED: `{why}`. The Run button was drawn — so preflight passed and \
             this build has both an engine and models — and the job then came back with a named \
             refusal, so there was never a run to report progress about."
        )));
    }
    if !saw_first {
        return Ok(Some(format!(
            "★ NO PROGRESS WAS EVER REPORTED. The run started and {FIRST_PAGE_FRAMES} frames \
             (about {} seconds) passed with no `{PROGRESS_EVENT}` line at all — not one page \
             finished, or a page finished and the dialog did not draw the tally.\n\n\
             This is the operator's own complaint, reproduced: *\"the user can see that it is \
             doing something and hasn't frozen\"*. Look at `dialogs::ocr`'s `Phase::Working` \
             arm and at `Job::tally`. Trace: {}.",
            u64::from(FIRST_PAGE_FRAMES) * 25 / 1000,
            session.trace_path().display()
        )));
    }

    // The label must be ON SCREEN, not merely traced. A trace line proves the
    // shell computed a tally; the declared rect proves it drew one. The
    // request is about what the operator can SEE, so both are asserted — this
    // codebase has shipped a panel that existed and was unreachable, with every
    // gate green, and `D:/dev/rag/egui/` carries the finding.
    let trace = session.trace()?;
    let Some(rect) = driving::declared(&trace, ui_rect, PROGRESS_REGION) else {
        return Ok(Some(format!(
            "★ THE TALLY WAS COMPUTED AND NEVER DRAWN. `{PROGRESS_EVENT}` lines are in the \
             trace — so the shell knows how far it has got — and no `{PROGRESS_REGION}` region \
             was ever declared, which means no label reached the screen. Regions the dialog did \
             declare: {}.",
            driving::list(&driving::declared_names(&trace, ui_rect, "ocr-"))
        )));
    };
    if !rect.is_substantial() {
        return Ok(Some(format!(
            "the progress label was declared at {rect:?}, which has no usable area — it is on \
             screen in the sense that a zero-height label is on screen."
        )));
    }
    report.note(format!("the progress label is drawn at {rect:?}"));

    // Now let the run finish, and read the whole series.
    let finished = wait_until(&session, RUN_FRAMES, |t| {
        t.last(RECOGNISED_EVENT).is_some() || t.last(REFUSED_EVENT).is_some()
    })?;
    let trace = session.trace()?;
    if let Some(why) = refusal(&session)? {
        return Ok(Some(format!("RECOGNITION REFUSED MID-RUN: `{why}`.")));
    }
    if !finished {
        return Ok(Some(format!(
            "RECOGNITION NEVER FINISHED within {RUN_FRAMES} frames (about {} seconds). The last \
             tally reported was {:?}. A job that neither answers nor refuses leaves the dialog \
             saying `Recognising…` forever. Trace: {}.",
            u64::from(RUN_FRAMES) * 25 / 1000,
            attempts(&trace).last(),
            session.trace_path().display()
        )));
    }

    // THE ASSERTION THIS CHECK IS FOR.
    //
    // Two distinct values, rising. One value is a label that was drawn and
    // never changed, which is the frozen-looking application. `dedup` on an
    // already-ordered series rather than a set, so the count is of *changes*.
    let series = attempts(&trace);
    let mut distinct = series.clone();
    distinct.dedup();
    if distinct.len() < 2 {
        return Ok(Some(format!(
            "★★★ THE TALLY NEVER MOVED. The whole run reported the single value {distinct:?}. \
             A progress line that is drawn once and never updated is not progress — it is a \
             still frame, and it is exactly what an operator reads as a frozen program.\n\n\
             The likeliest cause is that nothing requested the next frame. egui is \
             immediate-mode and idle; the OCR worker is on another thread and generates no \
             input events, so unless `dialogs::ocr`'s `Phase::Working` arm calls \
             `ctx.request_repaint()` the window holds whatever frame it drew when the run \
             started. It also worked, for a while, purely because `egui::Spinner` requests a \
             repaint for its own animation — so check whether the spinner is still there. \
             Trace: {}.",
            session.trace_path().display()
        )));
    }
    if distinct.windows(2).any(|w| w[1] <= w[0]) {
        return Ok(Some(format!(
            "THE TALLY WENT BACKWARDS OR REPEATED A VALUE AFTER CHANGING: {distinct:?}. \
             `attempted` is a running count of pages finished and must be monotonically \
             increasing."
        )));
    }
    report.note(format!(
        "★ the tally advanced through {} distinct values: {distinct:?}",
        distinct.len()
    ));

    // **The tally must reach the last page but ONE, and not the last one.**
    //
    // The strict `last == scope` was written first and it FAILED,
    // deterministically, at 7 of 8 — which is the correct behaviour, so the
    // assertion was the thing that was wrong. The reason is worth writing down
    // because it is not obvious and it will otherwise be rediscovered:
    //
    // `Job::poll` **drains** the channel — deliberately, so that several pages
    // finishing during one slow frame do not make the label lag the work by
    // exactly as long as the work takes. On the frame the run ends, that single
    // drain reads `Page(8)` *and* `Finished`, and returns the outcome.
    // `dialogs::ocr` leaves `Phase::Working` immediately, so the body never
    // draws a `Working` frame carrying `attempted = 8`. What the operator sees
    // is `Page 7 of 8` and then the outcome, which states the true totals
    // including page 8.
    //
    // That is right, and it is what a progress display is supposed to do: be
    // superseded by its result rather than flash 100% on the way past. So this
    // is a **band**, not a widened tolerance — and it is still strong, because
    // what it is aimed at is a tally that goes quiet partway (2 of 8, 3 of 8),
    // which is symptom-identical to a freeze and is the whole subject here.
    let scope = trace
        .last("ocr-scope")
        .and_then(|l| l.get_usize("pages"))
        .unwrap_or(0);
    let last = distinct.last().copied().unwrap_or(0);
    let floor = scope.saturating_sub(1);
    if last < floor {
        return Ok(Some(format!(
            "THE TALLY STOPPED SHORT. The scope was {scope} page(s) and the last progress \r
             line reported {last} attempted, where at least {floor} was expected. \r
             Either pages were dropped from the run without being counted, or the \r
             tally stopped being published partway — a progress line that goes quiet \r
             before the end is the same failure as one that never starts, arriving \r
             later.

\r
             ★ {floor} rather than {scope} is not slack. The frame on which the last \r
             page finishes is the frame the run ends on, and `dialogs::ocr` leaves \r
             `Phase::Working` before drawing it — see this check's source for the \r
             drain that makes that deterministic rather than a race."
        )));
    }
    if last > scope {
        return Ok(Some(format!(
            "THE TALLY OVERRAN ITS OWN DENOMINATOR: {last} attempted of a scope of {scope}. \r
             A page was counted twice, which means `Job::poll` is accumulating \r
             `attempted` rather than assigning it."
        )));
    }
    report.note(format!(
        "and it got as far as {last} of {scope} — the last page's frame is the frame the \r
         run ends on, so the outcome supersedes the tally rather than the tally \r
         briefly reading {scope} of {scope}"
    ));

    // And it must have said what it FOUND, not only how far it had got — the
    // operator asked for "words/characters detected" by name.
    let last_line = trace
        .events(PROGRESS_EVENT)
        .last()
        .ok_or_else(|| Error::new("the progress series vanished between two reads"))?;
    let words = last_line.get_usize("words").unwrap_or(0);
    let chars = last_line.get_usize("chars").unwrap_or(0);
    if words == 0 || chars == 0 {
        return Ok(Some(format!(
            "THE TALLY COUNTED PAGES AND NOT CONTENT: `{}`. The request names \
             *\"words/characters detected\"* explicitly, and a page count alone does not \
             distinguish a recogniser that is reading from one that is walking pages and \
             finding nothing on any of them.",
            last_line.raw
        )));
    }
    report.note(format!(
        "and it reported what it found as it went: `{}`",
        last_line.raw
    ));
    if !real {
        report.note(
            "NOT established: recognition quality. The fixture is a rendered page. What is \
             established is that a multi-page run tells the operator where it has got to, in \
             numbers that move, on a window that keeps redrawing itself",
        );
    }
    Ok(None)
}

// ---------------------------------------------------------------------------
// 2 — Stop keeps the work
// ---------------------------------------------------------------------------

/// **Stop finishes the page in hand and keeps every page before it.**
pub struct StoppingOcrKeepsWhatItHasDone;

impl Check for StoppingOcrKeepsWhatItHasDone {
    fn name(&self) -> &'static str {
        "stopping_ocr_keeps_the_pages_it_had_already_done"
    }

    fn defect(&self) -> &'static str {
        "Stop throws away the recognition it was asked to keep, or does not stop at all — the \
         operator waits out a run they had ended, or loses the pages they had explicitly asked \
         for"
    }

    fn run(&self, ctx: &CheckContext) -> CheckReport {
        let mut report = CheckReport::new(self.name(), self.defect());
        match drive_ending(ctx, &mut report, Ending::Stop) {
            Ok(Some(failure)) => report.fail(failure),
            Ok(None) => report.pass(),
            Err(why) => report.from_error(&why),
        }
    }
}

// ---------------------------------------------------------------------------
// 3 — Cancel throws it away
// ---------------------------------------------------------------------------

/// **Cancel discards the run and touches the document not at all.**
pub struct CancellingOcrThrowsAwayWhatItHadDone;

impl Check for CancellingOcrThrowsAwayWhatItHadDone {
    fn name(&self) -> &'static str {
        "cancelling_ocr_throws_away_what_it_had_done"
    }

    fn defect(&self) -> &'static str {
        "Cancel keeps the partial recognition — the operator asked for none of it and gets a \
         half-recognised document, with a layer over some pages and not others and nothing to \
         say which"
    }

    fn run(&self, ctx: &CheckContext) -> CheckReport {
        let mut report = CheckReport::new(self.name(), self.defect());
        match drive_ending(ctx, &mut report, Ending::Cancel) {
            Ok(Some(failure)) => report.fail(failure),
            Ok(None) => report.pass(),
            Err(why) => report.from_error(&why),
        }
    }
}

/// Which of the two early endings is being driven.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Ending {
    /// Finish the page in hand, keep everything.
    Stop,
    /// Abandon the run, keep nothing.
    Cancel,
}

impl Ending {
    /// The region to click.
    fn region(self) -> &'static str {
        match self {
            Self::Stop => STOP_REGION,
            Self::Cancel => CANCEL_REGION,
        }
    }

    /// The operator's own word for it, for the report.
    fn word(self) -> &'static str {
        match self {
            Self::Stop => "Stop",
            Self::Cancel => "Cancel",
        }
    }
}

#[allow(clippy::too_many_lines)]
fn drive_ending(
    ctx: &CheckContext,
    report: &mut CheckReport,
    ending: Ending,
) -> Result<Option<String>> {
    let ui_rect = ctx
        .profile
        .vocab
        .ui_rect_event
        .ok_or_else(|| Error::new("no ui-rect event in this profile"))?;
    let trace_name = match ending {
        Ending::Stop => "ocr-stop.trace.txt",
        Ending::Cancel => "ocr-cancel.trace.txt",
    };
    let (session, driver, real) = start_a_run(ctx, report, trace_name)?;

    // **Wait for a page to finish before pressing anything, and that is
    // not politeness — it is what makes the result mean something.**
    //
    // Pressing Stop before any page has completed makes "Stop keeps the work"
    // vacuous: there is no work. Pressing Cancel then makes "Cancel discards
    // the work" equally vacuous. Both would pass against a build in which the
    // two buttons were the same button, which is the exact confusion this pair
    // exists to rule out. So the harness waits for `attempted >= 1` and only
    // then reaches for the control.
    let ready = wait_until(&session, FIRST_PAGE_FRAMES, |t| {
        attempts(t).iter().any(|n| *n >= 1)
            || t.last(REFUSED_EVENT).is_some()
            || t.last(RECOGNISED_EVENT).is_some()
    })?;
    if let Some(why) = refusal(&session)? {
        return Ok(Some(format!(
            "RECOGNITION REFUSED: `{why}` — there was never a run to {}.",
            ending.word()
        )));
    }
    if !ready {
        return Ok(Some(format!(
            "NO PAGE FINISHED in {FIRST_PAGE_FRAMES} frames, so `{}` had nothing to act on. \
             That is `{}`'s subject; here it means this check could not be set up. Trace: {}.",
            ending.word(),
            OcrSaysHowFarItHasGot.name(),
            session.trace_path().display()
        )));
    }

    // The run may have finished already on a fast machine and a short
    // document. That is a SKIP, and it is a real one: you cannot interrupt
    // something that is over, and calling it a pass would be this harness's own
    // worst outcome — a green result that measured nothing.
    let trace = session.trace()?;
    if trace.last(RECOGNISED_EVENT).is_some() {
        return Err(Error::new(format!(
            "the whole run finished before the harness could press {}. Nothing was \
             interrupted, so nothing about interrupting was measured. Drive a longer document \
             — set {SCAN_ENV} to a scanned PDF with more pages — or accept that this machine \
             recognises {} pages faster than this harness can react.",
            ending.word(),
            trace
                .last("ocr-scope")
                .and_then(|l| l.get_usize("pages"))
                .unwrap_or(0),
        )));
    }
    let before = attempts(&trace).last().copied().unwrap_or(0);
    let scope = trace
        .last("ocr-scope")
        .and_then(|l| l.get_usize("pages"))
        .unwrap_or(0);
    report.note(format!(
        "pressing {} with {before} of {scope} page(s) attempted",
        ending.word()
    ));

    if driving::declared(&trace, ui_rect, ending.region()).is_none() {
        return Ok(Some(format!(
            "★ THERE IS NO {} BUTTON WHILE THE RUN IS GOING. No `{}` region was declared on any \
             frame of a run that has been going for at least one page. The operator asked for \
             both controls by name and a run with no way out is the thing they were asking to \
             be rid of. Regions the dialog did declare: {}.",
            ending.word().to_uppercase(),
            ending.region(),
            driving::list(&driving::declared_names(&trace, ui_rect, "ocr-"))
        )));
    }
    click_region(&session, &driver, ui_rect, ending.region())?;

    // The stop flag is read between pages, so the wait is bounded by one page
    // plus the poll — generous margin, same reasoning as everywhere else here.
    let ended = wait_until(&session, FIRST_PAGE_FRAMES + SLICE * 8, |t| {
        t.last(RECOGNISED_EVENT).is_some()
            || t.last(CANCELLED_EVENT).is_some()
            || t.last(REFUSED_EVENT).is_some()
    })?;
    let trace = session.trace()?;
    if !ended {
        return Ok(Some(format!(
            "★ {} DID NOTHING. The button was clicked and the run neither ended nor \
             acknowledged it within {} seconds — more than one page's worth. The flag is read \
             between pages (`ocr::progress`), so a press that is never observed means the \
             worker is not reading it or the button is not setting it. Last tally: {:?}. \
             Trace: {}.",
            ending.word().to_uppercase(),
            u64::from(FIRST_PAGE_FRAMES + SLICE * 8) * 25 / 1000,
            attempts(&trace).last(),
            session.trace_path().display()
        )));
    }

    match ending {
        // ---------------------------------------------------------------
        Ending::Stop => {
            let Some(recognised) = trace.last(RECOGNISED_EVENT) else {
                return Ok(Some(format!(
                    "★★★ STOP THREW THE WORK AWAY. The run ended after the press and the \
                     trace carries {} rather than `{RECOGNISED_EVENT}`.\n\n\
                     These are not two names for one act. An operator who presses Stop on \
                     page 40 of 200 has ASKED FOR those forty pages; one who presses Cancel \
                     has asked for none of them. Collapsing Stop into Cancel discards work \
                     that was explicitly kept. Trace: {}.",
                    if trace.last(CANCELLED_EVENT).is_some() {
                        "`ocr-cancelled` — the CANCEL path"
                    } else {
                        "neither ending"
                    },
                    session.trace_path().display()
                )));
            };
            let kept = recognised.get_usize("pages").unwrap_or(0);
            if kept == 0 {
                return Ok(Some(format!(
                    "STOP KEPT NOTHING: `{}`. At least {before} page(s) had been attempted \
                     when the button was pressed, and none of them survived.",
                    recognised.raw
                )));
            }
            if kept >= scope {
                return Ok(Some(format!(
                    "★ STOP DID NOT STOP. `{}` reports {kept} page(s) written out of a scope \
                     of {scope}, so the run went to completion after the press. The result is \
                     correct and the control is inert — which the operator discovers by \
                     waiting out the twenty minutes they had just cancelled.",
                    recognised.raw
                )));
            }
            report.note(format!(
                "★ the run ended early and kept what it had: `{}` — {kept} of {scope} pages",
                recognised.raw
            ));

            // And the kept pages reached the SESSION. `ocr-applied` is the
            // dialog saying it asked; `ocr-layer` is `vector_edit` saying it
            // happened. Only the pair distinguishes "kept" from "said kept".
            if trace.last(APPLIED_EVENT).is_none() {
                return Ok(Some(format!(
                    "THE STOPPED RUN'S PAGES WERE NEVER APPLIED. `{}` reports {kept} page(s) \
                     and no `{APPLIED_EVENT}` line followed, so the dialog never raised the \
                     edit. Trace: {}.",
                    recognised.raw,
                    session.trace_path().display()
                )));
            }
            let Some(edit) = trace.last(EDIT_EVENT) else {
                return Ok(Some(format!(
                    "★ THE STOPPED RUN'S EDIT NEVER REACHED THE SESSION. `{APPLIED_EVENT}` \
                     was traced and no `{EDIT_EVENT}` followed. The operator's version of this \
                     state is a dialog reporting {kept} recognised pages over a document with \
                     no text in it. Trace: {}.",
                    session.trace_path().display()
                )));
            };
            report.note(format!("and the session took them: `{}`", edit.raw));
        }
        // ---------------------------------------------------------------
        Ending::Cancel => {
            let Some(cancelled) = trace.last(CANCELLED_EVENT) else {
                return Ok(Some(format!(
                    "★★★ CANCEL KEPT THE WORK. The run ended after the press and the trace \
                     carries {} rather than `{CANCELLED_EVENT}`.\n\n\
                     Cancel means the document is untouched. A build that applies the pages \
                     done so far leaves a half-recognised document — a layer over some pages \
                     and not others, invisible by design (Table 106 mode 3), with nothing on \
                     screen to say which. Trace: {}.",
                    if trace.last(RECOGNISED_EVENT).is_some() {
                        "`ocr-recognised` — the STOP path"
                    } else {
                        "neither ending"
                    },
                    session.trace_path().display()
                )));
            };
            report.note(format!("the run was abandoned: `{}`", cancelled.raw));

            // The falsifying assertion, and it is an ABSENCE over the whole
            // trace. See the type's doc comment.
            let applied = trace.events(APPLIED_EVENT).count();
            let edits = trace.events(EDIT_EVENT).count();
            if applied > 0 || edits > 0 {
                return Ok(Some(format!(
                    "★★★ CANCEL APPLIED A LAYER ANYWAY. The trace carries {applied} \
                     `{APPLIED_EVENT}` line(s) and {edits} `{EDIT_EVENT}` line(s) across a run \
                     the operator abandoned. `Cancel` must touch the document not at all — not \
                     apply-then-undo, which leaves an entry in their undo stack and a document \
                     that was momentarily something they did not ask for. Trace: {}.",
                    session.trace_path().display()
                )));
            }
            report.note(
                "★ and nothing was applied — no `ocr-applied` and no `ocr-layer` anywhere in \
                 the run. The document is exactly as it was opened",
            );
        }
    }

    if !real {
        report.note(
            "driven on the synthetic fixture. The ENDING is what is established here and it is \
             document-independent; recognition quality is not, and is not claimed",
        );
    }
    Ok(None)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The fixture these drive is the multi-page image-only one.
    #[test]
    fn the_fixture_is_multi_page_and_image_only() {
        assert!(
            FIXTURE.contains("image-only"),
            "{FIXTURE} must have no text"
        );
        assert!(
            FIXTURE.contains("8pages"),
            "{FIXTURE} must be the multi-page one — a one-page run has no middle to observe"
        );
        const { assert!(FIXTURE_PAGES > 1) };
    }

    /// Every trace event read here is spelled once and is an OCR event.
    #[test]
    fn the_event_names_are_distinct_and_all_ocr() {
        let all = [
            PROGRESS_EVENT,
            RECOGNISED_EVENT,
            REFUSED_EVENT,
            CANCELLED_EVENT,
            APPLIED_EVENT,
            EDIT_EVENT,
        ];
        for (i, a) in all.iter().enumerate() {
            assert!(a.starts_with("ocr-"), "{a} is not an OCR event");
            for b in &all[i + 1..] {
                assert_ne!(a, b, "two constants name the same event");
            }
        }
    }

    /// **Stop and Cancel click different controls.**
    #[test]
    fn the_two_endings_reach_two_different_controls() {
        assert_ne!(Ending::Stop.region(), Ending::Cancel.region());
        assert_ne!(Ending::Stop.word(), Ending::Cancel.word());
        assert_eq!(Ending::Stop.region(), STOP_REGION);
        assert_eq!(Ending::Cancel.region(), CANCEL_REGION);
    }

    /// The budgets are ordered: a whole run may take longer than one page.
    ///
    /// An inversion here would make the run budget expire before the first-page
    /// budget and report "recognition never finished" on every run.
    #[test]
    fn the_waiting_budgets_are_ordered() {
        const {
            assert!(
                RUN_FRAMES > FIRST_PAGE_FRAMES,
                "a whole run must be allowed more time than its first page"
            );
        };
        const { assert!(SLICE > 0 && SLICE < FIRST_PAGE_FRAMES) };
    }

    /// With no override, the document is the committed fixture.
    #[test]
    fn the_default_document_is_the_committed_fixture() {
        assert_eq!(SCAN_ENV, "PDFCER_VERIFY_SCAN");
        if std::env::var_os(SCAN_ENV).is_none() {
            let (path, real) = document();
            assert!(!real);
            assert!(path.ends_with(FIXTURE.rsplit('/').next().unwrap()));
        }
    }
}
