//! # icons::catalog::mapping — every [`Icon`] resolved to its asset and its key
//!
//!
//! ## Why the split fell here and not somewhere else
//!
//! Because the seam is total-ness. [`Icon::ALL`], [`Icon::source`] and
//! [`Icon::name`] are each required to cover every variant, and each one fails
//! LOUDLY when it does not: `source` and `name` are exhaustive `match`es the
//! compiler checks, and `ALL` is checked by `all_is_exhaustive_and_free_of_duplicates`
//! because a missing entry there is the one omission the compiler cannot see.
//! Keeping the three together means the three lists a new variant must join are
//! adjacent, which is the property that stops one of them being forgotten.
//!
//! The doc comments — the rulings about what a glyph may not look like — stay
//! with the enum, because that is where somebody choosing a glyph reads.
//!
//! Design and rationale: `docs/modules/pdfcer-gui-base/icons/catalog/mapping.md`.

use super::super::assets;
use super::Icon;

impl Icon {
    /// Every icon, in catalogue order.
    pub const ALL: &'static [Icon] = &[
        Icon::Open,
        Icon::Save,
        Icon::Sidebar,
        Icon::Comment,
        Icon::ChevronLeft,
        Icon::Back,
        Icon::ChevronRight,
        Icon::ChevronDown,
        Icon::Search,
        Icon::ChevronUp,
        Icon::Close,
        Icon::ZoomOut,
        Icon::ZoomIn,
        Icon::FitPage,
        Icon::FitWidth,
        Icon::FitHeight,
        Icon::RotateCcw,
        Icon::RotateCw,
        Icon::Properties,
        Icon::Markup,
        Icon::Text,
        Icon::EditText,
        Icon::AddText,
        Icon::EditObjects,
        Icon::FormField,
        Icon::Measure,
        Icon::Undo,
        Icon::Redo,
        Icon::Copy,
        Icon::Tools,
        Icon::Keyboard,
        Icon::Info,
        Icon::ShowPoints,
        Icon::Bookmarks,
        Icon::Layers,
        Icon::Signatures,
        Icon::Sign,
        Icon::Fonts,
        Icon::Pointer,
        Icon::ShapeRect,
        Icon::ShapeEllipse,
        Icon::ShapeArrow,
        Icon::ShapePolyline,
        Icon::ShapePolygon,
        Icon::ShapeCloud,
        Icon::ShapeInk,
        Icon::ShapeHighlight,
        Icon::TextSelect,
        Icon::TextUnderline,
        Icon::TextStrikeout,
        Icon::TextSquiggly,
        Icon::TextFreeText,
        Icon::TextSticky,
        Icon::Stamp,
        Icon::ImportFormData,
        Icon::Combine,
        Icon::Split,
        Icon::InsertPages,
        Icon::FontFolders,
        Icon::Redact,
        Icon::Print,
        Icon::Export,
        Icon::Settings,
        Icon::InsertImage,
        Icon::SetScale,
        Icon::PageSingle,
        Icon::PageContinuous,
        Icon::PageFacing,
        Icon::PageFacingContinuous,
        Icon::ZoomRegion,
        Icon::ZoomSelection,
        Icon::Cut,
        Icon::Paste,
        Icon::Cursor,
        Icon::CursorNode,
        Icon::Hand,
        Icon::Rulers,
        Icon::Grid,
        Icon::Guides,
        Icon::Pages,
        Icon::Forms,
        Icon::ReadMode,
        Icon::Fullscreen,
        Icon::FloatingPanels,
        Icon::ResetLayout,
        Icon::Delete,
        Icon::PageExtract,
        Icon::FormFlatten,
        Icon::ManageList,
        Icon::PickText,
        Icon::PickPath,
        Icon::PickPart,
        Icon::PickFormXObject,
        Icon::PickLink,
        Icon::Document,
        Icon::Convert,
        Icon::SelectAll,
        Icon::ApplyRedactions,
        Icon::Attachment,
        Icon::Accept,
        Icon::CheckBox,
        Icon::CloseOthers,
        Icon::Collapse,
        Icon::CopyDocumentText,
        Icon::CopyPageText,
        Icon::DimensionGroups,
        Icon::NextDocument,
        Icon::PreviousDocument,
        Icon::DropDown,
        Icon::EmbedFonts,
        Icon::Expand,
        Icon::FinishShape,
        Icon::Locked,
        Icon::MeasureAngle,
        Icon::MeasureLength,
        Icon::MeasurePerimeter,
        Icon::MeasureRadius,
        Icon::MergeInto,
        Icon::New,
        Icon::NewFromTemplate,
        Icon::PushButton,
        Icon::PutDown,
        Icon::RadioButton,
        Icon::Recent,
        Icon::RecogniseText,
        Icon::RedactSelection,
        Icon::OffPage,
        Icon::Reflow,
        Icon::RenderDiagnostics,
        Icon::SaveAs,
        Icon::SaveCompacted,
        Icon::SaveCopy,
        Icon::UnembedFonts,
        Icon::WheelFlip,
        // CORRECTED 2026-09-05. This comment read *"the five with no
        // ribbon control yet … the other four are art before button"*, and by
        // the end of 2026-09-04 **all five were named by a registered
        // command**: `edit.copy_as_vector` (token 408, Edit ▸ Clipboard),
        // `file.encrypt` and `file.permissions` (126 / 127, File ▸ Security),
        // `file.export_image` (File ▸ Export) and `file.open_in_acrobat` (the
        // ribbon's trailing item). The art landed in the morning and the
        // buttons landed in the afternoon; the sentence describing the gap was
        // written between them and outlived it by hours.
        //
        // ⇒ **A sentence about what has not been built yet is a dated
        // citation, not a fact**, and on this project its shelf life has twice
        // been measured in hours rather than days. Where such a claim can be an
        // assertion it should be one — the reason this correction is possible
        // at all is that `Icon::ALL` is walked by the catalogue-wide tests, so
        // the *membership* below never went stale even while the prose did.
        //
        // The five stay in the list for the reason they joined it: membership
        // is what puts a variant under `every_icon_parses`,
        // `every_icon_rasterizes_to_visible_pixels` and the rest. That reason
        // is unaffected by whether a button exists.
        Icon::CopyAsVector,
        Icon::Encrypt,
        Icon::ExportImage,
        Icon::OpenInAcrobat,
        Icon::Permissions,
        Icon::Bold,
        Icon::Italic,
        Icon::LineWeights,
        Icon::AlignBefore,
        Icon::AlignLeft,
        Icon::AlignCentreH,
        Icon::AlignRight,
        Icon::AlignAfter,
        Icon::AlignTextH,
        Icon::AlignAbove,
        Icon::AlignTop,
        Icon::AlignCentreV,
        Icon::AlignBottom,
        Icon::AlignBelow,
        Icon::AlignTextV,
        Icon::DistributeLeft,
        Icon::DistributeCentreH,
        Icon::DistributeRight,
        Icon::DistributeGapsH,
        Icon::DistributeTextH,
        Icon::DistributeTop,
        Icon::DistributeCentreV,
        Icon::DistributeBottom,
        Icon::DistributeGapsV,
        Icon::DistributeTextV,
        Icon::ExchangeSelection,
        Icon::ExchangeStacking,
        Icon::ExchangeClockwise,
        Icon::Randomize,
        Icon::Unclump,
        Icon::RemoveOverlaps,
        Icon::ArrangeGrid,
        Icon::ArrangeCircular,
        Icon::NodesAlignVertical,
        Icon::NodesAlignHorizontal,
        Icon::NodesSpreadAcross,
        Icon::NodesSpreadDown,
        Icon::AlignCentre,
        Icon::AlignPanel,
        Icon::Model3d,
        Icon::ParaAlignLeft,
        Icon::ParaAlignCentre,
        Icon::ParaAlignRight,
        Icon::ParaJustify,
        Icon::Underline,
        Icon::Strikethrough,
    ];

    /// The asset's SVG source.
    #[must_use]
    pub const fn source(self) -> &'static str {
        match self {
            Icon::ApplyRedactions => assets::APPLY_REDACTIONS,
            Icon::Attachment => assets::ATTACHMENT,
            Icon::Accept => assets::CHECK,
            Icon::CheckBox => assets::CHECK_BOX,
            Icon::CloseOthers => assets::CLOSE_OTHERS,
            Icon::Collapse => assets::COLLAPSE,
            Icon::CopyDocumentText => assets::COPY_DOCUMENT_TEXT,
            Icon::CopyPageText => assets::COPY_PAGE_TEXT,
            Icon::DimensionGroups => assets::DIMENSION_GROUPS,
            Icon::NextDocument => assets::DOCUMENT_NEXT,
            Icon::PreviousDocument => assets::DOCUMENT_PREVIOUS,
            Icon::DropDown => assets::DROP_DOWN,
            Icon::EmbedFonts => assets::EMBED_FONTS,
            Icon::Expand => assets::EXPAND,
            Icon::FinishShape => assets::FINISH_SHAPE,
            Icon::Locked => assets::LOCK,
            Icon::MeasureAngle => assets::MEASURE_ANGLE,
            Icon::MeasureLength => assets::MEASURE_LENGTH,
            Icon::MeasurePerimeter => assets::MEASURE_PERIMETER,
            Icon::MeasureRadius => assets::MEASURE_RADIUS,
            Icon::MergeInto => assets::MERGE,
            Icon::New => assets::NEW_DOCUMENT,
            Icon::NewFromTemplate => assets::NEW_FROM_TEMPLATE,
            Icon::PushButton => assets::PUSH_BUTTON,
            Icon::PutDown => assets::PUT_DOWN,
            Icon::RadioButton => assets::RADIO_BUTTON,
            Icon::Recent => assets::RECENT,
            Icon::RecogniseText => assets::RECOGNISE_TEXT,
            Icon::RedactSelection => assets::REDACT_SELECTION,
            Icon::OffPage => assets::OFF_PAGE,
            Icon::Reflow => assets::REFLOW,
            Icon::RenderDiagnostics => assets::RENDER_DIAGNOSTICS,
            Icon::SaveAs => assets::SAVE_AS,
            Icon::SaveCompacted => assets::SAVE_COMPACT,
            Icon::SaveCopy => assets::SAVE_COPY,
            Icon::UnembedFonts => assets::UNEMBED_FONTS,
            Icon::WheelFlip => assets::WHEEL_FLIP,
            Icon::CopyAsVector => assets::COPY_AS_VECTOR,
            Icon::Encrypt => assets::ENCRYPT,
            Icon::ExportImage => assets::EXPORT_IMAGE,
            Icon::OpenInAcrobat => assets::OPEN_IN_ACROBAT,
            Icon::Permissions => assets::PERMISSIONS,
            Icon::Open | Icon::FontFolders => assets::FOLDER,
            Icon::Save => assets::SAVE,
            Icon::Sidebar => assets::SIDEBAR,
            Icon::Comment => assets::COMMENT,
            Icon::ChevronLeft => assets::CHEVRON_LEFT,
            Icon::Back => assets::BACK,
            Icon::ChevronRight => assets::CHEVRON_RIGHT,
            Icon::ChevronDown => assets::CHEVRON_DOWN,
            Icon::Search => assets::SEARCH,
            Icon::ChevronUp => assets::CHEVRON_UP,
            Icon::Close => assets::CLOSE,
            Icon::ZoomOut => assets::ZOOM_OUT,
            Icon::ZoomIn => assets::ZOOM_IN,
            Icon::FitPage => assets::FIT_PAGE,
            Icon::FitWidth => assets::FIT_WIDTH,
            Icon::FitHeight => assets::FIT_HEIGHT,
            Icon::RotateCcw => assets::ROTATE_CCW,
            Icon::RotateCw => assets::ROTATE_CW,
            Icon::Properties => assets::PROPERTIES,
            Icon::Document => assets::DOCUMENT,
            Icon::Convert => assets::CONVERT,
            Icon::SelectAll => assets::SELECT_ALL,
            Icon::Bold => assets::BOLD,
            Icon::Italic => assets::ITALIC,
            Icon::LineWeights => assets::LINE_WEIGHTS,
            Icon::Markup => assets::MARKUP,
            Icon::Text => assets::TEXT,
            Icon::EditText => assets::EDIT,
            Icon::AddText => assets::ADD_TEXT,
            Icon::FormField => assets::FORM_FIELD,
            Icon::EditObjects => assets::EDIT_OBJECTS,
            Icon::ShowPoints => assets::SHOW_POINTS,
            Icon::Bookmarks => assets::BOOKMARKS,
            Icon::Layers => assets::LAYERS,
            Icon::Signatures => assets::SIGNATURES,
            Icon::Sign => assets::SIGN,
            Icon::Fonts => assets::FONTS,
            Icon::Measure => assets::RULER,
            Icon::Undo => assets::UNDO,
            Icon::Redo => assets::REDO,
            Icon::Copy => assets::COPY,
            Icon::Tools => assets::TOOL,
            Icon::Keyboard => assets::KEYBOARD,
            Icon::Info => assets::INFO,
            Icon::Pointer => assets::POINTER,
            Icon::ShapeRect => assets::SHAPE_RECT,
            Icon::ShapeEllipse => assets::SHAPE_ELLIPSE,
            Icon::ShapeArrow => assets::SHAPE_ARROW,
            Icon::ShapePolyline => assets::SHAPE_POLYLINE,
            Icon::ShapePolygon => assets::SHAPE_POLYGON,
            Icon::ShapeCloud => assets::SHAPE_CLOUD,
            Icon::ShapeInk => assets::SHAPE_INK,
            Icon::ShapeHighlight => assets::SHAPE_HIGHLIGHT,
            Icon::TextSelect => assets::TEXT_SELECT,
            Icon::TextUnderline => assets::TEXT_UNDERLINE,
            Icon::TextStrikeout => assets::TEXT_STRIKEOUT,
            Icon::TextSquiggly => assets::TEXT_SQUIGGLY,
            Icon::TextFreeText => assets::TEXT_FREETEXT,
            Icon::TextSticky => assets::TEXT_STICKY,
            Icon::Stamp => assets::STAMP,
            Icon::Combine => assets::LINK,
            Icon::Split => assets::SCISSORS,
            Icon::InsertPages => assets::INSERT_PAGES,
            Icon::ImportFormData => assets::UPLOAD,
            Icon::Redact => assets::REDACT,
            Icon::Print => assets::PRINTER,
            Icon::Export => assets::DOWNLOAD,
            Icon::Settings => assets::SETTINGS,
            Icon::InsertImage => assets::IMAGE,
            Icon::SetScale => assets::SET_SCALE,
            Icon::PageSingle => assets::PAGE_SINGLE,
            Icon::PageContinuous => assets::PAGE_CONTINUOUS,
            Icon::PageFacing => assets::PAGE_FACING,
            Icon::PageFacingContinuous => assets::PAGE_FACING_CONTINUOUS,
            Icon::ZoomRegion => assets::ZOOM_REGION,
            Icon::ZoomSelection => assets::ZOOM_SELECTION,
            Icon::Cut => assets::CUT,
            Icon::Paste => assets::PASTE,
            Icon::Cursor => assets::CURSOR,
            Icon::CursorNode => assets::CURSOR_NODE,
            Icon::Hand => assets::HAND,
            Icon::Rulers => assets::RULERS,
            Icon::Grid => assets::GRID,
            Icon::Guides => assets::GUIDES,
            Icon::Pages => assets::PAGES,
            Icon::Forms => assets::FORMS,
            Icon::ReadMode => assets::READ_MODE,
            Icon::Fullscreen => assets::FULLSCREEN,
            Icon::FloatingPanels => assets::FLOATING_PANELS,
            Icon::ResetLayout => assets::RESET_LAYOUT,
            Icon::Delete => assets::DELETE,
            Icon::PageExtract => assets::PAGE_EXTRACT,
            Icon::FormFlatten => assets::FORM_FLATTEN,
            Icon::ManageList => assets::LIST,
            Icon::PickText => assets::PICK_TEXT,
            Icon::PickPath => assets::PICK_PATH,
            Icon::PickPart => assets::PICK_PART,
            Icon::PickFormXObject => assets::PICK_FORM_XOBJECT,
            Icon::PickLink => assets::PICK_LINK,
            Icon::AlignBefore => assets::ALIGN_BEFORE,
            Icon::AlignLeft => assets::ALIGN_LEFT,
            Icon::AlignCentreH => assets::ALIGN_CENTRE_H,
            Icon::AlignRight => assets::ALIGN_RIGHT,
            Icon::AlignAfter => assets::ALIGN_AFTER,
            Icon::AlignTextH => assets::ALIGN_TEXT_H,
            Icon::AlignAbove => assets::ALIGN_ABOVE,
            Icon::AlignTop => assets::ALIGN_TOP,
            Icon::AlignCentreV => assets::ALIGN_CENTRE_V,
            Icon::AlignBottom => assets::ALIGN_BOTTOM,
            Icon::AlignBelow => assets::ALIGN_BELOW,
            Icon::AlignTextV => assets::ALIGN_TEXT_V,
            Icon::DistributeLeft => assets::DISTRIBUTE_LEFT,
            Icon::DistributeCentreH => assets::DISTRIBUTE_CENTRE_H,
            Icon::DistributeRight => assets::DISTRIBUTE_RIGHT,
            Icon::DistributeGapsH => assets::DISTRIBUTE_GAPS_H,
            Icon::DistributeTextH => assets::DISTRIBUTE_TEXT_H,
            Icon::DistributeTop => assets::DISTRIBUTE_TOP,
            Icon::DistributeCentreV => assets::DISTRIBUTE_CENTRE_V,
            Icon::DistributeBottom => assets::DISTRIBUTE_BOTTOM,
            Icon::DistributeGapsV => assets::DISTRIBUTE_GAPS_V,
            Icon::DistributeTextV => assets::DISTRIBUTE_TEXT_V,
            Icon::ExchangeSelection => assets::EXCHANGE_SELECTION,
            Icon::ExchangeStacking => assets::EXCHANGE_STACKING,
            Icon::ExchangeClockwise => assets::EXCHANGE_CLOCKWISE,
            Icon::Randomize => assets::RANDOMIZE,
            Icon::Unclump => assets::UNCLUMP,
            Icon::RemoveOverlaps => assets::REMOVE_OVERLAPS,
            Icon::ArrangeGrid => assets::ARRANGE_GRID,
            Icon::ArrangeCircular => assets::ARRANGE_CIRCULAR,
            Icon::NodesAlignVertical => assets::NODES_ALIGN_VERTICAL,
            Icon::NodesAlignHorizontal => assets::NODES_ALIGN_HORIZONTAL,
            Icon::NodesSpreadAcross => assets::NODES_SPREAD_ACROSS,
            Icon::NodesSpreadDown => assets::NODES_SPREAD_DOWN,
            Icon::AlignCentre => assets::ALIGN_CENTRE,
            Icon::AlignPanel => assets::ALIGN_PANEL,
            Icon::Model3d => assets::MODEL_3D,
            Icon::ParaAlignLeft => assets::PARA_ALIGN_LEFT,
            Icon::ParaAlignCentre => assets::PARA_ALIGN_CENTRE,
            Icon::ParaAlignRight => assets::PARA_ALIGN_RIGHT,
            Icon::ParaJustify => assets::PARA_JUSTIFY,
            Icon::Underline => assets::UNDERLINE,
            Icon::Strikethrough => assets::STRIKETHROUGH,
        }
    }

    /// The stable key this icon answers to.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Icon::ApplyRedactions => "apply-redactions",
            Icon::Attachment => "attachment",
            Icon::Accept => "check",
            Icon::CheckBox => "check-box",
            Icon::CloseOthers => "close-others",
            Icon::Collapse => "collapse",
            Icon::CopyDocumentText => "copy-document-text",
            Icon::CopyPageText => "copy-page-text",
            Icon::DimensionGroups => "dimension-groups",
            Icon::NextDocument => "document-next",
            Icon::PreviousDocument => "document-previous",
            Icon::DropDown => "drop-down",
            Icon::EmbedFonts => "embed-fonts",
            Icon::Expand => "expand",
            Icon::FinishShape => "finish-shape",
            Icon::Locked => "lock",
            Icon::MeasureAngle => "measure-angle",
            Icon::MeasureLength => "measure-length",
            Icon::MeasurePerimeter => "measure-perimeter",
            Icon::MeasureRadius => "measure-radius",
            Icon::MergeInto => "merge",
            Icon::New => "new-document",
            Icon::NewFromTemplate => "new-from-template",
            Icon::PushButton => "push-button",
            Icon::PutDown => "put-down",
            Icon::RadioButton => "radio-button",
            Icon::Recent => "recent",
            Icon::RecogniseText => "recognise-text",
            Icon::RedactSelection => "redact-selection",
            // ui-text-exempt: icon key, never displayed.
            Icon::OffPage => "off-page",
            Icon::Reflow => "reflow",
            Icon::RenderDiagnostics => "render-diagnostics",
            Icon::SaveAs => "save-as",
            Icon::SaveCompacted => "save-compact",
            Icon::SaveCopy => "save-copy",
            Icon::UnembedFonts => "unembed-fonts",
            Icon::WheelFlip => "wheel-flip",
            Icon::CopyAsVector => "copy-as-vector",
            Icon::Encrypt => "encrypt",
            Icon::ExportImage => "export-image",
            // ui-text-exempt: icon key, never displayed. The vendor name is the
            // COMMAND's label, not this string, and the art carries no mark.
            Icon::OpenInAcrobat => "open-in-acrobat",
            Icon::Permissions => "permissions",
            Icon::Open => "open",
            Icon::Save => "save",
            Icon::Sidebar => "sidebar",
            Icon::Comment => "comment",
            Icon::Close => "close",
            Icon::ChevronLeft => "chevron-left",
            Icon::Back => "back",
            Icon::ChevronRight => "chevron-right",
            Icon::ChevronDown => "chevron-down",
            Icon::Search => "search",
            Icon::ChevronUp => "chevron-up",
            Icon::ZoomOut => "zoom-out",
            Icon::ZoomIn => "zoom-in",
            Icon::FitPage => "fit-page",
            Icon::FitWidth => "fit-width",
            // ui-text-exempt: icon key, never displayed
            Icon::FitHeight => "fit-height",
            Icon::RotateCcw => "rotate-ccw",
            Icon::RotateCw => "rotate-cw",
            Icon::Properties => "properties",
            Icon::Document => "document",
            Icon::Convert => "convert",
            Icon::SelectAll => "select-all",
            Icon::Bold => "bold",
            Icon::Italic => "italic",
            // ui-text-exempt: icon catalogue key, never displayed
            Icon::LineWeights => "line-weights",
            Icon::Markup => "markup",
            Icon::Text => "text",
            Icon::EditText => "edit-text",
            Icon::AddText => "add-text",
            Icon::FormField => "form-field",
            Icon::EditObjects => "edit-objects",
            Icon::ShowPoints => "show-points",
            Icon::Bookmarks => "bookmarks",
            Icon::Layers => "layers",
            Icon::Signatures => "signatures",
            Icon::Sign => "sign",
            Icon::Fonts => "fonts",
            Icon::Measure => "measure",
            Icon::Undo => "undo",
            Icon::Redo => "redo",
            Icon::Copy => "copy",
            Icon::Tools => "tools",
            Icon::Keyboard => "keyboard",
            Icon::Info => "info",
            // ui-text-exempt: icon asset key, never displayed
            Icon::Pointer => "pointer",
            Icon::ShapeRect => "shape-rect",
            Icon::ShapeEllipse => "shape-ellipse",
            Icon::ShapeArrow => "shape-arrow",
            Icon::ShapePolyline => "shape-polyline",
            Icon::ShapePolygon => "shape-polygon",
            // ui-text-exempt: icon asset key, never displayed
            Icon::ShapeCloud => "shape-cloud",
            Icon::ShapeInk => "shape-ink",
            Icon::ShapeHighlight => "shape-highlight",
            Icon::TextSelect => "text-select",
            Icon::TextUnderline => "text-underline",
            Icon::TextStrikeout => "text-strikeout",
            Icon::TextSquiggly => "text-squiggly",
            Icon::TextFreeText => "text-freetext",
            Icon::TextSticky => "text-sticky",
            Icon::Stamp => "stamp",
            Icon::Combine => "combine",
            Icon::Split => "split",
            Icon::InsertPages => "insert-pages",
            Icon::ImportFormData => "import-form-data",
            Icon::FontFolders => "font-folders",
            Icon::Redact => "redact",
            Icon::Print => "print",
            Icon::Export => "export",
            Icon::Settings => "settings",
            Icon::InsertImage => "insert-image",
            Icon::SetScale => "set-scale",
            Icon::PageSingle => "page-single",
            Icon::PageContinuous => "page-continuous",
            Icon::PageFacing => "page-facing",
            Icon::PageFacingContinuous => "page-facing-continuous",
            Icon::ZoomRegion => "zoom-region",
            Icon::ZoomSelection => "zoom-selection",
            Icon::Cut => "cut",
            Icon::Paste => "paste",
            Icon::Cursor => "cursor",
            Icon::CursorNode => "cursor-node",
            Icon::Hand => "hand",
            Icon::Rulers => "rulers",
            Icon::Grid => "grid",
            Icon::Guides => "guides",
            Icon::Pages => "pages",
            Icon::Forms => "forms",
            Icon::ReadMode => "read-mode",
            Icon::Fullscreen => "fullscreen",
            Icon::FloatingPanels => "floating-panels",
            Icon::ResetLayout => "reset-layout",
            Icon::Delete => "delete",
            Icon::PageExtract => "page-extract",
            Icon::FormFlatten => "form-flatten",
            Icon::ManageList => "list",
            // ui-text-exempt: diagnostic/lookup keys, matched by ui-verify and
            // by `from_key`; never rendered.
            Icon::PickText => "pick-text",
            // ui-text-exempt: diagnostic/lookup key, never rendered.
            Icon::PickPath => "pick-path",
            // ui-text-exempt: diagnostic/lookup key, never rendered.
            Icon::PickPart => "pick-part",
            // ui-text-exempt: diagnostic/lookup key, never rendered.
            Icon::PickFormXObject => "pick-form-xobject",
            // ui-text-exempt: diagnostic/lookup key, never rendered.
            Icon::PickLink => "pick-link",
            Icon::AlignBefore => "align-before",
            Icon::AlignLeft => "align-left",
            Icon::AlignCentreH => "align-centre-h",
            Icon::AlignRight => "align-right",
            Icon::AlignAfter => "align-after",
            Icon::AlignTextH => "align-text-h",
            Icon::AlignAbove => "align-above",
            Icon::AlignTop => "align-top",
            Icon::AlignCentreV => "align-centre-v",
            Icon::AlignBottom => "align-bottom",
            Icon::AlignBelow => "align-below",
            Icon::AlignTextV => "align-text-v",
            Icon::DistributeLeft => "distribute-left",
            Icon::DistributeCentreH => "distribute-centre-h",
            Icon::DistributeRight => "distribute-right",
            Icon::DistributeGapsH => "distribute-gaps-h",
            Icon::DistributeTextH => "distribute-text-h",
            Icon::DistributeTop => "distribute-top",
            Icon::DistributeCentreV => "distribute-centre-v",
            Icon::DistributeBottom => "distribute-bottom",
            Icon::DistributeGapsV => "distribute-gaps-v",
            Icon::DistributeTextV => "distribute-text-v",
            Icon::ExchangeSelection => "exchange-selection",
            Icon::ExchangeStacking => "exchange-stacking",
            Icon::ExchangeClockwise => "exchange-clockwise",
            Icon::Randomize => "randomize",
            Icon::Unclump => "unclump",
            Icon::RemoveOverlaps => "remove-overlaps",
            Icon::ArrangeGrid => "arrange-grid",
            Icon::ArrangeCircular => "arrange-circular",
            Icon::NodesAlignVertical => "nodes-align-vertical",
            Icon::NodesAlignHorizontal => "nodes-align-horizontal",
            Icon::NodesSpreadAcross => "nodes-spread-across",
            Icon::NodesSpreadDown => "nodes-spread-down",
            Icon::AlignCentre => "align-centre",
            Icon::AlignPanel => "align-panel",
            Icon::Model3d => "model-3d",
            Icon::ParaAlignLeft => "para-align-left",
            Icon::ParaAlignCentre => "para-align-centre",
            Icon::ParaAlignRight => "para-align-right",
            Icon::ParaJustify => "para-justify",
            Icon::Underline => "underline",
            Icon::Strikethrough => "strikethrough",
        }
    }

    /// Resolve an application icon key back to an [`Icon`].
    #[must_use]
    pub fn from_key(key: &str) -> Option<Self> {
        Self::ALL.iter().copied().find(|icon| icon.name() == key)
    }
}
