#!/usr/bin/env python3
"""Every non-Cargo file pdfcer-gui REDISTRIBUTES must have its licence recorded,
and that record must reach the person who was handed the binary.

A PORT of `D:\\Dev\\pdfcer\\tools\\check-shipped-assets.py`. Its reasoning is the
valuable part and is preserved below; what changed is marked "PORT CHANGE".
Read the original before editing this one — it is the specification.

WHY THIS GATE EXISTS
====================

`THIRD_PARTY_LICENSES.md` is generated by `cargo-about` from `Cargo.lock`. It
is complete and correct for what it covers, and it is **structurally
incapable** of covering anything that is not a Cargo dependency. Fonts, icons,
data tables, and — imminently — OCR model weights are files pdfcer ships inside
its portable folder or compiles into its executable, so they are redistributed
by pdfcer and carry whatever obligations their licences impose. `cargo-about`
cannot see any of them.

That is not a flaw in `cargo-about`; it is a gap between two tools, and a gap
between tools is exactly where an obligation goes missing without anyone
deciding to drop it.

WHY IT ARRIVED HERE, WHICH IS ITSELF THE FINDING
================================================

Until 2026-08-14 **this repository had no attribution surface of any kind** —
no `PROVENANCE.md`, no `cargo-about`, no third-party licence text anywhere in
the program or the package. That was defensible while pdfcer-gui shipped only
permissively-licensed *code*, whose notices the `LICENSE` file and the Cargo
metadata cover.

It stopped being defensible when the operator decided on 2026-08-14 to ship
the `ocrs` OCR model weights, which are **CC-BY-SA-4.0**. That licence's BY
clause requires the notice to reach the **end user**, not merely a reader of
the source tree — which is the whole distinction this gate is built around and
the reason check 4 exists.

Building the surface then turned up something nobody had gone looking for:
**three third-party works this binary already redistributes**, with no notice
anywhere. `pdfcer-render`'s `font::bundled` embeds fourteen BSD-3-Clause CFF
faces with `include_bytes!`, and `pdfcer-core`'s `fontdata::tables` compiles in
Adobe metric and glyph-list data. They arrive through path dependencies and
static linking, so they are inside `pdfcer-gui.exe` whether or not anyone in
this repository thought about them. The gate covers them explicitly — see
`REDISTRIBUTED_ENGINE_ASSETS`.

WHAT IT CHECKS
==============

For every asset directory this workspace redistributes — its own, under
`crates/**/assets/`, and the engine directories declared below:

1. A `PROVENANCE.md` exists.
2. That file NAMES A LICENCE — it must contain a recognisable licence
   identifier or an explicit statement of terms. A provenance note that says
   where files came from but not what may be done with them does not discharge
   anything.
3. Every shipped file in the directory is accounted for: at least one of the
   files actually present must be named, unless the note explicitly states it
   covers the whole directory.
4. ★ The directory is cited in **`about.hbs`**, the `cargo-about` template.
5. ★ PORT CHANGE — the directory is also cited in
   **`crates/pdfcer-gui/src/text/about.rs`**, the in-application surface.

Checks 4 and 5 are the ones that reach the OPERATOR rather than the
repository. `PROVENANCE.md` records terms for whoever reads the source tree;
it does NOT ship.

`about.hbs` is where the packaged half is fixed: it is the handlebars template
`cargo-about` renders, so a hand-written section in its static epilogue flows
into the generated `THIRD_PARTY_LICENSES.md` and therefore into every release.

★ WHY THIS PORT ADDS A FIFTH CHECK, WHEN THE ENGINE MANAGES WITH FOUR
=====================================================================

Because the engine is a CLI and this is a GUI, and the difference is not
cosmetic.

pdfcer's shipped notice is a file in a folder, and a CLI operator is already in
that folder — they got there to run the executable. A GUI operator may never
see it: they launch from a shortcut or a file association, and the folder is
somewhere a support engineer would have to talk them into opening. A `.md`
file is also one tidy-up away from being deleted by someone who does not know
what it is.

So this shell carries **both** surfaces — the file in the package, and an
About dialog reachable from File ▸ pdfcer — and the gate requires both,
because a change that remembers one and forgets the other is the commonest way
an obligation half-lands. The two are not redundant: the file carries the
licence TEXTS, which a dialog cannot reasonably render; the dialog carries the
ATTRIBUTION, which is what BY actually asks be given to the recipient.

Note what is NOT claimed here: that a UI surface is legally required. A notice
file shipped alongside is the ordinary way this obligation is discharged. The
second surface is a product judgement — the operator asked for the model to
ship *"with proper credit"* — and having built it, the gate keeps it true.

**Own work is exempt from 4 and 5.** An asset whose `PROVENANCE.md` says it is
pdfcer's own art under the project licence needs neither entry — the shipped
`LICENSE` already covers it and there is no third-party grant to reproduce.
The GUI icon set is exactly this case. In the engine, check 4 flagged that set
on its first run before the exemption existed; that was a false positive, and
a gate that fires on a correct state is one people learn to ignore.

Check 3 is deliberately loose — the goal is to catch a directory that quietly
gained twenty model files under a provenance note describing three fonts, not
to demand a table row per icon.

TWO CHECKS THE ENGINE HAS NO NEED FOR
=====================================

6. **The notice must actually be in the package.** `tools/package-portable.py`
   copies a declared list of documents into the portable folder. A
   `THIRD_PARTY_LICENSES.md` that exists in the repository and is not in that
   list ships to nobody, and looks exactly like one that does.

7. **The generated notice must not have drifted from its template.** The
   static epilogue in `about.hbs` — everything from the `STATIC-EPILOGUE-BEGIN`
   marker to end of file — is literal text, so it must appear verbatim in
   `THIRD_PARTY_LICENSES.md`. If it does not, somebody edited the template and
   never regenerated, and the release carries a notice missing the very
   section that was just written.

   `HANDOFF.md` §10 records exactly this failure mode for a different
   generated file: the RON manifest "has no compiler behind it and no failure
   until someone else runs the round-trip", and it has now been found stale
   twice in one day. A generated compliance artifact deserves better than
   somebody remembering.

WHY NOT JUST TRUST A REVIEWER
=============================

Because the failure is silent and delayed. A model file added today ships in
every release from now on; the moment anyone notices is after distribution,
and un-distributing is not a thing. A gate costs one CI second.

★ WHY THIS GATE IS PYTHON WHEN EVERY OTHER GATE HERE IS BASH
============================================================

Stated because the inconsistency is real and someone will want to fix it.

Checks 6 and 7 are the two that make this gate worth having in a repository
whose own asset directory is the operator's own art and therefore exempt from
most of the others. Check 6 has to read **`PAYLOAD_DOCS` and
`PAYLOAD_ASSET_DIRS` out of `tools/package-portable.py`**, which is Python
source. This file imports that module and reads the actual list objects, so
the check is exact: renaming a constant raises `AttributeError` and fails the
gate loudly, and restructuring the list into a tuple or a dict still works.

The bash alternative is a `grep` for a bracketed list, and a grep that stops
matching prints exactly what a clean run prints — which is the single failure
mode every gate in this directory was written to avoid. `check-ui-strings.sh`
records a sibling gate that "would print `ui-strings: clean` while checking a
handful of files"; a grep over a Python list would be the same defect wearing
a different hat.

So: bash where the check IS a grep over source, Python where the check is
"what does this program's data structure actually say". The engine's copy of
this gate is Python for its own reasons and the convention is at least shared
across the two repositories rather than split within one.

`check-shipped-assets.sh` is a three-line wrapper that finds an interpreter
and reports a SKIP with the real reason if there is none, so `run-all.sh`
invokes this gate exactly like every other.

USAGE / EXIT CODES
==================

  tools/gates/check-shipped-assets.py              the real run
  tools/gates/check-shipped-assets.py --self-test  prove the gate bites

  0 — every redistributed asset records its licensing, and that record reaches
      both the package and the running program.
  1 — at least one does not. The offending directory is named, with what is
      missing and what to do about it.
  2 — PRECONDITION ABSENT (a SKIP, not a pass): this is not the workspace
      root, or a declared engine directory's tree is not mounted. `run-all.sh`
      renders 2 as SKIPPED and refuses to call the overall run a pass.
"""

from __future__ import annotations

import importlib.util
import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent

#: The engine tree. Read-only to this project — this gate only ever READS it.
# ★★★ DERIVED, NOT ASSUMED — see `tools/engine_path.py`.
#
# This was a hard-coded literal until 2026-09-03, when the project's rename
# pointed it at a directory the engine had not created yet and this instrument
# went silently blind. `engine_path.locate` reads the git URL out of the
# manifest Cargo actually builds from, so it follows the temporary
# `package = ...` shim and will follow the engine's rename without anybody
# remembering that this line exists.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import engine_path  # noqa: E402

ENGINE = engine_path.locate() or Path("D:/Dev/pdfcer")

#: The `cargo-about` template. A hand-written section in its static epilogue is
#: the ONLY route by which a non-Cargo asset's licence reaches the shipped
#: `THIRD_PARTY_LICENSES.md`, and therefore the only route by which it reaches
#: anyone who was given a binary rather than the source.
_ABOUT_TEMPLATE = "about.hbs"

#: The generated notice, at the workspace root and in the portable folder.
_NOTICE = "THIRD_PARTY_LICENSES.md"

#: The in-application attribution surface. Its `attributions()` catalog is what
#: the About dialog draws; a directory is "cited" here if its repository-relative
#: path appears anywhere in the file, which in practice means in the comment
#: above the entry that covers it. The path is deliberately NOT required to be
#: in operator-visible copy: an end user does not want a source path, and
#: forcing one into a label would make the dialog worse to satisfy a gate.
_IN_APP_SURFACE = "crates/pdfcer-gui/src/text/about.rs"

#: Marks the start of `about.hbs`'s literal epilogue. Everything from here to
#: end of file must appear verbatim in the generated notice — see check 7.
_EPILOGUE_MARKER = "<!-- STATIC-EPILOGUE-BEGIN -->"

# Files that are documentation ABOUT the assets rather than shipped assets.
_DOC_SUFFIXES = {".md", ".txt"}


@dataclass(frozen=True)
class EngineAsset:
    """An asset directory in `D:\\Dev\\pdfcer` that THIS binary redistributes.

    The engine is a separate repository with its own packaging, so nothing in
    its tree knows that pdfcer-gui ships its assets too. This list is that
    knowledge, written down where the gate can act on it.

    `how` is either:

    * ``"linked"`` — the files are compiled into `pdfcer-gui.exe` (an
      `include_bytes!` in a path dependency, statically linked). They ship
      whether or not the packager does anything.
    * ``"copied"`` — the files must be copied into the portable folder as
      loose files, so `tools/package-portable.py` has to carry them. The gate
      cross-checks that they are in `PAYLOAD_ASSET_DIRS`; a "copied" entry the
      packager does not know about is an asset that is attributed and then
      never shipped, which is a different kind of wrong from the usual one.
    """

    #: Path relative to the engine repository root, forward-slashed.
    path: str
    #: "linked" or "copied" — see the class docstring.
    how: str
    #: Why this binary redistributes it. Prose, for the failure message.
    why: str


#: Engine asset directories `pdfcer-gui.exe` redistributes.
#:
#: ★ THE SECOND ENTRY ARRIVED 2026-08-14, AND IS WHY THIS GATE WAS BUILT.
#:
#: `crates/pdfcer-core/assets/models/ocrs` — the CC-BY-SA-4.0 OCR model weights,
#: 12,240,008 bytes over two `.rten` files, accepted into the MIT portable
#: folder by the operator on 2026-08-14. It is `how="copied"` rather than
#: `how="linked"`: `pdfcer_core::ocr::models::resolve_model_dir` resolves them
#: from a `models/<engine>` directory beside the executable, so they are loose
#: files in the portable folder and the packager has to put them there.
#:
#: That declaration is load-bearing in **both** directions, which is the whole
#: shape this gate was written for. `how="copied"` makes check 6b demand an
#: entry in `PAYLOAD_ASSET_DIRS` — an attribution for files nobody receives is
#: as wrong as files received with no attribution — while checks 4 and 5 demand
#: the notice and the About dialog. Declaring the asset and forgetting any one
#: of the three fails here rather than shipping.
REDISTRIBUTED_ENGINE_ASSETS: list[EngineAsset] = [
    EngineAsset(
        # ★ Derived: under the temporary rename shim the engine's directories
        # still carry their old names. See `tools/engine_path.py`.
        path=f"crates/{engine_path.crate_name('render')}/assets/fonts",
        how="linked",
        why=(
            "pdfcer-render's `font::bundled` embeds all fourteen faces with "
            "`include_bytes!`, and pdfcer-gui links pdfcer-render statically, so "
            "they are inside pdfcer-gui.exe"
        ),
    ),
    EngineAsset(
        path=f"crates/{engine_path.crate_name('core')}/assets/models/ocrs",
        how="copied",
        why=(
            "the `tools.ocr` command recognises text through "
            "`pdfcer_core::ocr::engine_ocrs`, which loads these two `.rten` "
            "files from a `models/ocrs` directory beside the running "
            "executable — so package-portable.py copies them into every "
            "portable folder, and pdfcer redistributes a CC-BY-SA-4.0 work"
        ),
    ),
]

# Recognisable licence identifiers, plus the phrasings this project's existing
# provenance notes actually use. Matched case-insensitively.
#
# Deliberately broad: the check is "did somebody state the terms", not "did
# they pick from an approved list". A bespoke grant ("the operator drew these
# himself and places them under the project licence") is a real answer and
# must pass, which is why the operator/own-work phrasings are here alongside
# the SPDX ids.
_LICENCE_SIGNALS = [
    r"\bMIT\b",
    r"\bApache[- ]2\.0\b",
    r"\bBSD-[23]-Clause\b",
    r"\bAPAFML\b",
    r"\bCC-BY(-SA)?-\d",
    r"\bCC0\b",
    r"\bSIL\b|\bOFL\b",
    r"\bZlib\b",
    r"\bUnlicense\b",
    r"\bpublic domain\b",
    r"\blicen[cs]e\b.{0,40}\b(grant|terms|is|are)\b",
    r"\bdrawn from scratch\b",
    r"\boriginal work\b",
    r"\bproject licen[cs]e\b",
]
_LICENCE_RE = re.compile("|".join(_LICENCE_SIGNALS), re.IGNORECASE)

# A provenance note may declare that it covers everything beside it, which
# exempts it from the per-file accounting in check 3.
_COVERS_ALL_RE = re.compile(
    r"covers (every|all) (file|asset)|all files in this (directory|folder)",
    re.IGNORECASE,
)

#: Provenance phrasings meaning "this is OUR work, under pdfcer's own licence".
#:
#: Such assets need no entry in `about.hbs` and none in the About dialog,
#: because the `LICENSE` file that already ships with every release covers
#: them — there is no third-party grant to reproduce. Checks 4 and 5 exempt
#: them.
_OWN_WORK_RE = re.compile(
    r"operator's own work|own art|drawn from scratch|no third-party licen[cs]e"
    r"|project licen[cs]e|covered by pdfcer's",
    re.IGNORECASE,
)


def _shipped_files(directory: Path) -> list[Path]:
    """Files in `directory` that are shipped rather than documentation."""
    if not directory.is_dir():
        return []
    return [
        p
        for p in sorted(directory.iterdir())
        if p.is_file() and p.suffix.lower() not in _DOC_SUFFIXES
    ]


def _asset_dirs_under(crates: Path) -> list[Path]:
    """Every directory under `crates` that holds shipped asset files.

    ★ PORT CHANGE — the engine scans `crates/*/assets/` only. This shell's own
    art lives at `crates/pdfcer-gui/src/icons/assets/`, INSIDE the module that
    reads it, and `icons::assets`' header gives the reason: the rebuild ran
    several agents over one tree and the boundaries between them were
    directories, so the icon work's territory was `src/icons/`. A gate that
    only looked one level under a crate root would have found nothing at all
    in this repository and reported it as clean — the exact shape of failure
    `check-ui-strings.sh` was ported here to fix.

    So: any directory NAMED `assets`, at any depth, plus its subdirectories.
    """
    found: list[Path] = []
    if not crates.is_dir():
        return found
    for assets in sorted(crates.rglob("assets")):
        if not assets.is_dir():
            continue
        for sub in sorted(assets.rglob("*")):
            if sub.is_dir() and _shipped_files(sub):
                found.append(sub)
        if _shipped_files(assets):
            found.append(assets)
    return found



def _cites(haystack: str, label: str) -> bool:
    """Does `haystack` cite `label`, under EITHER spelling of the engine crates?

    ★★ Added 2026-09-03 with the rename. The declared path is *derived* from the
    manifest so it points at the directory that exists today — which, under the
    temporary `package = ...` shim, still carries the engine's OLD crate name.
    The attributions in `about.hbs` and `about.rs`, by contrast, were renamed
    with the rest of this repository and name the destination.

    Both are right. An attribution is a statement about the work being
    redistributed, not about a directory layout that is mid-migration, and
    making it flip twice — once now and once when the engine renames — would be
    churn in the one file whose whole job is to be stable for the people we ship
    to.

    ⇒ So the citation test normalises. When the engine's rename lands the two
    spellings converge and this becomes an identity.
    """
    if label in haystack:
        return True
    # old-name-exempt: the substitution this helper performs, spelled out.
    # The label carries the engine's pre-rename crate name while the shim is up;
    # the haystack is already the new
    # spelling, and normalising both directions could match a genuinely absent
    # citation against an unrelated one.
    return label.replace("pdfce-", "pdfcer-") in haystack  # old-name-exempt: the mapping itself

def check_directory(
    directory: Path,
    label: str,
    about: str,
    in_app: str,
    context: str = "",
) -> list[str]:
    """Checks 1-5 for one asset directory. Returns a list of problems.

    Split out from `main` and parameterised over the two notice texts so that
    `--self-test` can aim it at a planted fixture. A gate whose checks cannot
    be pointed anywhere else cannot be proven to bite.
    """
    problems: list[str] = []
    files = _shipped_files(directory)
    prov = directory / "PROVENANCE.md"
    where = f" ({context})" if context else ""

    if not prov.is_file():
        problems.append(
            f"  {label}{where}\n"
            f"      {len(files)} shipped file(s), NO PROVENANCE.md.\n"
            f"      cargo-about cannot see these — if pdfcer-gui redistributes them,\n"
            f"      their licensing exists nowhere. Add PROVENANCE.md recording\n"
            f"      where they came from and under what terms."
        )
        return problems

    text = prov.read_text(encoding="utf-8", errors="replace")

    if not _LICENCE_RE.search(text):
        problems.append(
            f"  {label}/PROVENANCE.md{where}\n"
            f"      Records provenance but NAMES NO LICENCE. Saying where a file\n"
            f"      came from does not say what may be done with it, and pdfcer\n"
            f"      ships these to other people."
        )
        return problems

    if not _COVERS_ALL_RE.search(text):
        # Loose accounting: at least one shipped filename (or its stem) should
        # appear. Catches a directory that gained a whole new class of asset
        # under a note describing the old ones.
        named = sum(1 for f in files if f.name in text or f.stem in text)
        if named == 0:
            problems.append(
                f"  {label}/PROVENANCE.md{where}\n"
                f"      Names a licence but mentions NONE of the {len(files)} file(s)\n"
                f"      actually in this directory. Either the files changed and the\n"
                f"      note did not, or the note covers something else."
            )

    if _OWN_WORK_RE.search(text):
        # Own work: the shipped LICENSE already covers it. Checks 4 and 5 do
        # not apply, and firing them here would be the engine's recorded false
        # positive, repeated knowingly.
        return problems

    # ★ Check 4 — does the licence reach the people who get a BINARY?
    #
    # Against the RENDERED template, not the raw file: see `rendered`, which
    # exists because the raw form let a "this one is deliberately absent"
    # comment satisfy a check for presence.
    if not _cites(rendered(about), label):
        problems.append(
            f"  {label}{where}\n"
            f"      Has a PROVENANCE.md, but {_ABOUT_TEMPLATE} never cites this\n"
            f"      directory — so its licence does NOT reach the generated\n"
            f"      {_NOTICE}, and therefore never reaches anyone\n"
            f"      who was given a binary rather than the source.\n"
            f"      PROVENANCE.md is for readers of the repository;\n"
            f"      {_ABOUT_TEMPLATE} is for the people you ship to.\n"
            f"      Add a section to its static epilogue; the Foxit faces are the\n"
            f"      worked example to copy."
        )

    # ★ Check 5 — and does it reach someone who never opens the folder?
    if not _cites(in_app, label):
        problems.append(
            f"  {label}{where}\n"
            f"      Not cited in {_IN_APP_SURFACE}, so the About dialog does not\n"
            f"      attribute it. A GUI operator launches from a shortcut and may\n"
            f"      never see the folder the notice file sits in.\n"
            f"      Add an `Attribution` to `attributions()` and name this path in\n"
            f"      the comment above it."
        )

    return problems


def _load_packager():
    """Import `tools/package-portable.py` and hand back the module.

    By import rather than by grep, and that is the reason this gate is Python
    — see the header. The hyphen in the filename is why this needs
    `importlib` rather than a plain `import`.
    """
    path = ROOT / "tools" / "package-portable.py"
    if not path.is_file():
        return None
    spec = importlib.util.spec_from_file_location("pdfcergui_packager", path)
    if spec is None or spec.loader is None:
        return None
    module = importlib.util.module_from_spec(spec)

    # ★ A GATE MUST NOT DIRTY THE WORKING TREE.
    #
    # Importing a module writes `tools/__pycache__/package-portable.*.pyc`, and
    # that directory is tracked in this repository — so the first run of this
    # gate showed up in `git status` as a modified file. A check that changes
    # the thing it is checking is a check whose "clean" result is one degree
    # less trustworthy, and on a project whose packager stamps a source digest
    # into every build, a gate that moves bytes is worse than merely untidy.
    #
    # Restored afterwards rather than left off, because the flag is global and
    # this gate is importable.
    previous = sys.dont_write_bytecode
    sys.dont_write_bytecode = True
    try:
        spec.loader.exec_module(module)
    finally:
        sys.dont_write_bytecode = previous
    return module


def check_packaging(about: str, notice: str) -> list[str]:
    """Checks 6 and 7 — the notice ships, and it is not stale."""
    problems: list[str] = []

    packager = _load_packager()
    if packager is None:
        problems.append(
            "  tools/package-portable.py\n"
            "      Could not be imported, so this gate cannot verify that the\n"
            "      notice reaches the package at all."
        )
        return problems

    # --- 6a. the notice is in the payload ---------------------------------
    try:
        payload_docs = list(packager.PAYLOAD_DOCS)
    except AttributeError:
        problems.append(
            "  tools/package-portable.py\n"
            "      has no `PAYLOAD_DOCS`. This gate reads that list to check that\n"
            "      the notice is actually copied into the portable folder. If it\n"
            "      was renamed, rename it here too — do not delete the check."
        )
        return problems

    if _NOTICE not in payload_docs:
        problems.append(
            f"  {_NOTICE}\n"
            f"      exists in the repository and is NOT in package-portable.py's\n"
            f"      PAYLOAD_DOCS, so it ships to nobody. Every licence text this\n"
            f"      binary is obliged to reproduce is in that file, and the folder\n"
            f"      an operator is handed would not contain it.\n"
            f"      PAYLOAD_DOCS is currently: {payload_docs}"
        )

    # --- 6b. every "copied" engine asset is in the packager's list ---------
    try:
        payload_assets = {str(src) for src, _dest in packager.PAYLOAD_ASSET_DIRS}
    except AttributeError:
        problems.append(
            "  tools/package-portable.py\n"
            "      has no `PAYLOAD_ASSET_DIRS`. That list is how an engine asset\n"
            "      directory gets copied into the portable folder; without it a\n"
            "      `how=\"copied\"` entry below can never be satisfied."
        )
        payload_assets = set()
    except (TypeError, ValueError):
        problems.append(
            "  tools/package-portable.py\n"
            "      `PAYLOAD_ASSET_DIRS` is not a list of (source, destination)\n"
            "      pairs any more. This gate reads it to check that an attributed\n"
            "      asset is actually shipped."
        )
        payload_assets = set()

    for asset in REDISTRIBUTED_ENGINE_ASSETS:
        if asset.how == "copied" and asset.path not in payload_assets:
            problems.append(
                f"  {asset.path}\n"
                f"      is declared `how=\"copied\"` but package-portable.py's\n"
                f"      PAYLOAD_ASSET_DIRS does not carry it, so it is attributed\n"
                f"      and never shipped. Either add it to that list or change the\n"
                f"      declaration — an attribution for a file nobody receives is\n"
                f"      as wrong as a file received with no attribution."
            )

    problems.extend(check_notice_freshness(about, notice))
    return problems


def check_notice_freshness(about: str, notice: str) -> list[str]:
    """Check 7 — the generated notice still carries its template's epilogue.

    Its own function rather than a branch of [`check_packaging`], so that
    `--self-test` can plant a stale notice without dragging the real
    packager's payload list into a synthetic case.
    """
    if _EPILOGUE_MARKER not in about:
        return [
            f"  {_ABOUT_TEMPLATE}\n"
            f"      has no `{_EPILOGUE_MARKER}` marker. That marker bounds the\n"
            f"      literal region this gate compares against the generated file;\n"
            f"      without it, a template edit that never reached\n"
            f"      {_NOTICE} cannot be detected."
        ]

    epilogue = _normalise(about[about.index(_EPILOGUE_MARKER) :])
    if epilogue not in _normalise(notice):
        return [
            f"  {_NOTICE}\n"
            f"      is STALE: {_ABOUT_TEMPLATE}'s static epilogue does not appear in\n"
            f"      it verbatim. Somebody edited the template and did not\n"
            f"      regenerate, so the shipped notice is missing the section that\n"
            f"      was just written. Regenerate it:\n"
            f"          cargo about generate about.hbs -o {_NOTICE}"
        ]
    return []


#: An HTML comment in `about.hbs`, non-greedy, across lines.
_HTML_COMMENT_RE = re.compile(r"<!--.*?-->", re.DOTALL)


def rendered(about: str) -> str:
    """`about.hbs` with its HTML comments removed.

    ★ THIS FUNCTION EXISTS BECAUSE THE GATE CAUGHT ITS OWN AUTHOR.

    Check 4 asks "is this directory cited in the template", and the first
    implementation asked it of the raw file. `about.hbs`'s epilogue carries a
    long comment explaining which directories are **deliberately absent** from
    it — including, by name, the path of the OCR model weights that had not
    shipped yet.

    So the first violation planted against this gate — declaring those weights
    redistributed before writing their notice — was **not** caught by check 4.
    The template "cited" the directory in a paragraph whose entire content was
    *this directory is not attributed here*. A comment saying a thing is
    missing is the one string that must never satisfy a check for its
    presence.

    It is the same reasoning `check-theme-colors.sh` already applies to Rust —
    "a comment mentioning a colour is prose, not a drawn colour". Here a
    comment mentioning a path is maintenance notes, not an attribution. So the
    comments are stripped and the check runs against what the notice actually
    says to the person who receives it.
    """
    return _HTML_COMMENT_RE.sub("", about)


def _normalise(text: str) -> str:
    """Line endings only.

    `.gitattributes` and `core.autocrlf` between them mean a checked-out file
    may be CRLF while a freshly generated one is LF, and a byte comparison
    would then report every file as stale on somebody else's clone. The
    comparison is about WORDS, so the line ending is noise.
    """
    return text.replace("\r\n", "\n")


def self_test() -> int:
    """Prove the gate detects its own planted violations.

    Runs FIRST in run-all.sh, before this gate's verdict on the real tree is
    trusted. `PROJECT_PLAN.md` §4.1 records a sibling gate that printed
    "clean" while checking a handful of files: finding nothing looks exactly
    like finding no violations, and the only way to tell them apart is to hand
    the gate something it MUST find.

    Six cases, and the last three are the ways this gate could rot into
    uselessness without anyone noticing:

      1. no PROVENANCE.md at all               -> must be caught
      2. a PROVENANCE.md naming no licence     -> must be caught
      3. a licence, but no `about.hbs` entry   -> must be caught  (check 4)
      4. a licence, but no in-app entry        -> must be caught  (check 5)
      5. cited in about.hbs only inside an HTML COMMENT -> must be caught
      6. the same, declared as OWN WORK        -> must NOT be caught (exemption)
      7. fully documented in both surfaces     -> must NOT be caught

    ★ Case 5 is not hypothetical and not defensive. It is the violation this
    gate FAILED to catch the first time one was planted against it, on the day
    it was written — see [`rendered`]. It is here so that the fix cannot be
    undone by someone simplifying `rendered` away.
    """
    import tempfile

    failures: list[str] = []

    def plant(root: Path, name: str, provenance: str | None) -> Path:
        d = root / name
        d.mkdir(parents=True)
        (d / "asset.bin").write_bytes(b"\x00")
        if provenance is not None:
            (d / "PROVENANCE.md").write_text(provenance, encoding="utf-8")
        return d

    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        cases = {
            "in-a-comment-only": "# PROVENANCE\n\n`asset.bin`. Licence: MIT.\n",
            "no-provenance": None,
            "no-licence": "# PROVENANCE\n\nCopied from somewhere, on 2026-08-14.\n",
            "not-in-hbs": "# PROVENANCE\n\n`asset.bin`. Licence: MIT.\n",
            "not-in-app": "# PROVENANCE\n\n`asset.bin`. Licence: MIT.\n",
            "own-work": "# PROVENANCE\n\n`asset.bin`. The operator's own art under the project licence.\n",
            "documented": "# PROVENANCE\n\n`asset.bin`. Licence: MIT.\n",
        }
        dirs = {name: plant(root, name, text) for name, text in cases.items()}

        # The two notice surfaces, as a correctly-maintained pair would have
        # them: `not-in-app` is cited in the template only, `not-in-hbs` in the
        # app only, `documented` in both.
        #
        # `in-a-comment-only` is named in the template — but ONLY inside an
        # HTML comment, which is the exact shape that fooled check 4 the first
        # time a violation was planted against this gate. See `rendered`.
        about = (
            "cited: not-in-app\ncited: documented\n"
            "<!-- in-a-comment-only is deliberately absent from this file -->\n"
        )
        in_app = "cited: not-in-hbs\ncited: documented\ncited: in-a-comment-only\n"

        caught: dict[str, list[str]] = {
            name: check_directory(path, name, about, in_app)
            for name, path in dirs.items()
        }

        must_catch = {
            "no-provenance": "a directory with no PROVENANCE.md",
            "no-licence": "a PROVENANCE.md that names no licence",
            "not-in-hbs": f"an asset absent from {_ABOUT_TEMPLATE}",
            "not-in-app": "an asset absent from the About dialog",
            "in-a-comment-only": (
                "an asset named in about.hbs ONLY inside an HTML comment — a "
                "comment saying a directory is absent must never satisfy a "
                "check for its presence"
            ),
        }
        for name, description in must_catch.items():
            if not caught[name]:
                failures.append(f"did not catch {description} ({name}/)")

        if caught["own-work"]:
            failures.append(
                "the own-work exemption did not fire — the gate would flag the "
                f"operator's own art: {caught['own-work']}"
            )
        if caught["documented"]:
            failures.append(
                "a fully documented directory was flagged — the gate has false "
                f"positives: {caught['documented']}"
            )

        # The two checks must be INDEPENDENT. If check 5 were accidentally
        # keyed off `about` as well, `not-in-hbs` would report two problems and
        # `not-in-app` none — and both of the assertions above would still
        # pass. This is the assertion that makes them mean something.
        if len(caught["not-in-hbs"]) != 1:
            failures.append(
                "an asset missing only from about.hbs produced "
                f"{len(caught['not-in-hbs'])} problems, expected exactly 1 — "
                "checks 4 and 5 are not independent"
            )
        if len(caught["not-in-app"]) != 1:
            failures.append(
                "an asset missing only from the About dialog produced "
                f"{len(caught['not-in-app'])} problems, expected exactly 1 — "
                "checks 4 and 5 are not independent"
            )

    # Check 7's own planted violations, run against `check_notice_freshness`
    # directly rather than through `check_packaging`. The latter imports the
    # REAL packager, and a self-test that reports a problem with the real tree
    # is a self-test whose result nobody can read.
    template = f"body\n{_EPILOGUE_MARKER}\nA section written today.\n"
    if not any(
        "STALE" in p
        for p in check_notice_freshness(
            template, "a notice generated before that section existed\n"
        )
    ):
        failures.append(
            "did not catch a generated notice missing its template's epilogue"
        )
    if check_notice_freshness(template, f"crates\n{template}"):
        failures.append("reported a freshly generated notice as stale")
    if not check_notice_freshness("a template with no marker at all\n", "anything\n"):
        failures.append("did not notice that about.hbs had lost its epilogue marker")

    for message in failures:
        print(f"shipped-assets self-test: FAIL — {message}")
    if failures:
        return 1
    print(
        "shipped-assets self-test: the gate catches all five planted violations"
        " (including one cited only inside an HTML comment), exempts own work,"
        " and passes a documented directory."
    )
    return 0


def main() -> int:
    if not (ROOT / "Cargo.toml").is_file():
        print(f"shipped-assets: SKIPPED — {ROOT} is not the pdfcer-gui workspace root.")
        print("  Nothing was scanned, and 'nothing scanned' is not 'nothing wrong'.")
        return 2

    about_path = ROOT / _ABOUT_TEMPLATE
    if not about_path.is_file():
        print(f"shipped-assets: FAIL — {_ABOUT_TEMPLATE} is missing.")
        print("  It is the cargo-about template and the only route by which a")
        print("  non-Cargo asset's licence reaches the shipped notice file.")
        return 1
    about = about_path.read_text(encoding="utf-8", errors="replace")

    in_app_path = ROOT / _IN_APP_SURFACE
    if not in_app_path.is_file():
        print(f"shipped-assets: FAIL — {_IN_APP_SURFACE} is missing.")
        print("  It is the in-application attribution surface. Without it the")
        print("  About dialog has nothing to draw and check 5 cannot run.")
        return 1
    in_app = in_app_path.read_text(encoding="utf-8", errors="replace")

    notice_path = ROOT / _NOTICE
    if not notice_path.is_file():
        print(f"shipped-assets: FAIL — {_NOTICE} has never been generated.")
        print("  Generate it: cargo about generate about.hbs -o " + _NOTICE)
        return 1
    notice = notice_path.read_text(encoding="utf-8", errors="replace")

    problems: list[str] = []
    scanned = 0
    total_files = 0

    # --- this workspace's own asset directories ---------------------------
    for directory in _asset_dirs_under(ROOT / "crates"):
        rel = directory.relative_to(ROOT).as_posix()
        scanned += 1
        total_files += len(_shipped_files(directory))
        problems.extend(check_directory(directory, rel, about, in_app))

    # --- engine directories this binary redistributes ---------------------
    if REDISTRIBUTED_ENGINE_ASSETS and not (ENGINE / "Cargo.toml").is_file():
        print(f"shipped-assets: SKIPPED — the engine tree {ENGINE} is not present.")
        print(f"  {len(REDISTRIBUTED_ENGINE_ASSETS)} declared asset directory(ies)")
        print("  could not be checked, and a verdict over the rest would read as a")
        print("  verdict over all of them.")
        return 2

    for asset in REDISTRIBUTED_ENGINE_ASSETS:
        directory = ENGINE / asset.path
        if not directory.is_dir():
            problems.append(
                f"  {asset.path}\n"
                f"      is declared as redistributed by this binary ({asset.why})\n"
                f"      and does not exist in the engine tree. Either it moved — in\n"
                f"      which case this gate's declaration is now pointing at\n"
                f"      nothing and checking nothing — or the declaration is stale."
            )
            continue
        scanned += 1
        total_files += len(_shipped_files(directory))
        problems.extend(
            check_directory(directory, asset.path, about, in_app, context=f"engine, {asset.how}")
        )

    # --- the notice ships, and is not stale -------------------------------
    problems.extend(check_packaging(about, notice))

    if problems:
        print("shipped-assets: redistributed files with no recorded licensing.\n")
        print("\n".join(problems))
        print(
            f"\n  {_NOTICE} is generated by cargo-about from Cargo.lock and\n"
            "  CANNOT cover non-Cargo files. This gate is the only thing that does."
        )
        return 1

    print(
        f"shipped-assets: clean — {scanned} asset directory(ies) "
        f"({len(REDISTRIBUTED_ENGINE_ASSETS)} of them in the engine tree), "
        f"{total_files} redistributed file(s), all with recorded licensing;\n"
        f"                {_NOTICE} is in the package payload and matches "
        f"{_ABOUT_TEMPLATE}."
    )
    return 0


if __name__ == "__main__":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except AttributeError:
        pass
    sys.exit(self_test() if "--self-test" in sys.argv[1:] else main())
