#!/usr/bin/env python3
"""Build the pdfcer-gui portable distribution into ``D:\\builds``.

★★★ PUBLISH ONLY WHAT AN OPERATOR WOULD NOTICE — MEASURED 2026-08-26
===================================================================

**Each mirror to OneDrive costs the machine roughly 27,000 kernel handles, and
OneDrive does not give them back.**

Measured, with a control, because the first version of this claim was two data
points and a correlation:

    349,214 handles -> 404,185   over ~2 hours, TWO publishes   (+55,000)
    404,179 handles -> 404,185   over 32 minutes, NO publish    (+6)

Four orders of magnitude apart. The leak tracks this script's mirror step, not
the passage of time.

WHAT IT BREAKS, AND WHY IT LOOKS UNRELATED
-------------------------------------------
Handles are the resource Windows needs to CREATE A WINDOW. Past a threshold,
`accesskit_windows` panics while installing a window's accessibility subclass:

    HRESULT(0x80070008) "Not enough memory resources are available"

`pdfcer-gui` then dies before showing anything, with a message about *memory* on
a machine with plenty of it — measured at 404,179 handles against a **15 MB**
working set. It is a handle exhaustion wearing a memory error's clothes, which
is why nobody would connect it to a packaging script.

The effect is intermittent and therefore easy to misread as flakiness: at this
level, one launch in three fails. It also blocked a third of `ui-verify`'s
checks from starting at all, which is how it was found.

THE RULE
--------
**Publish when there is something an operator would notice.** A fix they can
feel, a feature they asked for, a rendering change. NOT:

  - a documentation or comment change
  - a test added or a harness improved
  - an engine re-pin with no behavioural difference
  - a refactor, however satisfying

Those are commits, and the commit is the record. A build in `OneDrive\` is a
thing the operator *runs*, and mirroring one costs his machine real resources
that are not returned until OneDrive restarts.

★ Stopping does not undo what has leaked. The count stays where it is; only a
OneDrive restart clears it. So the rule is about not making it worse, and the
already-accumulated total is the operator's to clear.

WHY THIS EXISTS
===============

Operator request, 2026-08-13: *"When complete compile integrated with
pdfcer in d:\\builds as a single exe like pdfcer does. ... Basically I want
this to get to where I can use it to replace acrobat reader first."*

"Integrated with pdfcer" needed no fold-in, and that is the single most
important fact about this script. `crates/pdfcer-gui` depends on
`pdfcer-core`, `pdfcer-render` and `pdfcer-print` from `D:\\Dev\\pdfcer`, and
Rust links them **statically**. So `cargo build --release -p pdfcer-gui` in
THIS workspace already produces one self-contained executable carrying
pdfcer's engine — the integration the request asks for is a property of
the dependency graph, not a merge that has to happen first.

★ The FORM of that dependency has changed twice and this docstring has
been wrong after each change, which is why it now says as little about it
as possible: read `crates/pdfcer-gui/Cargo.toml`, which carries the
argument. In one line: it was a path, then a GitHub revision pin
(2026-08-14), and is now `git = "file:///D:/Dev/pdfcer", branch = "main"`
(2026-08-17). **The static-linking property above held under all three**
and is the only part this script depends on.

What DOES depend on the form is how the engine is identified — see
`locked_engine_rev`, which reads `Cargo.lock` rather than the engine
tree's HEAD, because a git dependency compiles a committed revision out
of cargo's cache and the tree can be both dirty and ahead of it.

That matters because the alternative reading — fold the new shell into
`D:\\Dev\\pdfcer` and package from there — would have shipped a REGRESSION
when this script was written. That is no longer the reason it is wrong,
and the change is worth recording rather than quietly deleting: measure,
redaction, the settings dialog and text editing have all since landed
HERE. Fold-in is now a scheduling decision under PROJECT_PLAN.md §7
rather than a thing that would cost four capabilities, and shipping from
here still costs nothing and keeps the old build installable beside it.

WHAT IT PRODUCES
================

``D:\\builds\\pdfcergui-<YYYYMMDD-HHMM>-<engine>-<shell>[-dirty-<digest>]\\``

where ``<engine>`` is the revision **`Cargo.lock` says was linked**, not
the engine tree's HEAD — see `locked_engine_rev`.

    pdfcer-gui.exe            the new shell, with pdfcer's engine linked in
    LICENSE                  MIT
    THIRD_PARTY_LICENSES.md  generated by cargo-about, never hand-edited
    MANUAL.md                the USER MANUAL — the one document written for
                             somebody who wants to use pdfcer rather than build it
    README.md                the project README
    FEATURES.md              what works today and what does not
    BUILD-INFO.txt           identity, verification state, what to try

`THIRD_PARTY_LICENSES.md` is not a courtesy. `pdfcer-gui.exe` links
`pdfcer-core` and `pdfcer-render` statically, and those crates embed
third-party font faces and data tables with `include_bytes!` — so the
binary redistributes work whose licences require their notices to travel
with it. `cargo-about` covers the Cargo crates; the template's
hand-written epilogue covers the rest. See
`tools/gates/check-shipped-assets.py`, which fails if this file is not in
`PAYLOAD_DOCS` or has drifted from `about.hbs`.

The same attributions are reachable inside the program at
File ▸ pdfcer ▸ About pdfcer, because a GUI operator who launched from a
shortcut may never open this folder.

`FEATURES.md` ships deliberately. The operator's constraint on the
pdfcer builds was *"so I can try it out while you are working"*, and
"try it out" is answerable only if the operator knows what is finished.
Here that matters more than it did there, because this build is a shell
mid-rebuild: without the feature list, a missing Measure tab reads as a
bug rather than as a row that is not ticked yet.

``userdata/`` is deliberately NOT created, for the same reason as pdfcer's
packager: the app makes it at first run, so "replace the folder" stays a
safe update procedure precisely because payload and state are
distinguishable.

TWO IDENTITIES, BECAUSE THERE ARE TWO SOURCES
=============================================

pdfcer's packager names a build after one commit. This one cannot, and
the difference is not cosmetic — **this binary is built from two trees**:

* the **engine**, `D:\\Dev\\pdfcer`, which another session edits live; and
* the **shell**, this workspace.

Both are now git repositories (this one since `2a504ef`, 2026-08-13), so
the name carries a short HEAD for each: ``<engine>-<shell>``.

`source_digest()` survives that, and the reason is specific to how this
project works. Commits here are taken at milestones while **several
agents write concurrently**, so the working tree is dirty far more often
than not — and for a dirty tree the commit hash names the last
checkpoint, not what was compiled. The digest names what was compiled.
It cannot say *what* the code was, only whether two builds were built
from identical bytes, but that is the question a bug report actually
asks: *"is this the build I was running?"*

So they answer different questions and both are recorded. The commit
goes in the folder name; the digest goes in `BUILD-INFO.txt`, and is
appended to the name too when the shell tree is dirty, because that is
exactly the case where the commit alone is not an identity.

★ THE `-enginedirty` SUFFIX IS GONE — REMOVED 2026-08-17
========================================================

It used to read *"load-bearing"*, and under a **path** dependency it was:
`D:\\Dev\\pdfcer` is read-only to this project but not to its own session,
so the engine tree moved underneath builds, and a path build compiles
that tree. If it carried uncommitted changes under `crates/`, the linked
engine was not the commit in the folder name.

The dependency is now `git = "file://…", branch = "main"`. Cargo builds a
committed revision out of `~/.cargo/git/`, so **the engine's working tree
is not compiled at all** and a suffix claiming it was would be false.

The removal is recorded rather than done quietly, because it demonstrates
the thing the old text was itself warning about. The narrow-test argument
it made — *"changes under `docs/`, `fixtures/` and `.claude/` cannot reach
a compiler … a warning that fires when nothing is wrong is one that gets
ignored when something is"* — was right, and the suffix became exactly
that kind of warning the moment the dependency form changed underneath it.
**A guard is only as valid as the mechanism it was reasoned about.**

Two things replace it, and neither is a claim about the payload:

* the engine tree's state is REPORTED in `BUILD-INFO.txt` as context;
* the engine being **ahead of the locked revision** is warned about, in
  `BUILD-INFO.txt` and on the console, with the `cargo update` line. That
  is the condition that actually cost something — a stale pin left the
  shell eight commits behind an image-decoding fix, and the old shell
  rendered a file correctly while this one did not.

THE NAME MUST NOT START WITH ``pdfcer-``
=======================================

`D:\\Dev\\pdfcer\\tools\\package-portable.py` finds its previous build with
``dest.glob("pdfcer-*")`` and reads that folder's `BUILD-INFO.txt` to pick
the commit its changelog diffs against. A build of THIS project named
`pdfcer-gui-2026...` would match that glob, and pdfcer's next package would
diff its history against a commit hash belonging to a different tree —
producing a silently wrong changelog in a file whose entire purpose is to
tell the operator what changed.

`pdfcergui-` does not match `pdfcer-*` (the glob needs a literal hyphen at
that position). One absent hyphen is the whole safeguard, and a safeguard
that thin cannot rest on a reader noticing it — so ``--self-test``
asserts it against a real temporary directory and pdfcer's own glob
string, following the self-test convention `tools/gates/check-ui-strings.sh`
established in this project after a gate shipped that could not catch its
own bug.

EXIT CODES
==========

``0`` build written; ``1`` a prerequisite is missing (no cargo, no engine
tree, no binary after a build attempt, or `--verify` failed); ``2`` the
destination exists and is non-empty, which should be impossible given the
timestamp and means something else is writing there.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import shutil
import stat
import subprocess
import sys
from datetime import datetime
from pathlib import Path

# Windows consoles default to a code page that cannot encode this file's
# arrows and dashes; see the same block in pdfcer's packager and in the
# Python gates.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

REPO = Path(__file__).resolve().parent.parent
ENGINE = Path("D:/Dev/pdfcer")

#: The engine crates this workspace takes from :data:`ENGINE`, refreshed
#: before every build.
#:
#: All three are named explicitly rather than running a bare `cargo update`,
#: which would also move every crates.io dependency in the lockfile. Those are
#: pinned to match `D:\Dev\pdfcer`'s own lockfile — the workspace root's rule
#: is that a crate this project adds which is NOT already in pdfcer's lockfile
#: is an operator decision — so bumping them as a side effect of a build would
#: quietly break that property and would do it in the one command nobody reads
#: the output of.
ENGINE_CRATES = ["pdfcer-core", "pdfcer-render", "pdfcer-print"]

#: Where a finished build is mirrored so it syncs to the operator's other
#: machines.
#:
#: Operator instruction, 2026-08-17: *"can you put the last latest 2 builds on
#: my onedrive? just put them in a folder called pdfcer-gui1 and pdfcer-gui2 and
#: rotate the latest build between them."*
MIRROR_ROOT = Path("C:/Users/Ken/OneDrive")

#: The two mirror slots, rotated so the newest build replaces the OLDER one.
#:
#: ★ Two rather than one, and the reason is the whole point of the request: the
#: previous build stays reachable. This shell is mid-rebuild and every release
#: can regress something — the operator's own report that started this week was
#: exactly that. A single mirrored folder would overwrite the last known-good
#: build with the one that broke, on a drive that then syncs the loss to every
#: other machine.
#:
#: ★ Rotation is decided by MTIME, not by a counter in a file. A counter is
#: state that can disagree with the directory it describes — deleted by hand,
#: lost on a fresh machine, or written by a run that then failed to copy. The
#: directories' own timestamps cannot drift from the directories, so the rule
#: "replace whichever slot is older" is derivable from the mirror itself and
#: needs nothing remembered. An empty or missing slot is treated as infinitely
#: old, so the first two builds fill both slots before anything is overwritten.
MIRROR_SLOTS = ["pdfcer-gui1", "pdfcer-gui2"]
DEFAULT_DEST = Path("D:/builds")

#: Payload files copied verbatim from the repo root, in the order they are
#: listed in `BUILD-INFO.txt`. Deliberate rather than alphabetical: licence
#: first, then the third-party notice that belongs beside it, then the two
#: documents an operator opens.
#:
#: ★ `THIRD_PARTY_LICENSES.md` joined this list on 2026-08-14 and is not
#: optional. It is generated by `cargo-about` from `Cargo.lock`, and its
#: hand-written epilogue carries the licences of the data and font assets the
#: engine embeds — assets `cargo-about` cannot see and that ship inside
#: `pdfcer-gui.exe` regardless. A notice file that exists in the repository and
#: not in this list reaches nobody, and looks exactly like one that does, so
#: `tools/gates/check-shipped-assets.py` reads THIS LIST and fails if the
#: notice is missing from it.
# ★ `MANUAL.md` FIRST, because it is the only one written FOR the operator.
#
# The others are an engineering README, a capability sheet and two licence
# files. A folder whose most approachable document is a project README —
# opening "the GUI rebuild for D:\Dev\pdfcer" — tells somebody who just wants
# to print a drawing that they have the wrong folder.
PAYLOAD_DOCS = [
    "MANUAL.md",
    "LICENSE",
    "THIRD_PARTY_LICENSES.md",
    "README.md",
    "FEATURES.md",
]

#: Asset directories copied WHOLE into the portable folder, as
#: `(source relative to the ENGINE tree, destination relative to the package)`.
#:
#: ★ ONE ENTRY, ADDED 2026-08-14 WITH THE OCR FEATURE.
#:
#: Some assets cannot be linked into the executable and have to travel beside
#: it as loose files. The `ocrs` OCR model weights are that case:
#: `pdfcer_core::ocr::models::resolve_model_dir` looks for a `models/<engine>`
#: directory beside the running executable, so `pdfcer-gui.exe` can only find
#: them if the packager put them there. They are not `include_bytes!`d by any
#: crate and cannot be — twelve megabytes compiled into the binary would be
#: paid by every operator whether or not they ever OCR anything, and would put
#: a CC-BY-SA-4.0 work inside an artifact whose licence file says MIT with no
#: way for a recipient to separate the two.
#:
#: WHAT THE ENTRY BELOW SHIPS: 12,240,008 bytes over two `.rten` files —
#: `text-detection.rten` (2,523,564 B) and `text-rec-checkpoint.rten`
#: (9,716,444 B) — by **Robert Knight**, from
#: <https://huggingface.co/robertknight/ocrs>, licensed **CC-BY-SA-4.0**,
#: BYTE-IDENTICAL to the upstream artifacts (only the filenames are shortened,
#: upstream carrying a content-addressed suffix). Every one of those facts is
#: recorded, with per-file SHA-256 hashes, in that directory's own
#: `PROVENANCE.md` in the engine tree, and none of them should be restated
#: from memory anywhere: there is **no version number**, so the hash is the
#: identity.
#:
#: The operator accepted them into this MIT package on 2026-08-14 —
#: *"yes ship that model in the mit repo with proper credit."*
#:
#: ★ THE COUPLING, WHICH IS THE POINT AND NOT AN OBSTACLE.
#: `tools/gates/check-shipped-assets.py` cross-checks this list against its own
#: register of redistributed engine assets, so this line cannot exist alone:
#: the gate fails until `about.hbs` (the notice that ships) and
#: `crates/pdfcer-gui/src/text/about.rs` (the About dialog) both carry the
#: attribution, and it fails in the other direction too if the source
#: directory ever disappears from the engine tree. Without this list the copy
#: would have arrived as an inline `shutil.copytree` somewhere in `main`,
#: invisible to any gate — which is precisely how an obligation goes missing
#: without anyone deciding to drop it.
#:
#: `copy_asset_dirs` drops `PROVENANCE.md` on the way in, deliberately: the
#: operator's copy of that information is `THIRD_PARTY_LICENSES.md` at the top
#: level, and two licence records in one package are two things to keep in
#: step.
#:
#: Sources are in the ENGINE tree because that is where the assets are
#: maintained; this project holds `D:\\Dev\\pdfcer` READ-ONLY and only ever
#: copies out of it.
import sys as _sys
_sys.path.insert(0, str(Path(__file__).resolve().parent))
import engine_path as _engine_path  # noqa: E402

PAYLOAD_ASSET_DIRS: list[tuple[str, str]] = [
    # ★★ DERIVED, not written out. Under the temporary rename shim the engine's
    # crate directory still carries its old name, and a literal here would have
    # named a directory that does not exist — so the packager would have found
    # nothing to copy and shipped a portable build with NO OCR MODELS, silently.
    # `tools/engine_path.py` carries the argument; it reads the manifest Cargo
    # actually builds from, so this follows the engine's rename by itself.
    (f"crates/{_engine_path.crate_name('core')}/assets/models/ocrs", "models/ocrs"),
]

#: The one shipped binary. Unlike pdfcer's packager there is no CLI here:
#: `pdfcer` is a member of the ENGINE workspace, and building it would
#: mean invoking cargo inside `D:\Dev\pdfcer` — a write to a tree this
#: project holds read-only (it would create/refresh `target/`). Operators
#: who want the CLI take it from a pdfcer build, which is where it is
#: maintained.
BINARIES = ["pdfcer-gui.exe"]

#: Prefixes under the ENGINE tree that can reach a compiler. Generous on
#: purpose: under-reporting here produces the false reassurance the
#: `-enginedirty` suffix exists to prevent, while over-reporting costs
#: only an unnecessary suffix.
BUILD_AFFECTING = (
    "crates/",
    "Cargo.toml",
    "Cargo.lock",
    "rust-toolchain",
    ".cargo/",
    "build.rs",
)

#: What `source_digest()` hashes. Mirrors BUILD_AFFECTING for this tree.
#: `tools/` is EXCLUDED — this file lives there, and a packager edit is
#: not a change to the shipped program. `tools/ui-verify` is a workspace
#: member but produces no shipped artifact.
SOURCE_GLOBS = ("crates/**/*.rs", "crates/**/Cargo.toml")
SOURCE_FILES = ("Cargo.toml", "Cargo.lock")


def git(*args: str, cwd: Path = ENGINE) -> str:
    """Run a git command in `cwd` and return its stripped stdout.

    Defaults to the ENGINE tree because that is the identity most calls
    below want; pass `cwd=REPO` for the shell's own repository.

    `encoding="utf-8"` is not optional, and the reason is recorded in
    pdfcer's packager: `text=True` alone decodes with the LOCALE codec,
    cp1252 on this machine, and pdfcer's commit subjects are full of
    em-dashes — so a changelog rendered `Pass 54.1 â€” a group can be
    deleted`. `errors="replace"` so a stray non-UTF-8 byte in some future
    commit degrades one character instead of failing a build.
    """
    return subprocess.run(
        ["git", *args],
        cwd=cwd,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        check=False,
    ).stdout.strip()


def locked_engine_rev(repo: Path) -> str | None:
    """The engine revision `Cargo.lock` says this build actually links.

    **This, not the engine tree's HEAD, is the engine's identity.** The
    distinction became real on 2026-08-17, when `pdfcer-gui` moved from a
    path dependency to `git = "file:///D:/Dev/pdfcer", branch = "main"`: a
    path dependency compiles the working tree, a git dependency compiles a
    committed revision out of `~/.cargo/git/`, and the two can differ by
    any number of commits plus whatever is uncommitted.

    `Cargo.lock` is the only artefact that records what was compiled, and
    it moves only on `cargo update`. So committing in the engine — or
    editing it, or checking out another branch — does not change this
    build, and reading HEAD would credit the binary with commits it does
    not contain.

    Parsed with a regex rather than a TOML library on purpose: this script
    has no third-party dependencies and gains none for one line. The shape
    it matches is Cargo's own and is stable —

        [[package]]
        name = "pdfcer-core"
        version = "0.5.3"
        source = "git+file:///D:/Dev/pdfcer?branch=main#13456637..."

    Returns `None` rather than raising when the lock has no such entry,
    which is the state a **path** dependency produces (path deps record no
    `source` at all). The caller reports "unknown" and the build still
    happens: refusing to package because an identity could not be read
    would be this script deciding it knows better than the operator who
    ran it.
    """
    lock = repo / "Cargo.lock"
    if not lock.is_file():
        return None
    text = lock.read_text(encoding="utf-8", errors="replace")
    # Non-greedy across the entry so `name` and `source` are matched within
    # the SAME `[[package]]` block. A greedy match would happily pair
    # `pdfcer-core`'s name with some later package's source.
    match = re.search(
        r'\[\[package\]\]\s*\nname = "pdfcer-core"\n.*?source = "git\+[^"]*#([0-9a-f]{7,40})"',
        text,
        re.DOTALL,
    )
    return match.group(1) if match else None


def source_digest(repo: Path) -> str:
    """A 12-hex digest identifying this workspace's build-affecting source.

    Stands in for the commit hash this project does not have. The contract
    is narrow and worth stating exactly, because a digest invites more
    trust than it earns: **identical digests mean identical source; a
    different digest means the source differs, somewhere.** It cannot say
    what differs, and it is not a version — 12 hex digits sort
    meaninglessly.

    Determinism is the whole value, so both inputs are normalised:

    * **Paths** are relative and forward-slashed, so the digest does not
      change if the workspace is moved or built from a different shell.
    * **Order** is sorted by that relative path, because `Path.glob` order
      is filesystem-dependent — the same tree on a different volume would
      otherwise digest differently.

    The path is hashed alongside the bytes so that RENAMING a file changes
    the digest. Hashing contents alone would call a rename a no-op, and a
    rename absolutely changes the program.
    """
    h = hashlib.sha256()
    paths: set[Path] = set()
    for pattern in SOURCE_GLOBS:
        paths.update(p for p in repo.glob(pattern) if p.is_file())
    for name in SOURCE_FILES:
        p = repo / name
        if p.is_file():
            paths.add(p)
    for p in sorted(paths, key=lambda q: q.relative_to(repo).as_posix()):
        h.update(p.relative_to(repo).as_posix().encode("utf-8"))
        h.update(b"\0")
        h.update(p.read_bytes())
    return h.hexdigest()[:12]


def path_of(line: str) -> str:
    """The path out of one `git status --porcelain` line.

    `XY <path>`, or `XY <old> -> <new>` for a rename; the destination is
    what exists on disk now.

    Parsed with a regex rather than `line[3:]`, and the reason is a bug
    pdfcer's packager hit: the status field is two columns and EITHER may
    be a space, while `git()` strips its output — which removes the
    leading space from the first line only. A fixed offset therefore ate
    one character of exactly one path per run, printing
    `claude/agent-memory/...` for `.claude/...`. One wrong entry in a list
    of correct ones is the worst version of this bug: the list looks
    right, so the reader trusts the entry that is not, and a path that
    does not exist reads as a deleted file rather than as a parse error.
    """
    m = re.match(r"^\s*\S{1,2}\s+(.*)$", line)
    if not m:
        return ""
    return m.group(1).split(" -> ")[-1].strip().strip('"')


def previous_build(dest: Path) -> tuple[str, str, str] | None:
    """`(engine_commit, shell_commit, source_digest)` of the most recent
    build of THIS project in `dest`, or `None`.

    `shell_commit` is `""` for builds packaged before this workspace was
    put under git (2026-08-13), whose `BUILD-INFO.txt` has no `Shell:`
    line. Callers must treat it as "no baseline" rather than as a ref —
    which is why the changelog below verifies every ref it is handed.

    Read out of that build's own `BUILD-INFO.txt` rather than parsed from
    the folder name: the name is for humans and can be renamed, the file
    is the record.

    The glob is `pdfcergui-*`, which excludes pdfcer's own builds. Reading
    one of those would produce a changelog diffing this tree's history
    against a commit from a build of a different program.
    """
    builds = sorted(
        (p for p in dest.glob("pdfcergui-*") if p.is_dir()),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    for b in builds:
        info = b / "BUILD-INFO.txt"
        if not info.is_file():
            continue
        engine = shell = src = ""
        for line in info.read_text(encoding="utf-8", errors="replace").splitlines():
            # `Shell source digest:` is matched BEFORE `Shell:` — the
            # latter is a prefix of nothing here, but `startswith` order
            # is the kind of thing that quietly stops being true when a
            # label is renamed, so the specific one goes first.
            if line.startswith("Shell source digest:"):
                src = line.split(":", 1)[1].strip().split()[0]
            elif line.startswith("Engine:"):
                engine = line.split(":", 1)[1].strip().split()[0]
            elif line.startswith("Shell:"):
                shell = line.split(":", 1)[1].strip().split()[0]
        if engine:
            return engine, shell, src
    return None


def copy_asset_dirs(out: Path, engine: Path) -> tuple[list[str], list[str]]:
    """Copy every `PAYLOAD_ASSET_DIRS` entry into the package.

    Returns `(copied, missing)` — destination paths that were written, and
    source paths that were declared and are not there.

    `engine` is a parameter rather than the module constant so `--self-test`
    can exercise this against a synthetic tree. That matters more than it
    looks: this list is empty today, so without a self-test the copy loop
    would ship **never having run once**, and the first time it did would be
    the day someone added a 12 MB licensed asset to a release. A code path
    that has never executed is not code that works; it is code that compiles.

    `dirs_exist_ok=False` on purpose. The destination is a folder this run
    just created under a timestamped name, so an existing directory there
    means something else is writing into the same package, and merging two
    writers' asset trees would produce a folder neither of them intended.
    """
    copied: list[str] = []
    missing: list[str] = []
    for source, dest in PAYLOAD_ASSET_DIRS:
        src = engine / source
        if not src.is_dir():
            missing.append(source)
            continue
        target = out / dest
        target.parent.mkdir(parents=True, exist_ok=True)
        # `ignore` drops the provenance note: it documents the asset for a
        # reader of the SOURCE TREE, and the operator's copy of that
        # information is `THIRD_PARTY_LICENSES.md`, which ships at the top
        # level where they will actually find it. Copying it here as well
        # would put a second, differently-worded licence record inside a data
        # folder — and two records are two things to keep in step.
        shutil.copytree(src, target, ignore=shutil.ignore_patterns("PROVENANCE.md"))
        copied.append(dest)
    return copied, missing


def run_verification(repo: Path) -> tuple[bool, str]:
    """Run the test suite and the CI gates; return `(ok, report)`.

    Opt-in via `--verify` rather than always-on, because a full workspace
    test run is minutes and the common case is packaging a build the
    session just verified.

    But when it is NOT run, `BUILD-INFO.txt` says so in those words. An
    omitted verification line would read as "nothing to report", which is
    the opposite of the truth: it means nobody checked. This project's
    whole verification stance is that a passing test is not evidence an
    operator can reach a feature (`FEATURES.md`), so a build that quietly
    implies it was verified is exactly the wrong artifact to ship.
    """
    # The spawned shell may not inherit cargo's directory.
    #
    # `tools/gates/run-all.sh` runs `cargo fmt` and `cargo clippy`. A bash
    # spawned from here is neither a login nor an interactive shell, so it
    # never reads the profile that puts `~/.cargo/bin` on PATH — and the gate
    # runner then SKIPs both, which makes it exit 3, which fails `--verify`
    # while every gate that actually ran was clean.
    #
    # ★ Honest provenance, because the next reader deserves it: this was
    # OBSERVED under a nested, sandboxed shell where `python` and `rustc`
    # were invisible too, so the sandbox — not the profile — was that
    # instance's cause, and this prepend did NOT fix it there. It is kept
    # because the non-login-shell case is real, independent, and costs two
    # lines. It has not been verified against that case.
    #
    # The half that WAS verified and fixed is `run-all.sh`'s message: it
    # reported `cargo: command not found` as "the workspace does not
    # currently load", which was flatly false and pointed the reader at the
    # one place the problem was not.
    env = os.environ.copy()
    cargo = shutil.which("cargo")
    if cargo:
        env["PATH"] = str(Path(cargo).parent) + os.pathsep + env.get("PATH", "")

    lines = []
    ok = True
    for label, cmd in (
        ("tests", ["cargo", "test", "--workspace", "--quiet"]),
        ("gates", [_bash(), "tools/gates/run-all.sh"]),
    ):
        print(f"package-portable: {label} ...")
        r = subprocess.run(
            cmd,
            cwd=repo,
            env=env,
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            check=False,
        )
        passed = r.returncode == 0
        ok = ok and passed
        tail = (r.stdout or r.stderr or "").strip().splitlines()[-3:]
        lines.append(f"  {label}: {'PASS' if passed else 'FAIL'}")
        lines.extend(f"    {t}" for t in tail)
    return ok, "\n".join(lines)


def self_test() -> int:
    """Assert the two invariants that are otherwise invisible.

    Both are properties nothing else would catch. A wrong folder name
    still packages successfully and still runs; the damage lands in a
    DIFFERENT project's changelog, days later. A non-deterministic digest
    still produces a name; it just quietly stops answering the one
    question it exists to answer. Neither failure mode announces itself,
    which is precisely why they are asserted rather than reasoned about.
    """
    import tempfile

    failures: list[str] = []

    # 1. The name must not be picked up by pdfcer's own packager. Asserted
    #    against a real directory and pdfcer's literal glob string, not by
    #    comparing prefixes — the whole point is to test the thing that
    #    actually runs over there.
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        (root / "pdfcergui-20260813-1200-abc1234-0123456789ab").mkdir()
        (root / "pdfcer-20260813-1200-abc1234").mkdir()
        caught = sorted(p.name for p in root.glob("pdfcer-*") if p.is_dir())
        if caught != ["pdfcer-20260813-1200-abc1234"]:
            failures.append(
                "a pdfcer-gui build name matches pdfcer's `pdfcer-*` glob; "
                f"its packager would read {caught} as its own previous build"
            )
        mine = sorted(p.name for p in root.glob("pdfcergui-*") if p.is_dir())
        if len(mine) != 1:
            failures.append(f"`pdfcergui-*` did not match exactly this project's build: {mine}")

    # 2. The digest must be stable across repeated calls on an unchanged
    #    tree, and must move when a byte does. Run against the real
    #    workspace, because a synthetic tree would not exercise the glob
    #    patterns that decide what is hashed in the first place.
    a = source_digest(REPO)
    b = source_digest(REPO)
    if a != b:
        failures.append(f"source_digest is not deterministic: {a} != {b}")
    if len(a) != 12:
        failures.append(f"source_digest returned {len(a)} chars, expected 12")
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        (root / "crates" / "x" / "src").mkdir(parents=True)
        f = root / "crates" / "x" / "src" / "lib.rs"
        f.write_text("fn a() {}", encoding="utf-8")
        before = source_digest(root)
        f.write_text("fn b() {}", encoding="utf-8")
        if source_digest(root) == before:
            failures.append("source_digest did not change when a source byte changed")
        f.rename(root / "crates" / "x" / "src" / "renamed.rs")
        if source_digest(root) == before:
            pass  # already differs; the rename check below is the real one
        moved = source_digest(root)
        (root / "crates" / "x" / "src" / "renamed.rs").rename(f)
        if source_digest(root) == moved:
            failures.append("source_digest ignored a rename; it must hash paths too")

    # 3. The asset-directory copy works, and reports a missing source rather
    #    than skipping it.
    #
    #    ★ This exists because `PAYLOAD_ASSET_DIRS` is EMPTY. An empty list
    #    means `copy_asset_dirs` never runs in a real package, so without this
    #    the first execution of that loop would be the day somebody added a
    #    12 MB licensed asset to a release — which is the worst possible day
    #    to discover a typo in a `copytree` call. The engine tree is
    #    synthesised here rather than read, so the test neither touches
    #    `D:\\Dev\\pdfcer` nor depends on it being mounted.
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        engine = root / "engine"
        (engine / "crates" / "demo" / "assets" / "models").mkdir(parents=True)
        weights = engine / "crates" / "demo" / "assets" / "models" / "weights.bin"
        weights.write_bytes(b"\x01\x02\x03")
        (engine / "crates" / "demo" / "assets" / "models" / "PROVENANCE.md").write_text(
            "terms", encoding="utf-8"
        )
        out = root / "package"
        out.mkdir()

        global PAYLOAD_ASSET_DIRS  # noqa: PLW0603 — restored below
        saved = PAYLOAD_ASSET_DIRS
        try:
            PAYLOAD_ASSET_DIRS = [("crates/demo/assets/models", "models/demo")]
            copied, missing = copy_asset_dirs(out, engine)
            if missing:
                failures.append(f"copy_asset_dirs reported a present source as missing: {missing}")
            if copied != ["models/demo"]:
                failures.append(f"copy_asset_dirs copied {copied}, expected ['models/demo']")
            if not (out / "models" / "demo" / "weights.bin").is_file():
                failures.append("copy_asset_dirs did not write the asset into the package")
            if (out / "models" / "demo" / "PROVENANCE.md").exists():
                failures.append(
                    "copy_asset_dirs shipped PROVENANCE.md — the operator's copy of that "
                    "information is THIRD_PARTY_LICENSES.md at the top level"
                )

            PAYLOAD_ASSET_DIRS = [("crates/demo/assets/gone", "models/gone")]
            _copied, missing = copy_asset_dirs(root / "package2", engine)
            if missing != ["crates/demo/assets/gone"]:
                failures.append(
                    "a declared asset directory that does not exist was NOT reported; "
                    "the package would have shipped an attribution for absent files"
                )
        finally:
            PAYLOAD_ASSET_DIRS = saved

    for msg in failures:
        print(f"package-portable --self-test: FAIL — {msg}")
    if failures:
        return 1
    print(
        "package-portable --self-test: 3 invariants hold "
        "(name collision, digest, asset copy)."
    )
    return 0


def _bash() -> str:
    """The bash to run the gates with, **by absolute path**.

    # ★★ This is the real cause of a quirk this project has documented and
    # worked around since it started

    `HANDOFF.md` §7 has carried a note for weeks: *"`--verify` may report the
    gates as skipped because a spawned bash does not inherit `~/.cargo/bin`."*
    The workaround was to run the gates by hand and state the result in
    `--note`. The diagnosis was wrong, and no amount of PATH manipulation was
    ever going to fix it.

    `subprocess.run(["bash", ...])` does not resolve `bash` the way this
    machine's shell does. Windows `CreateProcess` searches its own PATH and
    finds **`C:\Windows\System32\bash.exe` — the WSL launcher** — before Git
    Bash. Asked what it sees, that interpreter reports:

    ```text
    PATH_HEAD=/usr/local/sbin:/usr/local/bin:...:/usr/lib/wsl/lib:/mnt/c/Users/K
    type -p cargo -> NOTFOUND
    ```

    A Linux PATH. Windows `cargo.exe` is not on it under that name and never
    will be, so prepending `~/.cargo/bin` — which the caller does, and which
    its own comment already admitted "did NOT fix it" where it was observed —
    could not have worked.

    It also explains the *other* symptom, which looked unrelated: WSL bash
    refuses a script with CRLF line endings (`cd: $'\r': No such file or
    directory`), while Git Bash tolerates it. Two scripts had drifted to CRLF
    despite `.gitattributes` pinning `*.sh text eol=lf`, so `--verify` failed
    with a line-ending error that the same file ran fine under by hand. One
    root cause, two unrecognisable symptoms.

    `shutil.which` uses Python's own resolution and returns Git Bash here.
    Passing its absolute path removes the ambiguity entirely.

    Falls back to the bare name if `which` finds nothing, so a machine with a
    differently-installed bash still gets an attempt rather than a crash — and
    on such a machine the gates' own SKIPPED reasons are the honest report.
    """
    return shutil.which("bash") or "bash"


#: How many dated build folders to keep in ``D:\\builds``.
#:
#: **Three, and the number is chosen rather than round.** The two OneDrive slots
#: hold the current build and the fallback; a third keeps the one before those,
#: which is what a reader needs when a defect turns out to be two builds old and
#: the question is *when did this start*.
#:
#: Older folders are pure history: the exe is superseded, the `BUILD-INFO.txt`
#: naming its revisions is reproducible from git, and nothing links to them.
KEEP_BUILDS = 3


def _force_writable(func, path: str, _exc: object) -> None:
    """``shutil.rmtree`` error handler: clear the read-only bit and retry once.

    ★ **Why this is needed, found on 2026-08-27.** The first prune refused with
    ``[WinError 5] Access is denied`` on ``models\\ocrs`` — the recognition
    weights are copied out of a payload directory whose files carry the
    read-only attribute, and ``DeleteFile`` honours it. On Windows that
    attribute is a property of the *file*, not a permission, so the fix is to
    clear it rather than to elevate anything.

    ★★ It retries **once** and lets a second failure propagate. A handler that
    kept trying would turn "a sync client has this folder open" — the ordinary
    reason a delete fails here — into a hang inside a build script, and the
    caller already treats a failure to prune as a nuisance rather than as a
    reason to fail a build that has been written and mirrored.
    """
    import stat

    try:
        os.chmod(path, stat.S_IWRITE)
        func(path)
    except OSError:
        raise


def prune(dest: Path, keep: int) -> None:
    """Delete superseded ``pdfcergui-*`` build folders, keeping the newest *keep*.

    ★ **Why this exists.** The operator, 2026-08-27: *"all this compiling has
    filled the drive with temporary files. you'll have to clean yours up."*
    ``D:\builds`` held **39** of these, 1.27 GB, because this script had written
    one on every keeper build since 2026-08-13 and never removed one. On a
    volume at 97 % that is not a rounding error, and it is entirely this
    script's doing.

    ★★ **It touches only its own folders.** ``D:\builds`` is shared — ScripTree
    releases and the engine's own ``pdfcer-*`` packages live there too — so the
    filter is `pdfcergui-*` and nothing else is enumerated, let alone deleted. A
    cleanup that swept a sibling project's releases would be a far worse outcome
    than the disk being full.

    ★ **Newest by MODIFICATION TIME, not by name.** The folder name begins with
    a timestamp and sorting by it would usually agree — but `--slot` can rewrite
    an older build, a restored backup carries its original name, and a
    name-sorted deletion would then remove the one that was most recently
    verified. `mirror` already learned this exact lesson about the two OneDrive
    slots; the same reasoning applies to the same kind of decision here.

    A failure to delete is **not** fatal: a folder held open by Explorer or by a
    sync client is a nuisance, not a reason to fail a build that has already
    been written and mirrored. It is reported and the run continues.
    """
    folders = [d for d in dest.glob("pdfcergui-*") if d.is_dir()]
    if len(folders) <= keep:
        return
    folders.sort(key=lambda d: d.stat().st_mtime, reverse=True)
    removed = 0
    freed = 0
    for folder in folders[keep:]:
        size = sum(f.stat().st_size for f in folder.rglob("*") if f.is_file())
        try:
            # ★ `onerror` and not `onexc`. The newer keyword landed in Python
            # 3.12 and this machine runs **3.11.9**, where passing it is a
            # `TypeError` inside the handler-less path — i.e. the prune would
            # fail for a reason that has nothing to do with the folder. Caught
            # by checking `inspect.signature` rather than by assuming, after
            # writing `onexc` first. The two take the same three positional
            # arguments, so only the keyword differs.
            shutil.rmtree(folder, onerror=_force_writable)
        except OSError as error:
            print(f"package-portable: could not remove {folder.name}: {error}")
            continue
        removed += 1
        freed += size
    if removed:
        print(
            f"\npackage-portable: pruned {removed} superseded build(s), "
            f"{freed / 1_048_576:,.0f} MB — keeping the newest {keep}"
        )


def mirror(out: Path, forced: str | None = None) -> None:
    """**Copy a finished build into the older of the two OneDrive slots.**

    Called after the package is assembled and verified, so a failed run never
    replaces a good mirrored build with a broken one — the rotation only ever
    sees builds that were worth keeping.

    # ★ It replaces the OLDER slot, and that is the whole design

    The two slots exist so the previous build stays reachable. This shell is
    mid-rebuild; every release can regress something, and the operator report
    that started this week was exactly that. Overwriting the single most recent
    mirror would put the last known-good build under the one that broke — on a
    drive that then syncs the loss to every other machine.

    Which slot is older is read from **the build's own `Built:` stamp**, out of
    the `BUILD-INFO.txt` that build wrote. A missing or empty slot, or one whose
    stamp cannot be parsed, is treated as infinitely old — so the first two
    builds fill both slots before anything is overwritten, and an unreadable
    slot is replaced rather than trusted.

    # ★★ IT USED TO READ THE DIRECTORY'S MTIME, AND THAT WAS WRONG TWICE OVER

    The argument for mtime was good and the conclusion was not:

    > *"A counter is state that can disagree with the thing it describes:
    > deleted by hand, absent on a fresh machine, or written by a run that then
    > failed to copy. A directory's timestamp cannot drift from the directory."*

    True — and the wrong question. A directory's mtime describes **the
    directory**, and what the rotation needs is the age of **the build inside
    it**. Those are different facts, and two ordinary events separate them:

    1. **The operator RUNS the build from the slot.** pdfcer then creates
       `userdata/` beside the exe and writes their settings, dock layout and
       recent files into it. That bumps the slot's mtime to *now*, so the slot
       holding the older build looks like the newest — and the next package
       overwrites the good, newer one. **The two-slot guarantee is destroyed by
       the operator merely using the build**, which is what the slots are for.

    2. **A failed mirror bumps the slot it failed on.** Observed 2026-08-20 at
       19:59: `pdfcer-gui1` held the previous day's build and was correctly chosen
       as the target; OneDrive held it locked, the rename failed clean — and the
       attempt had already touched the directory. Three minutes later the same
       slot read as the *newest*, so the run overwrote `pdfcer-gui2`, which held
       that afternoon's build. Nothing was corrupted and nothing was lost that
       git does not have, but the fallback silently aged by a day. Repeat the
       lock and it ages indefinitely, one build at a time, while every run
       reports success.

    The `Built:` stamp has the property the mtime was reached for and does not
    have: **it is written by the run that produced the build and by nothing
    else.** Running the exe does not touch it. A failed rename does not touch
    it. It travels inside the directory, so it cannot be deleted by hand
    without deleting the build, and it is already printed for the operator to
    read — which is the other half of why it is the right source: the number
    the rotation decides on is the number they can see.

    # Failure is reported and never fatal

    OneDrive is a network-backed folder: it can be syncing, locked, offline, or
    out of quota, and none of that says anything about the build sitting
    correctly in `D:uilds`. Raising here would throw away a good package
    because a copy failed, so every problem prints and returns.
    """
    if not MIRROR_ROOT.is_dir():
        print()
        print(f"package-portable: mirror skipped - {MIRROR_ROOT} is not there.")
        return

    def age_key(slot: str) -> float:
        """When the build in `slot` was PACKAGED, as a POSIX timestamp.

        `-1.0` means "infinitely old, replace this one" and covers every case
        where the answer is not knowable: no directory, an empty directory, no
        `BUILD-INFO.txt`, an unreadable one, or a `Built:` line that does not
        parse. All five mean the same thing operationally — there is no build
        here worth protecting — and collapsing them is right, because a slot
        this function cannot describe is a slot it must not defend.

        Deliberately NOT `d.stat().st_mtime`; see the rotation note above for
        the two events that made mtime lie.
        """
        d = MIRROR_ROOT / slot
        if not d.is_dir() or not any(d.iterdir()):
            return -1.0
        info = d / "BUILD-INFO.txt"
        try:
            for line in info.read_text(encoding="utf-8", errors="replace").splitlines():
                if line.startswith("Built:"):
                    stamp = line.split(":", 1)[1].strip()
                    return datetime.strptime(stamp, "%Y-%m-%d %H:%M:%S").timestamp()
        except (OSError, ValueError):
            return -1.0
        return -1.0

    # ★★ `--slot` OVERRIDES THE ROTATION, and the case it exists for is
    # RETRACTION.
    #
    # The rotation protects the newest build, which is right when the newest
    # build is good. It is exactly wrong when the newest build is the one being
    # withdrawn: on 2026-08-20 a published build linked an engine revision whose
    # reflow could displace 1,676 labels on a text edit, and the replacement run
    # correctly aimed at the OTHER slot — the day-old fallback — leaving the
    # hazard in place and destroying the one good copy.
    #
    # A rotation cannot know that. "This build is bad" is a fact only the
    # operator or the person retracting it has, so it is an argument rather than
    # an inference. `choices=` means a typo is an error rather than a directory
    # created beside the two real ones.
    target_name = forced or min(MIRROR_SLOTS, key=age_key)
    # ★ Print BOTH slots' ages and which one is about to go.
    #
    # The rotation is the one part of this script whose correctness the operator
    # cannot see afterwards — a successful mirror looks identical whether it
    # replaced the right slot or the wrong one, which is exactly how the mtime
    # defect survived. Naming the two dates makes a wrong choice visible on the
    # run that makes it rather than on the day the fallback is needed.
    for slot in MIRROR_SLOTS:
        age = age_key(slot)
        when = (
            datetime.fromtimestamp(age).strftime("%Y-%m-%d %H:%M:%S")
            if age >= 0
            else "no readable build"
        )
        marker = "  <- replacing this one" if slot == target_name else ""
        print(f"  {slot:<12} {when}{marker}")
    target = MIRROR_ROOT / target_name
    keeps = [s for s in MIRROR_SLOTS if s != target_name]

    # ★ KEEP `userdata/` ACROSS A ROTATION.
    #
    # These slots are not archives — the operator can run the exe straight out
    # of one, and the moment they do, pdfcer creates `userdata/` beside it and
    # writes their settings, their dock layout, their recent files and their
    # per-document page-display choices into it.
    #
    # A rotation is `rmtree` then `copytree`, so without this the next release
    # into that slot would DELETE all of it — and then sync the deletion to
    # every other machine, which is worse than losing it locally.
    #
    # This is the project's own published update procedure, applied to itself:
    # *"replace the program files, keep your `userdata` folder."* `BUILD-INFO`
    # tells the operator exactly that, and a mirror that did the opposite would
    # be contradicting its own instructions inside the same directory.
    #
    # Held in a temporary sibling rather than copied twice: the slot may hold
    # tens of megabytes and the state is small, but a move is atomic-ish on the
    # same volume and cannot half-copy.
    keep = target / "userdata"
    stash = None
    if keep.is_dir():
        stash = MIRROR_ROOT / f".{target_name}-userdata-in-flight"
        if stash.exists():
            shutil.rmtree(stash, ignore_errors=True)
        try:
            shutil.move(str(keep), str(stash))
        except OSError as e:
            print()
            print(f"package-portable: mirror SKIPPED - could not protect {keep}: {e}")
            print("  Refusing to replace a slot whose settings could not be set aside.")
            return

    def _force(func, path, _exc):
        """Clear the read-only bit and retry — `rmtree`'s error handler.

        ★ OneDrive needs this and a local directory does not. A synced folder
        can carry the read-only attribute (it is how the client marks
        cloud-backed items), and `os.unlink`/`os.rmdir` then fail with
        `WinError 5 Access is denied` on a file the operator plainly owns. The
        first real rotation failed exactly there, on `models\ocrs`.

        `onerror` rather than `onexc` because this machine runs Python 3.11;
        `onexc` arrived in 3.12 and using it here would raise `TypeError` on
        the version that is actually installed.

        If the retry also fails the exception propagates to the caller's
        `except OSError`, which restores `userdata/` and reports — so a locked
        slot costs a mirror, never the operator's settings.
        """
        os.chmod(path, stat.S_IWRITE)
        func(path)

    # ★★ STAGE, THEN SWAP. The old order destroyed the fallback it exists to
    #    protect — measured, on 2026-08-20.
    #
    # This block used to be `rmtree(target)` followed by `copytree(out, target)`,
    # with the failure path printing:
    #
    #     The build in {out} is fine; only the OneDrive copy did not happen.
    #
    # That sentence was **false**, and it was false in the worst available
    # direction. The slot is cleared first, so a failure anywhere after the
    # `rmtree` leaves it EMPTY — and on 2026-08-20 it did: `pdfcer-gui1` was
    # locked by another process, the `rmtree` partially succeeded, the
    # `copytree` raised `WinError 32`, and the operator's previous build was
    # gone. The message said the copy "did not happen".
    #
    # The two-slot rotation exists for exactly one reason, stated in
    # `RESUME.md`: *"the previous build stays intact beside the new one, to fall
    # back to and to compare against."* A rotation that can delete the previous
    # build has removed the only property it was built to provide, silently, at
    # the moment a build is most likely to be wrong.
    #
    # ★★★ AND `rmtree` IS NOT ATOMIC EITHER, WHICH THE FIRST FIX MISSED.
    #
    # The first repair, earlier the same day, was *stage then clear then copy* —
    # and it failed again, in the same way, on the very next run:
    #
    #     mirror FAILED - [WinError 32] … pdfcer-gui1
    #       pdfcer-gui1 is locked by another process … It still holds the
    #       previous build; nothing was replaced.
    #
    # `pdfcer-gui1` was empty afterwards. `shutil.rmtree` walks depth-first and
    # deletes as it goes, so a lock on **one file** leaves everything it had
    # already removed removed. Moving the clear later in the sequence bought
    # nothing, because the clear is itself the non-atomic act — and the message
    # was confidently wrong for the second time in one day.
    #
    # The lock is not incidental, either: the only process holding it is
    # **OneDrive's own sync client**, which opens files it is uploading. On a
    # synced folder that hazard is permanent, so the deploy has to be safe
    # against it rather than lucky.
    #
    # ## What is actually atomic: renaming a directory
    #
    # A directory rename either happens or does not. It cannot half-happen, and
    # on Windows it fails outright if anything inside is open — which is exactly
    # the guarantee that was missing. So nothing is ever deleted in place:
    #
    #   1. copy the new build into `.slot-incoming`      (slow, and safe:
    #                                                     the slot is untouched)
    #   2. rename `slot`  →  `.slot-outgoing`            (atomic; fails clean)
    #   3. rename `.slot-incoming`  →  `slot`            (atomic)
    #   4. delete `.slot-outgoing`                       (best effort)
    #
    # Step 4 is the only `rmtree`, and it runs against a directory nothing is
    # pointing at any more. If it fails, the operator has a stray hidden folder
    # — not a missing build.
    #
    # | step | if it fails | the slot holds |
    # |---|---|---|
    # | 1 copy into staging | the payload never reached the volume | **the previous build**, untouched |
    # | 2 rename the slot aside | the slot is locked — the case that fired twice | **the previous build**, untouched, because a failed rename moves nothing |
    # | 3 rename staging in | the previous build is at `.slot-outgoing` and the new one at `.slot-incoming`, and the message names both | nothing, briefly, and recoverably |
    # | 4 delete the old one | a stray hidden folder | **the new build** |
    staging = MIRROR_ROOT / f".{target_name}-incoming"
    outgoing = MIRROR_ROOT / f".{target_name}-outgoing"
    try:
        if staging.exists():
            shutil.rmtree(staging, onerror=_force)
        if outgoing.exists():
            shutil.rmtree(outgoing, onerror=_force)
        # `copytree` of the package directory's CONTENTS, not the timestamped
        # folder itself: the slot name is the identity the operator navigates
        # by, and nesting `pdfcer-gui1/pdfcergui-2026…/pdfcer-gui.exe` would make
        # them click through a folder whose name they already know.
        # `BUILD-INFO.txt` carries the real identity inside.
        shutil.copytree(out, staging)
    except OSError as e:
        print()
        print(f"package-portable: mirror FAILED - {e}")
        print(f"  The build in {out} is fine, and {target_name} still holds the")
        print("  previous build — nothing was replaced.")
        shutil.rmtree(staging, ignore_errors=True)
        if stash is not None:
            shutil.move(str(stash), str(target / "userdata"))
        return

    moved_aside = False
    try:
        if target.exists():
            os.rename(target, outgoing)
            moved_aside = True
    except OSError as e:
        print()
        print(f"package-portable: mirror FAILED - {e}")
        print(f"  {target_name} is locked — most likely OneDrive is syncing it, or the exe")
        print("  in it is running. A failed rename moves nothing, so it still holds the")
        print("  previous build in full. Nothing was replaced.")
        print(f"  The build in {out} is fine. Try again in a moment.")
        shutil.rmtree(staging, ignore_errors=True)
        if stash is not None:
            shutil.move(str(stash), str(target / "userdata"))
        return

    try:
        os.rename(staging, target)
    except OSError as e:
        print()
        print(f"package-portable: mirror FAILED - {e}")
        print(f"  ⚠ {target_name} is temporarily absent. Nothing is lost:")
        print(f"    the PREVIOUS build is at {outgoing}")
        print(f"    the NEW build is at      {staging}")
        print("  Rename whichever you want to the slot name. The other slot is untouched.")
        if stash is not None:
            shutil.move(str(stash), str(staging / "userdata"))
        return

    # Only now, and against a directory nothing points at.
    if moved_aside:
        shutil.rmtree(outgoing, ignore_errors=True)
    if stash is not None:
        shutil.move(str(stash), str(keep))
        print(f"  kept the existing userdata/ in {target_name}")

    print()
    print(f"package-portable: mirrored to {target}")
    print(f"  (replaced the older slot; {', '.join(keeps)} still holds the previous build)")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--dest",
        type=Path,
        default=DEFAULT_DEST,
        help="destination root (default: D:/builds)",
    )
    ap.add_argument(
        "--no-build",
        action="store_true",
        help="package the existing target/release binary without rebuilding",
    )
    ap.add_argument(
        "--no-update",
        action="store_true",
        help=(
            "do NOT refresh the engine to D:/Dev/pdfcer's latest commit first. "
            "Only for reproducing an exact earlier revision — see ENGINE_CRATES"
        ),
    )
    ap.add_argument(
        "--verify",
        action="store_true",
        help="run the workspace tests and the CI gates, and record the result",
    )
    ap.add_argument(
        "--note",
        default="",
        help="one-line summary of what this milestone added, for BUILD-INFO.txt",
    )
    ap.add_argument(
        "--slot",
        default=None,
        choices=MIRROR_SLOTS,
        help=(
            "force which OneDrive slot this build replaces, overriding the "
            "replace-the-older rotation. For RETRACTING a build: the slot "
            "holding the bad one is by definition the NEWER, and the rotation "
            "would protect it and overwrite the good fallback instead."
        ),
    )
    ap.add_argument(
        "--self-test",
        action="store_true",
        help="assert this script's own invariants and exit; packages nothing",
    )
    args = ap.parse_args()

    if args.self_test:
        return self_test()

    if not (REPO / "Cargo.toml").is_file():
        print(f"package-portable: {REPO} is not the pdfcer-gui workspace root.")
        return 1
    if not (ENGINE / "Cargo.toml").is_file():
        # Not a nicety. The path dependencies point here; without it the
        # build below fails with a cargo error about a missing manifest
        # that does not mention why the path matters.
        print(f"package-portable: the engine tree {ENGINE} is missing.")
        print("  crates/pdfcer-gui depends on pdfcer-core and pdfcer-render by path.")
        return 1

    # --- refresh the engine, BEFORE the identity is read --------------------
    #
    # ★★ OPERATOR INSTRUCTION, 2026-08-17: *"always update core render and
    # print before building the latest."*
    #
    # Automated rather than written down as a step, because a step that has to
    # be remembered is one that gets skipped exactly when it matters. The
    # engine dependency is `git = "file:///D:/Dev/pdfcer", branch = "main"`, so
    # `Cargo.lock` pins a revision and ONLY `cargo update` moves it — a build
    # taken without this silently ships an engine older than the repository
    # has, with nothing anywhere to say so.
    #
    # That is not a hypothetical cost. A stale pin left this shell eight
    # commits behind `1e7a0be`, the fix that made `Separation`, `DeviceN`,
    # `Lab`, `CalGray` and `CalRGB` IMAGES decode instead of being dropped from
    # the raster — eighteen pictures missing from the operator's own file, with
    # the OLD shell rendering it correctly while the rebuild did not. The
    # engine repository moved 8, then 12, then 4, then 6 commits ahead of the
    # lock inside a single afternoon.
    #
    # ★ BEFORE the identity block below, and that ordering is the whole point:
    # `locked_engine_rev` reads `Cargo.lock`, so updating afterwards would name
    # one revision in the folder and link another. It is also before `--verify`,
    # because tests must run against the engine that is going to ship.
    #
    # A failure here is REPORTED and does not stop the build. The engine is
    # another session's working repository and `cargo update` can legitimately
    # fail — the branch mid-rebase, the git cache locked. Refusing to package
    # would make this script's convenience into a veto over the operator's
    # build, and the honest fallback is the previous revision plus a loud line
    # saying so. `BUILD-INFO.txt` names what was actually linked either way.
    if not args.no_update:
        before = locked_engine_rev(REPO)
        print(f"package-portable: cargo update {' '.join(ENGINE_CRATES)} ...")
        rc = subprocess.run(
            ["cargo", "update", *[a for c in ENGINE_CRATES for a in ("-p", c)]],
            cwd=REPO,
            check=False,
        ).returncode
        after = locked_engine_rev(REPO)
        if rc != 0:
            print("  WARNING: the engine update FAILED.")
            print(
                f"           Packaging against the revision already in Cargo.lock "
                f"({(before or 'unknown')[:7]})."
            )
            print(
                "           If D:/Dev/pdfcer is mid-rebase or its git cache is locked, "
                "retry;"
            )
            print("           otherwise this build is older than the engine repository.")
        elif before and after and before != after:
            print(f"  engine {before[:7]} -> {after[:7]}")
            # ★ The trap this automation creates, and it caught its author
            # within one run of being written.
            #
            # Updating the engine as a build step means the revision that
            # SHIPS can differ from the one whatever tests were last run
            # against — including a `cargo test` the operator ran by hand five
            # minutes earlier, and including the revision quoted in a `--note`
            # typed before the update happened. Both went wrong on the first
            # real use: the note said `3c4c00e`, the binary linked `0d6f4ac`.
            #
            # `--verify` closes it, because the update runs BEFORE the identity
            # block and therefore before verification. Without it, say so — a
            # build whose engine moved under it and was never re-tested is
            # exactly the state `BUILD-INFO.txt`'s verification line exists to
            # report, and a warning here reaches the person who can still act.
            if not args.verify:
                print(
                    "  WARNING: the engine MOVED and --verify was not passed, so nothing"
                )
                print(
                    "           has been tested against the revision this build will link."
                )
                print(
                    "           Re-run with --verify, and check any revision quoted in --note."
                )
        else:
            print("  engine already at the latest commit")

    # --- identity, before anything is built --------------------------------
    #
    # Computed for BOTH trees with the same three questions: what commit,
    # what did it say, and does the tree carry changes that can reach a
    # compiler. `dirty_of()` is shared rather than duplicated because the
    # narrow definition of "dirty" is the load-bearing part, and two
    # copies of it would drift.
    def dirty_of(cwd: Path) -> tuple[list[str], list[str]]:
        changed = [
            path_of(l) for l in git("status", "--porcelain", cwd=cwd).splitlines() if l.strip()
        ]
        build = [p for p in changed if p.startswith(BUILD_AFFECTING)]
        return build, [p for p in changed if p not in build]

    # ★★ THE ENGINE'S IDENTITY IS THE LOCKED REVISION, NOT THE TREE'S HEAD —
    # rewritten 2026-08-17 when the dependency form changed.
    #
    # This used to read `git rev-parse HEAD` in the engine tree, which was
    # correct while `pdfcer-gui` took the engine by PATH: a path dependency
    # compiles the working tree, so the tree's HEAD (plus a dirty flag) was
    # what got linked.
    #
    # It is now `git = "file:///D:/Dev/pdfcer", branch = "main"`. Cargo clones
    # that repository and builds a **specific commit** out of `~/.cargo/git/`,
    # so the working tree is not compiled at all. Two consequences, and both
    # would have made the old code lie:
    #
    #   1. **A dirty engine worktree can no longer reach the binary.** The
    #      `-enginedirty` suffix would have fired on a build it does not
    #      describe — and this script's own docstring says a warning that
    #      fires when nothing is wrong is one that gets ignored when
    #      something is.
    #   2. **HEAD can be AHEAD of what was linked.** `Cargo.lock` pins a
    #      revision and only `cargo update` moves it, so committing in the
    #      engine does not change this build. Naming HEAD would have credited
    #      the binary with commits it does not contain, which is the more
    #      dangerous error of the two.
    #
    # So the identity is read from `Cargo.lock`, which is the only artefact
    # that records what was actually compiled. `git log` in the engine tree is
    # still used to turn that revision into a subject line, because a hash
    # with no sentence beside it tells the operator nothing.
    engine_locked = locked_engine_rev(REPO)
    engine_short = (engine_locked or "unknown")[:7]
    engine_subject = (
        git("log", "-1", "--format=%s", engine_locked) if engine_locked else ""
    )
    # Reported, never in the name: the tree may be mid-edit by the session
    # that owns it, and that is now simply none of this build's business.
    dirty_build, dirty_other = dirty_of(ENGINE)
    engine_head = git("rev-parse", "--short", "HEAD") or "unknown"
    engine_behind = (
        git("rev-list", "--count", f"{engine_locked}..HEAD") if engine_locked else ""
    )

    shell_short = git("rev-parse", "--short", "HEAD", cwd=REPO) or "unknown"
    shell_subject = git("log", "-1", "--format=%s", cwd=REPO)
    shell_dirty_build, shell_dirty_other = dirty_of(REPO)
    src = source_digest(REPO)

    stamp = datetime.now().strftime("%Y%m%d-%H%M")
    # The digest joins the NAME only when the shell tree is dirty. On a
    # clean tree the commit already identifies the bytes, and a
    # permanently-appended 12-hex string would be noise in every folder
    # name; on a dirty tree the commit identifies the last checkpoint and
    # nothing else, so the digest is the only thing distinguishing this
    # build from the next one taken thirty seconds later.
    name = f"pdfcergui-{stamp}-{engine_short}-{shell_short}"
    if shell_dirty_build:
        name += f"-dirty-{src}"
    # ★ No `-enginedirty`. It was removed on 2026-08-17 with the dependency
    # change above: the engine is built from a committed revision out of
    # cargo's git cache, so its working tree cannot reach this binary and a
    # suffix claiming otherwise would be false. The tree's state is still
    # REPORTED in `BUILD-INFO.txt` — it is useful context about the
    # repository — it is just no longer a claim about the payload.
    out = args.dest / name

    if out.exists() and any(out.iterdir()):
        print(f"package-portable: {out} already exists and is not empty.")
        return 2

    # --- verify, BEFORE building -------------------------------------------
    #
    # Order is deliberate: a failed verification should cost the operator
    # nothing and leave no folder behind. Verifying after packaging would
    # produce a written build that the same run then declares unfit.
    verification = "  not run for this package (pass --verify to run it)"
    if args.verify:
        ok, verification = run_verification(REPO)
        if not ok:
            print("\npackage-portable: verification failed; nothing packaged.")
            print(verification)
            return 1

    # --- build --------------------------------------------------------------
    if not args.no_build:
        print("package-portable: cargo build --release -p pdfcer-gui ...")
        # PDFCER_BUILD_STAMP -- the LOCAL build time, stamped into the About box.
        #
        # `crates/pdfcer-gui/build.rs` reads this and falls back to computing UTC
        # when it is unset. The fallback exists because the workspace may not add
        # a date crate (PROJECT_PLAN.md section 2 forbids any dependency that is
        # not already in pdfcer's lockfile) and a build script with no date crate
        # cannot know the machine's UTC offset. Python can, so a packaged build
        # -- the kind an operator actually runs -- gets the local wall-clock time
        # they would compare against, and an ad-hoc `cargo build` gets an honest
        # UTC stamp that says UTC.
        #
        # `%z` is emitted as an explicit offset rather than a zone abbreviation:
        # abbreviations are ambiguous across regions and the offset never is.
        build_env = os.environ.copy()
        build_env["PDFCER_BUILD_STAMP"] = datetime.now().astimezone().strftime(
            "%Y-%m-%d %H:%M %z"
        )
        rc = subprocess.run(
            ["cargo", "build", "--release", "-p", "pdfcer-gui"],
            cwd=REPO,
            check=False,
            env=build_env,
        ).returncode
        if rc != 0:
            print("package-portable: the release build failed; nothing packaged.")
            return 1

    rel = REPO / "target" / "release"
    missing = [b for b in BINARIES if not (rel / b).is_file()]
    if missing:
        print(f"package-portable: missing binaries in {rel}: {', '.join(missing)}")
        return 1

    # --- assemble -----------------------------------------------------------
    out.mkdir(parents=True, exist_ok=True)
    for b in BINARIES:
        shutil.copy2(rel / b, out / b)
    copied_docs = []
    for d in PAYLOAD_DOCS:
        s = REPO / d
        if s.is_file():
            shutil.copy2(s, out / d)
            copied_docs.append(d)
        else:
            print(f"package-portable: WARNING — {d} not found at the workspace root")

    # --- asset directories that must travel as loose files ------------------
    #
    # A MISSING SOURCE IS FATAL, not a warning. The two things in this list's
    # future are licensed assets whose absence would be silent: the package
    # would build, the operator would get a program that reports "no OCR
    # models" from a folder that was supposed to contain them, and the
    # attribution in `THIRD_PARTY_LICENSES.md` would be describing files that
    # are not there. Every other payload item degrades to a warning because
    # `README.md` going missing costs a reader a document; this costs the
    # package its correctness in both directions at once.
    copied_assets, missing_assets = copy_asset_dirs(out, ENGINE)
    if missing_assets:
        print("package-portable: declared asset directories are missing from the engine tree:")
        for m in missing_assets:
            print(f"  {m}")
        print("  Nothing was packaged. PAYLOAD_ASSET_DIRS names files this build")
        print("  is obliged to ship AND to attribute; shipping the attribution")
        print("  without the files would make THIRD_PARTY_LICENSES.md describe")
        print("  something the operator does not have.")
        shutil.rmtree(out, ignore_errors=True)
        return 1

    # --- what changed since the last build ----------------------------------
    def changelog(cwd: Path, since: str | None, label: str) -> str:
        """Commits in `cwd` since the previous build, formatted for the file.

        `since` may name a commit this tree does not contain — a build
        packaged before a history rewrite, or a `BUILD-INFO.txt` copied
        between machines. `git log bad..HEAD` writes to stderr and returns
        nothing, and `git()` returns only stdout, so that failure would
        otherwise render as a confident, empty "(none)": a claim that
        nothing changed, which is the worst available answer. Verifying
        the ref first turns it into a stated fallback.
        """
        if since:
            # `git cat-file -e` answers through its EXIT CODE and prints
            # nothing, so this cannot go through `git()` — that helper
            # returns stdout, which is empty either way.
            exists = subprocess.run(
                ["git", "cat-file", "-e", f"{since}^{{commit}}"],
                cwd=cwd,
                capture_output=True,
                check=False,
            ).returncode == 0
            if not exists:
                label += (
                    "\n  (the previous build's commit is not in this tree;"
                    " showing recent history instead)"
                )
                since = None
        if since:
            out_ = git("log", "--oneline", "--no-decorate", f"{since}..HEAD", cwd=cwd)
        else:
            out_ = git("log", "--oneline", "--no-decorate", "-10", cwd=cwd)
        body = "\n".join(f"  {l}" for l in out_.splitlines()) if out_ else "  (none)"
        return f"{label}\n{body}"

    prev = previous_build(args.dest)
    if prev:
        prev_engine, prev_shell, prev_src = prev
        engine_log = changelog(
            ENGINE, prev_engine, f"Engine commits since the previous build ({prev_engine}):"
        )
        shell_log = changelog(
            REPO, prev_shell or None, f"Shell commits since the previous build ({prev_shell}):"
        )
        digest_line = (
            "  Source digest UNCHANGED since the previous build — this is the\n"
            "  same program, however the commits read."
            if prev_src == src
            else f"  Source digest changed: {prev_src} -> {src}"
        )
    else:
        engine_log = changelog(ENGINE, None, "Recent engine commits (no previous build to diff):")
        shell_log = changelog(REPO, None, "Recent shell commits (no previous build to diff):")
        digest_line = "  No previous build to compare the source digest against."

    warn = ""
    if shell_dirty_build:
        listed = "\n".join(f"  {q}" for q in shell_dirty_build[:10])
        more = "\n  ..." if len(shell_dirty_build) > 10 else ""
        warn += (
            "\n*** THE SHELL WAS BUILT FROM AN UNCOMMITTED WORKING TREE ***\n"
            "The shell commit below is the last CHECKPOINT, not what was compiled.\n"
            "Use the source digest to tell this build apart from another; the\n"
            "code itself is in no commit and cannot be recovered from the hash.\n"
            f"{listed}{more}\n"
        )
    # ★ The engine tree's state is CONTEXT now, not a warning about the
    # payload. Since 2026-08-17 the engine is compiled from a committed
    # revision out of cargo's git cache, so nothing uncommitted in
    # D:\Dev\pdfcer can reach this binary — see `locked_engine_rev`.
    #
    # It is still reported, because it answers the question an operator
    # actually has when a fix they know landed is not in the build: *is the
    # engine ahead of what I am running?* That question used to be
    # unanswerable and it is the one that cost eighteen images on a real file.
    if dirty_build or dirty_other:
        changed = dirty_build + dirty_other
        listed = "\n".join(f"  {q}" for q in changed[:10])
        more = "\n  ..." if len(changed) > 10 else ""
        warn += (
            "\nEngine tree note: D:\\Dev\\pdfcer had uncommitted changes when this was\n"
            "packaged. They are NOT in this binary — the engine is built from the\n"
            "committed revision named below, out of cargo's git cache — so this is\n"
            "context rather than a warning:\n"
            f"{listed}{more}\n"
        )

    if engine_behind and engine_behind not in ("", "0"):
        warn += (
            f"\n*** THE ENGINE HAS MOVED ON: {engine_behind} COMMIT(S) NOT IN THIS BUILD ***\n"
            f"This binary links {engine_short}; D:\\Dev\\pdfcer's main is at {engine_head}.\n"
            "Cargo.lock pins the revision and only `cargo update` moves it, so this\n"
            "is deliberate rather than broken. To pick them up:\n"
            "  cargo update -p pdfcer-core -p pdfcer-render -p pdfcer-print\n"
            "Worth checking before investigating any RENDERING complaint as a shell\n"
            "defect: a stale engine pin has already produced exactly that confusion.\n"
        )

    # Hoisted out of the f-string: an expression part may not contain a
    # backslash before Python 3.12, and this machine runs 3.11.
    note_block = f"THIS BUILD\n----------\n{args.note}\n" if args.note else ""

    (out / "BUILD-INFO.txt").write_text(
        f"""pdfcer-gui portable build
=======================
{warn}
Built:  {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Engine: {engine_short}  {engine_subject}
        (D:\\Dev\\pdfcer, branch {git("rev-parse", "--abbrev-ref", "HEAD")})
Shell:  {shell_short}  {shell_subject}
        (D:\\Dev\\pdfcer-gui, branch {git("rev-parse", "--abbrev-ref", "HEAD", cwd=REPO)})
Shell source digest: {src}
        Identifies the BYTES compiled, which the commit above does not when
        the tree is dirty. Two builds with the same digest are the same
        program; a different digest means the source differs, somewhere.

WHAT THIS IS
------------
The NEW pdfcer shell, rebuilt from scratch, with pdfcer's engine linked in
statically. One executable, no installer, no registry writes, nothing
outside this folder. Run pdfcer-gui.exe.

It is not a replacement for a pdfcer build yet, and FEATURES.md ships
beside it so you can tell which is which. Install it alongside a pdfcer
build rather than instead of one.

That sentence used to name measure, redaction, the settings dialog and
text editing as living only in the OLD shell. All four have since landed
here, so the honest reason to keep both installed is narrower: this shell
is still mid-rebuild and FEATURES.md is the list of what is finished.
Read it before concluding something is broken.

WHAT TO TRY
-----------
Open a PDF, then: click an object and press Delete; drag a selection;
press Escape mid-drag; switch Read / Review / Edit with Ctrl+1/2/3; drag
a panel to another dock column and restart to confirm the layout came
back. FEATURES.md's first list is the full set that should work.

New since the last build, and all of it in File > pdfcer > Settings:
  * Appearance > size of pdfcer's own menus and text  (drag it; it
    applies while you drag, and Cancel puts it back)
  * Drawing the page > how a page is sized when a document opens, and
    which of rulers / grid / guides start switched on. Both apply to the
    NEXT document you open, not the one on screen.

YOUR SETTINGS LIVE IN THIS FOLDER
---------------------------------
On first run the app creates `userdata/` here. To update, replace the
binary but KEEP `userdata/`.

VERIFICATION
------------
{verification}

{note_block}
{engine_log}

{shell_log}

Source digest:
{digest_line}

Files in this build: {", ".join(BINARIES + copied_docs + [d + "/" for d in copied_assets])}

THIRD-PARTY MATERIAL
--------------------
THIRD_PARTY_LICENSES.md carries the licence of every Rust crate this binary
links, and — in a hand-written epilogue — the licences of the data and font
assets the engine embeds, which no generator can see. The same attributions
are in the program itself: File > pdfcer > About pdfcer.
""",
        encoding="utf-8",
    )

    total = sum(f.stat().st_size for f in out.rglob("*") if f.is_file())
    print(f"\npackage-portable: wrote {out}")
    for f in sorted(out.iterdir()):
        print(f"  {f.name:<26} {f.stat().st_size:>10,} bytes")
    print(f"  {'TOTAL':<26} {total:>10,} bytes")

    # ★ LAST — after `BUILD-INFO.txt` has been written into `out`.
    #
    # The first version called this while the warning text was still being
    # assembled, several statements before the file existed, and the mirrored
    # slot came out **without a BUILD-INFO.txt** — missing the one document
    # that says which engine and which shell the binary is. The exe was
    # otherwise perfect, which is what made it easy to miss: the folder looks
    # complete unless you go looking for the file that identifies it.
    #
    # Mirroring is the last thing that happens for exactly this reason. Every
    # payload file is on disk by now, and a mirror taken at any earlier point
    # is a copy of a directory that is still being built.
    mirror(out, forced=args.slot)

    prune(out.parent, keep=KEEP_BUILDS)

    # ★ The engine's WORKING TREE is no longer a warning — it cannot reach the
    # binary. What IS worth a console line is the engine being ahead of the
    # locked revision, because that is the question an operator has when a fix
    # they know landed is not in the build they are holding.
    if engine_behind and engine_behind not in ("", "0"):
        print(
            f"\n  NOTE: D:\\Dev\\pdfcer is {engine_behind} commit(s) ahead of the "
            f"revision\n        linked here ({engine_short}). To pick them up:\n"
            "        cargo update -p pdfcer-core -p pdfcer-render -p pdfcer-print"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
