//! # `leaf_geometry` — **the same four questions, asked of something inside a
//! # form**
//!
//! `OPERATOR_REQUESTS.md` **O70**. The descent reaches an object painted inside
//! a form XObject and can move and delete it; what it cannot yet do is go one
//! level deeper, into that object's own subpaths and anchors, because every
//! accessor that answers *"what is inside this?"* took a **page paint-order
//! index** and a leaf does not have one.
//!
//! `ObjectModelProvider`'s `_of` family answers the same questions for either
//! index space. This is what says they answer *correctly* for the space that
//! had no answer before.
//!
//! ## ★★★ Why an integration test on a real file, not a unit test on a stub
//!
//! Because the thing under test is a **geometry mapping**, and the stub
//! (`canvas::target::StubTargets`) carries rectangles rather than paths: it can
//! model *which* target is hit and cannot model where a path's anchors are. A
//! unit test against it would assert that the plumbing returns what the stub
//! was given, which is the shape of test this project has twice found asserting
//! nothing.
//!
//! ⇒ So this decomposes `fixtures/form-xobject.pdf` — three fat strokes inside
//! one form, at coordinates its generator states — and checks the numbers that
//! come back against the numbers the generator wrote.
//!
//! ## ★★ The number that matters, and why it is a MAGNITUDE
//!
//! A `FormLeaf`'s geometry is *"already mapped into page space"* — the engine's
//! phrase — so the placement offset the fixture applies (`1 0 0 1 40 40 cm`)
//! must already be in the answer. The bar the generator draws at `y = 110` in
//! the form's own space must come back at **`y = 150`**.
//!
//! That is the whole hazard of this address space in one number. A build that
//! returned the form-local coordinate would be off by exactly the placement,
//! would look entirely plausible on any page, and would drag the operator's
//! line forty points away from where they grabbed it.

use pdfcer_gui::panels::objects::provider::{ObjectModelProvider, TargetId};

/// The fixture, generated by `tools/gen-form-xobject-fixture.py`.
fn provider() -> ObjectModelProvider {
    let path = std::path::Path::new(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../fixtures/form-xobject.pdf"
    ));
    let doc = pdfcer_core::document::Document::load(path)
        .expect("fixture form-xobject.pdf must load — run tools/gen-form-xobject-fixture.py");
    let pages = pdfcer_core::page_tree::pages(&doc).expect("the page tree walks");
    ObjectModelProvider::build(&doc.view(), &pages[0], 0).expect("the page decomposes")
}

/// The fixture's shape, asserted before anything is asked of it.
///
/// ★ A precondition rather than a subject: every test below indexes leaf 0, and
/// on a file that decomposed differently they would all fail with messages
/// about geometry when the truth was that the fixture had changed.
#[test]
fn the_fixture_is_one_container_over_three_strokes() {
    let provider = provider();
    let model = provider.page_objects();
    assert_eq!(
        model.objects.len(),
        1,
        "one page object — the form itself; the page's whole content is one `Do`"
    );
    assert_eq!(model.leaves.len(), 3, "three strokes inside it");
}

/// ★★★ **A leaf's anchors come back in PAGE space, placement included.**
///
/// The horizontal bar is drawn at `20,110 → 300,110` inside a form placed at
/// `(40, 40)`, so its anchors are at `y = 150` and `x` from 60 to 340.
#[test]
fn a_leafs_anchors_carry_the_forms_placement() {
    let provider = provider();
    let points = provider.subpath_node_points_of(TargetId::Leaf(0), 0);
    assert_eq!(points.len(), 2, "a two-anchor line: {points:?}");

    let ys: Vec<f64> = points.iter().map(|(_, p)| p.y).collect();
    for y in &ys {
        assert!(
            (y - 150.0).abs() < 0.5,
            "★ the bar sits at y=110 in the FORM's space and y=150 on the page — a value near \
             110 means the placement was dropped, which is plausible everywhere and wrong \
             everywhere. Got {ys:?}"
        );
    }
    let xs: Vec<f64> = points.iter().map(|(_, p)| p.x).collect();
    let (min, max) = (
        xs.iter().copied().fold(f64::INFINITY, f64::min),
        xs.iter().copied().fold(f64::NEG_INFINITY, f64::max),
    );
    assert!(
        (min - 60.0).abs() < 0.5 && (max - 340.0).abs() < 0.5,
        "the bar runs 20→300 in the form and 60→340 on the page: {xs:?}"
    );
}

/// ★★ **The anchor indices are object-scoped and start at zero per object.**
///
/// The node verbs take an index in that space, so a leaf whose anchors were
/// numbered from somewhere else would move the wrong point — and the numbers
/// would still be in range.
#[test]
fn the_anchor_indices_are_object_scoped() {
    let provider = provider();
    let points = provider.subpath_node_points_of(TargetId::Leaf(0), 0);
    let indices: Vec<usize> = points.iter().map(|(i, _)| *i).collect();
    assert_eq!(indices, vec![0, 1], "first subpath, first anchors");

    // …and the whole-object list agrees with the per-subpath one, which is what
    // stops the Node rung and the Part rung disagreeing about what anchor 1 is.
    let all = provider.object_node_points_of(TargetId::Leaf(0));
    assert_eq!(all.len(), 2);
    assert_eq!(all[1].0, 1);
    assert!((all[1].1.y - 150.0).abs() < 0.5);
}

/// A leaf that is a path has a Part rung; the container above it does not.
///
/// ★ The second half is the interesting one. `TargetId::Object(0)` is the form
/// XObject, which the decomposition reports as an `Image`-family object with no
/// subpaths — so a double-click on the container must not offer a Part rung,
/// and this is where that answer comes from.
#[test]
fn a_path_leaf_has_parts_and_the_container_does_not() {
    let provider = provider();
    assert!(
        provider.part_kind_of(TargetId::Leaf(0)).is_some(),
        "a stroke inside the form is a path and has subpaths"
    );
    assert!(
        provider.part_kind_of(TargetId::Object(0)).is_none(),
        "the form itself is one opaque object — 8.10.1's /BBox, not geometry"
    );
    assert!(
        provider
            .object_node_points_of(TargetId::Object(0))
            .is_empty(),
        "…and therefore has no anchors to offer"
    );
}

/// ★ **An index the page does not have answers empty, not a panic.**
///
/// The contract every accessor on this provider inherits: a selection can
/// outlive an edit that removed what it named, and the frame that is trying to
/// draw it must survive that.
#[test]
fn an_index_the_page_does_not_have_is_empty_rather_than_fatal() {
    let provider = provider();
    assert!(provider.object_for(TargetId::Leaf(99)).is_none());
    assert!(provider.object_for(TargetId::Object(99)).is_none());
    assert!(
        provider
            .subpath_node_points_of(TargetId::Leaf(99), 0)
            .is_empty()
    );
    assert!(
        provider
            .subpath_node_points_of(TargetId::Leaf(0), 99)
            .is_empty(),
        "…and a subpath the object does not have, too"
    );
}
