//! # `page_generation_covers` — **what `page_content_generation` actually
//! notices**, measured rather than assumed
//!
//! ## Why this test exists
//!
//! `pdfcer-core`'s reply of 2026-08-31
//! (`reply_the_verbs_decomposition_is_gone_and_two_of_your_premises_were_wrong.md`)
//! offers this shell a cheap invalidation key:
//!
//! > *"Your `(page, edit_epoch)` cache key can go. `Pass 186.0` also shipped
//! > `EditSession::page_content_generation(page_index) -> u64` … comparing
//! > object counts means decomposing twice, comparing this means comparing two
//! > integers."*
//!
//! The prize is large and measured: this shell's own decomposition of the
//! operator's benchmark drawing takes **469 ms** for 129,758 objects and
//! 10,256 leaves (`page-objects-built page=0 objects=129758 leaves=10256
//! ms=469`, driven 2026-08-31). Today it is rebuilt on **every** `edit_epoch`
//! bump — including edits that cannot have touched page content at all, such
//! as authoring a form field, which is an `/Annots` change. That is the
//! operator's O74 complaint in its most expensive form.
//!
//! ## ★★★ Why a TEST and not a swap
//!
//! Because the failure mode of a wrong invalidation key is not a slow program.
//! `PageObjects` addresses content **by index**, so a stale model makes
//! `move_objects(page, &[7], …)` edit whatever object 7 is in the *wrong*
//! model — the engine's own words for this are *"silent corruption of the
//! operator's drawing, reported as success"*.
//!
//! ⇒ So before this shell trusts that number, it establishes exactly what the
//! number notices. Each test here is one dependency class, driven through the
//! real verbs, on a fixture built for it.
//!
//! ## ★★ The class this is really about
//!
//! The engine's reply says the memo's key is *"(page id, every `/Contents`
//! entry with its staged span, the effective `/Resources`)"* — and that the
//! forms a page descends into are kept **beside** the key rather than in it,
//! *"because which forms a page paints is an OUTPUT of the decomposition, not
//! an input to it"*.
//!
//! `page_content_generation` is documented as the digest of *"the same key the
//! memo uses"*. If that means the key **without** the form set, then an edit
//! inside a form XObject moves nothing this shell could see — and a shell that
//! had swapped its cache key would keep a stale model after every such edit.
//!
//! That case is not reachable from this shell's UI today (in-form editing is
//! refused, `Refusal::InsideForm`), and `pdfcer-core` Pass 188.0 shipped the six
//! verbs that will make it reachable. **This test is what tells us which order
//! those two things may be done in.**

use pdfcer_core::edit::EditSession;

/// The form fixture: one page object (a form), three path leaves inside it.
/// Generated by `tools/gen-form-xobject-fixture.py`.
fn form_fixture() -> pdfcer_core::document::Document {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../fixtures/form-xobject.pdf"
    );
    pdfcer_core::document::Document::load(std::path::Path::new(path))
        .expect("fixture form-xobject.pdf must load — run tools/gen-form-xobject-fixture.py")
}

/// A page with ordinary content, for the classes that do not need a form.
fn plain_fixture() -> pdfcer_core::document::Document {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../fixtures/a1-titleblock.pdf"
    );
    pdfcer_core::document::Document::load(std::path::Path::new(path))
        .expect("fixture a1-titleblock.pdf must load")
}

/// ★★★ **A content edit moves it.** The baseline: without this the number
/// would be useless in the other direction, and a cache keyed on it would
/// never rebuild.
#[test]
fn a_content_edit_moves_the_generation() {
    let mut session = EditSession::new(plain_fixture());
    let before = session
        .page_content_generation(0)
        .expect("page 0 has a generation");

    // The cheapest real content edit: move an object by a point.
    let objects = session
        .page_objects(0)
        .expect("page 0 decomposes")
        .objects
        .len();
    assert!(objects > 0, "the fixture must have something to move");
    session
        .move_objects(0, &[0], 1.0, 0.0)
        .expect("moving object 0 by one point must succeed");

    let after = session
        .page_content_generation(0)
        .expect("page 0 still has a generation");
    assert_ne!(
        before, after,
        "★ a content edit must move the generation, or a cache keyed on it would serve a pre-edit model for ever"
    );
}

/// ★★★ **AN EDIT INSIDE A FORM MOVES IT — and this test was red for four
/// hours between the two facts.**
///
/// ## The whole exchange, because the shape is worth keeping
///
/// | when | what |
/// |---|---|
/// | 23:30 | measured here: `move_node_in_form` succeeded and the digest was identical, `9733417638757333672` either side |
/// | 23:36 | filed as `request_the_generation_cannot_see_a_form_rewrite.md`, with this file named as the reproduction |
/// | 23:36 | the shell took a workaround — its own counter, bumped at the six `*_in_form` call sites — and **this test was written INVERTED**, asserting the limitation so it would go red the day it stopped being true |
/// | 01:4x | `pdfcer-core` `6e2b69e`: the digest folds in the descended-form set. This test went red on the first build after `cargo update`, naming the counter to delete |
///
/// ★★ That is the third time in two days a test written to assert a
/// *limitation* has closed its own request. The alternative — a comment saying
/// "this does not work yet" — is not executed, so it survives the fix and
/// misleads the next reader instead of catching them.
///
/// ⇒ The assertion is now the ordinary one: an edit that rewrites a form's
/// stream must move the page's content digest, because this shell keys its
/// decomposition on that number and `PageObjects` addresses content by index.
#[test]
fn an_edit_inside_a_form_moves_the_generation() {
    let mut session = EditSession::new(form_fixture());
    let model = session.page_objects(0).expect("page 0 decomposes");
    let leaves = model.leaves.len();
    assert!(
        leaves >= 1,
        "the fixture must decompose to leaves — `page_objects` returned none, \
         which is the pre-Pass-188.0 behaviour and means the engine is too old \
         for this test to mean anything"
    );
    // The first leaf is a path (the fixture paints three strokes), so the node
    // verbs apply to it.
    let editable = model.leaves.iter().filter(|l| l.is_editable()).count();
    assert!(
        editable >= 1,
        "the fixture's leaves must be paths — `is_editable` was a hard `false` \
         for every leaf before Pass 188.0"
    );
    drop(model);

    let before = session
        .page_content_generation(0)
        .expect("page 0 has a generation");

    // Move one node of the first editable leaf. The coordinates are page
    // space, per the engine's contract for the `*_in_form` verbs.
    let outcome =
        session.move_node_in_form(0, 0, 0, pdfcer_core::vector::Point { x: 60.0, y: 60.0 });
    let outcome = outcome.expect("moving a node inside a form must succeed on Pass 188.0+");
    assert!(
        outcome.invocations > 0,
        "the verb must have rewritten at least one invocation: {outcome:?}"
    );

    let after = session
        .page_content_generation(0)
        .expect("page 0 still has a generation");
    assert_ne!(
        before, after,
        "★★★ THE LIMITATION IS BACK: an edit inside a form XObject left the page content \
         digest unchanged. This shell keys its decomposition cache on that number, and \
         `PageObjects` addresses content by INDEX — so a stale model makes the next drag \
         edit whatever that index names in the wrong model, which the engine itself calls \
         silent corruption reported as success. Closed by `pdfcer-core` `6e2b69e`; if this \
         fails, that is what regressed."
    );
}

/// ★★ **An annotation-only edit does NOT move it** — which is the whole prize.
///
/// Authoring a form field or a markup changes `/Annots`, never the page's
/// content stream. Today this shell rebuilds its 469 ms decomposition anyway,
/// because `edit_epoch` cannot tell the two apart. If the generation holds
/// still here, the rebuild can be skipped — and that is the operator's O74
/// complaint answered at its most expensive point.
#[test]
fn an_annotation_edit_does_not_move_the_generation() {
    let mut session = EditSession::new(plain_fixture());
    let before = session
        .page_content_generation(0)
        .expect("page 0 has a generation");

    // ★ Built through the shell's own pen helper rather than as a literal, for
    // the reason `apply::tests` gives for the same call: the spec's fields are
    // `#[non_exhaustive]`-adjacent in practice — a variant gaining a field
    // breaks a literal here and not the shell — and the helper is what the
    // operator's gesture actually produces.
    let spec = pdfcer_gui::canvas::markup::spec_default_pen(
        pdfcer_gui::canvas::markup::MarkupKind::Rectangle,
        &pdfcer_gui::canvas::markup::Geometry::Band {
            start: (50.0, 50.0),
            end: (150.0, 120.0),
        },
    )
    .expect("a band is the Rectangle kind's own geometry");
    session
        .add_markup(0, &spec)
        .expect("adding a square markup must succeed");

    let after = session
        .page_content_generation(0)
        .expect("page 0 still has a generation");
    assert_eq!(
        before, after,
        "an annotation is not page content, so a decomposition cache has \
         nothing to rebuild — if this fails, the generation is coarser than \
         advertised and the 469 ms rebuild cannot be skipped after all"
    );
}
